### ISSUE TITLE
Suggestion - Update Readme with more information

### ISSUE THREAD

**Issue by rtman** [th3rdwave/react-native-safe-area-context#10]
Hi,

I'm interested in using this package, but I'm a little wary of implementing it since the readme is kind of light on details. 

For instance, does this work with all android and ios devices with notches? 
What does this package actually do? (description of how it works)
Will this be actively maintained?
How does this handle devices without notches?

If you could add a bit more to the readme I think that would help people to decide on using this. It's coming recommended from @mikehardy via `react-native-device-info` as a replacement for their `hasNotch` method, so maybe adding that could also help?

**Comment by mikehardy** [comment]
@janicduplessis this is spilling over from discussion on react-native-device-info

@rtman here is the previous thread: https://github.com/react-native-community/react-native-device-info/issues/594#issuecomment-527669853

It does not exist yet but we are thinking it is possible to expose it so then you can answer the boolean "hasNotch" question

**Comment by mikehardy** [comment]
So - a follow on thought @rtman if you are doing your own padding and don't want some other package just auto-fixing it then until some new API existed then it wouldn't work no - for that reason it is a conversation at the moment, not a formal API move and breaking change over on RNDI etc

**Comment by rtman** [comment]
@mikehardy So the only reason we add padding to non notched devices is because react-native's `SafeAreaView` adds vertical padding for ios notched devices. We don't want to add more vertical padding so we just removed it entirely and only add vertical padding to non notched devices. If this package can handle that, then I wouldn't need `hasNotch`.

However since this isn't implemented yet (as far as I know), I'll need to continue using `hasNotch` with `react-native-device-info`. Which is currently bugged by the sync + chrom debugger issue. A constant to check in the meantime would be much appreciated!

**Comment by janicduplessis** [comment]
@rtman The concept of safe area is a bit different than just if the device has a notch. For example the area under the status bar is considered in the safe area zone even when the device has no notch.

I think what you could do in your case is just use the maximum between some static value and the safe area value. So let's say you want to add padding at the bottom of a view of at least 20px you could do `<View style={{ paddingBottom: Math.max(safeAreaInsets.bottom, 20) }} />`.

**Comment by janicduplessis** [comment]
Going to close this, if anyone (or myself when I get time) wants to add more details to the readme feel free to open a PR.
