### ISSUE TITLE
IOS Wrong insets on landscape mode

### ISSUE THREAD

**Issue by Paduado** [th3rdwave/react-native-safe-area-context#100]
I'm running an App in landscape mode in iPhone X and iPhone 11 simulators, and I'm getting the same value for left and right insets, I don't know if thats expected, but I though that the inset should be 0 on the side where there is no nudge?

![image](https://user-images.githubusercontent.com/10711772/83714010-3436e100-a5ef-11ea-817d-cbd442326f47.png)

**Comment by janicduplessis** [comment]
This is expected behaviour because of the rounded corners on the iPhoneX. You can use the edges prop on SafeAreaView if you need more control over which edges the insets are applied to.

**Comment by scottmas** [comment]
The method you describe doesn't work if the phone can be flipped either way horizontally. And this is really important with some UI's. For instance, the right floating bottom button looks really weird in this screenshot:
![image (7)](https://user-images.githubusercontent.com/2257337/97481719-d1860f00-191a-11eb-9cd8-646a30b216ed.png)
