### ISSUE TITLE
Best practices when toggling status-bar visibility

### ISSUE THREAD

**Issue by sbycrosz** [th3rdwave/react-native-safe-area-context#102]
Hello!

We noticed that when toggling status-bar visibility (e.g. navigating from a screen with hidden status-bar to screen with status-bar), the insets provided by react-native-safe-area-context would change; which results in jankyness on the top inset as seen below

![Jun-09-2020 16-41-51](https://user-images.githubusercontent.com/4867178/84126254-404bf400-aa70-11ea-8a47-976534239219.gif)

Is there a best practice to avoid such situation?

Thank you!

**Comment by janicduplessis** [comment]
Hi, this is an interesting use case. I don't really have a good solution for it right now. Maybe you could try using `initialWindowMetrics.insets` for this specific screen. It has the initial values for insets, which will be with the statusbar visible.

Android has a concept of "stable" insets which is the maximum insets possible for each edge and doesn't change at runtime (unless you rotate the screen). Could be interesting to expose these as a proper solution.

**Comment by janicduplessis** [comment]
I'm not sure about this but you could try to use LayoutAnimation to make it look smoother as another possible workaround.

**Comment by sbycrosz** [comment]
Hello!

> Android has a concept of "stable" insets which is the maximum insets possible for each edge and doesn't change at runtime (unless you rotate the screen). Could be interesting to expose these as a proper solution.

This sounds great!

We ended up doing similar hacks by storing the maximum insets possible in memory e.g.

```
 // Assuming the app starts with status-bar visible
  insets = useMemo(() => ({
    top: Math.max(insets.top, rnSafeAreaInsets.top),
    bottom: Math.max(insets.bottom, rnSafeAreaInsets.bottom),
    left: Math.max(insets.left, rnSafeAreaInsets.left),
    right: Math.max(insets.right, rnSafeAreaInsets.right),
  }), [rnSafeAreaInsets]);
```

Will probably be wrong once we rotate the screen, but it's good enough for now ¯\\\_(ツ)_/¯

Cheers!
