### ISSUE TITLE
Problem with Tab Navigation (React Navigation 5)

### ISSUE THREAD

**Issue by nelsonprsousa** [th3rdwave/react-native-safe-area-context#107]
After following [React Navigation Tab navigation](https://reactnavigation.org/docs/tab-based-navigation) I tried to use react-native-safe-area-context with SafeAreaView, to avoid problems with notch screens.

However, I noticed this weird behaviour (only happening on iOS, Android works fine):
![Simulator Screen Shot - iPhone 11 - 2020-06-15 at 02 33 50](https://user-images.githubusercontent.com/8364345/84609919-b0afa680-aeb0-11ea-8ce8-83254d5a4c66.png)

I wasn't expecting that SafeAreaView added that space between the bottom tab and the scroll view. Like I said, in Android this doesn't happen. Also, it works as expected using SafeAreaView from react-native.

Here's the code:
```javascript
import * as React from 'react';
import {Text, View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';
import {ScrollView} from 'react-native-gesture-handler';

function HomeScreen() {
  return (
    <SafeAreaView style={{backgroundColor: 'red'}}>
      <ScrollView style={{backgroundColor: 'yellow'}}>
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
          {new Array(50).fill(0).map((_, index) => (
            <Text key={index}>Index {index}</Text>
          ))}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen name="Home" component={HomeScreen} />
        </Tab.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}
```

Here's the versions I am using (most updated, since I created the repo now to replicate this behaviour):
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.5",
    "react-native-screens": "^2.8.0"
  }
```

Am I doing something wrong? Or is this the expected behaviour and we should add a workaround?

**Comment by aneem** [comment]
@nelsonprsousa I'm also facing the same issue. 
In my case I was able to fix this issue by using the `SafeAreaView` from [react-native-safe-area-view](https://github.com/react-navigation/react-native-safe-area-view) instead of this library.

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa I'm also facing the same issue.
> In my case I was able to fix this issue by using the `SafeAreaView` from [react-native-safe-area-view](https://github.com/react-navigation/react-native-safe-area-view) instead of this library.

Hi @aneem, thanks for your reply. Yeah, with that library or with the built-in SafeAreaView we don't have the problem.

However, I am trying to avoid that library because [it will soon be deprecated in favor of this one](https://github.com/react-navigation/react-native-safe-area-view/issues/98#issuecomment-633791884).

Let's see if someone can lead us in the correct direction 🙏

**Comment by SleeplessByte** [comment]
> Let's see if someone can lead us in the correct direction 🙏

I believe react-navigation is basically setting the bottom safe-area distance to 0 (because their tabbar component takes it into account). There's probably a way to fix this by interopting with them, but I have have been doing is using `useSafeArea()` and NOT applying bottom (as bottom should be 0, because the tab navigator takes care of it).

**Comment by archansel** [comment]
If you are using tab bar or nav bar from react navigation, it already applied padding, if you use custom tab bar or navbar you have to handle it yourself. in your case, you use default tab bar by react navigation, so it already applied bottom padding. so in your screen SafeAreaView you should disable bottom padding `<SafeAreaView edges={['right', 'left', 'top']} />` otherwise it would have double bottom padding

**Comment by nelsonprsousa** [comment]
> If you are using tab bar or nav bar from react navigation, it already applied padding, if you use custom tab bar or navbar you have to handle it yourself. in your case, you use default tab bar by react navigation, so it already applied bottom padding. so in your screen SafeAreaView you should disable bottom padding `<SafeAreaView edges={['right', 'left', 'top']} />` otherwise it would have double bottom padding

Thanks for the tip. That's exactly it. 👌

**Comment by jzxchiang1** [comment]
> why would `<SafeAreaView>` be needed in this instance? doesnt `react-navigation` take care of it for you?

It's useful when you don't use a stack header. For example, https://reactnavigation.org/docs/5.x/handling-safe-area
