### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider

### ISSUE THREAD

**Issue by karimcambridge** [th3rdwave/react-native-safe-area-context#110]
# 👉 [jump to the solution](https://github.com/th3rdwave/react-native-safe-area-context/issues/110#issuecomment-668864576)

**Comment by AleeeKoi** [comment]
Same issue here

**Comment by karimcambridge** [comment]
Nope,. I reverted back as noone seems to know why yet. Not many people are getting the issue.

**Comment by AleeeKoi** [comment]
ok, can you explain what you have reverted?

In my case, I'm starting a new expo project and simply installing react navigation (following the official guide).
I can see that simply importing `import { createStackNavigator } from '@react-navigation/stack';` in my navigation file generate the error.

**Comment by karimcambridge** [comment]
Oh wow.

I'm not sure

I was on expo sdk 37 so I just reverted my package.json and ran npm install

**Comment by AleeeKoi** [comment]
Well, downgrading to sdk 37 make it works.
I will wait with you for a solution.

**Comment by chrisscott** [comment]
I'm seeing this with `react-navigation` and Expo SDK 38 as well. For some reason Expo has this lib (and no others) in it's `node_modules`. As a workaround to get my project working, I removed it from there. Not sure where the fault lies though.

**Comment by sam17896** [comment]
Getting the same issue, you guys found any solution yet.. may be we need to open this issue on expo repo.. also if downgrading to sdk 37 works, then please tell me whats the latest version of sdk 37 as expo's github release history is confusing.

**Comment by chrisscott** [comment]
It looks like Expo 38.0.8 [fixed this](https://github.com/expo/expo/issues/9042). Targeting that version in my project and doing an `npm install` resolved this.

**Comment by sam17896** [comment]
> It looks like Expo 38.0.8 [fixed this](https://github.com/expo/expo/issues/9042). Targeting that version in my project and doing an `npm install` resolved this.

Unfortunately not for me I'll dig more tonight.

**Comment by ikakara** [comment]
I created a sample app that demonstrates the issues: https://github.com/ikakara/expo-sdk38-bug

**Comment by conrad-vanl** [comment]
I can confirm that we're experiencing this issue on a non-expo app (`react-native init` app). We ran into it while attempting to upgrade to `react-navigation` v5. We also upgraded `react-native-safe-area-context` at the same time. I do not have a good lead yet on the cause from our end...it looks like it could be coming from the `@react-navigation/compat` package but i'm not very certain on that yet.

**Comment by henrypigg** [comment]
@conrad-vanl I had the same issue and it was a problem with react-navigation. I fixed it by updating react-navigation-stack to 2.8.2 and react-navigation-tabs to 2.9.0.

**Comment by jasonserafino** [comment]
Removing react-native-safe-area-context from expo.dependencies in package-lock and running npm install fixed this for me.  Expo and react-navigation 5.

**Comment by neiker** [comment]
> It looks like Expo 38.0.8 [fixed this](https://github.com/expo/expo/issues/9042). Targeting that version in my project and doing an `npm install` resolved this.

This solves the issue for me. I also removed expo app from simulator and let it install again

**Comment by HristoEftimov** [comment]
It works on ver.3.0.7, with SDK38 + React Navigation 5.

Upgrading to ver.3.1.1 breaks the app :/

**Comment by iNeedHookah** [comment]
For me the following worked: 

- Delete `react-native-safe-area-contex` from `package.json`

- Removed node modules `rm -rf node_modules`

- Run `npm install`

**Comment by pastordougdev** [comment]
I just started a new project on SDK 38 (38.0.8).  Installed safe-area-context version 3.0.7 and it still breaks.

**Comment by Decoder3-14** [comment]
@pastordougdev did you solve it? I have tried numerous ways but still same error!

**Comment by Decoder3-14** [comment]
Alright, I have finally solved this problem the following way:

1.  Go to expo's own node_modules, remove the _react-native-safe-area-context_ from there
2. Remove react-native-safe-area-context from package.json for expo's folder in node_modules
3. Run again using expo r -c.

**Comment by dominik992** [comment]
For now, I added this inside "scripts" in my package.json `"postinstall":"rm -rf node_modules/expo/node_modules/react-native-safe-area-context",`

It's an ugly fix but does the job.

**Comment by brentvatne** [comment]
@pastordougdev - can you provide a reproducible example?

i just did this and it worked as expected:

```
╭─~/code
╰─$ expo init testingit
? Choose a template: expo-template-blank

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Downloaded and extracted project files.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd testingit
- yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- yarn android
- yarn ios
- yarn web
╭─~/code
╰─$ cd testingit
╭─~/code/testingit ‹master›
╰─$ expo install react-native-safe-area-context
Installing 1 SDK 38.0.0 compatible native module using Yarn.
> yarn add react-native-safe-area-context@~3.0.7
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 0 new dependencies.
✨  Done in 2.67s.
```

the key things here:
- expo package is `expo@38.0.8`
- install react-native-safe-area-context with `expo install react-native-safe-area-context`

**Comment by EmbeddedProg** [comment]
expo version 38.0.9 solved the problem.

**Comment by pkj-ind** [comment]
Below worked for me:

Removing package-lock,json and node_module
delete entry of "react-native-safe-area-view": "^1.1.1" from package.json
run "npm install"

Post that i was not getting this error while launching app on ios device.

**Comment by TagIt34** [comment]
> Below worked for me:
> 
> Removing package-lock,json and node_module
> delete entry of "react-native-safe-area-view": "^1.1.1" from package.json
> run "npm install"
> 

tried the same, but does not work.
But I also cannot see version 38.0.8. It is only showing me 38.0.0
And if I then try to "install expo-secure-store"
I am getting a new error:

"action persist/PERSIST"
which simply stays on my terminal window while the expo app on the iPhone crashes

Anyone could help please?

**Comment by iNorthSea** [comment]
> @pastordougdev - can you provide a reproducible example?
> 
> i just did this and it worked as expected:
> 
> ```
> ╭─~/code
> ╰─$ expo init testingit
> ? Choose a template: expo-template-blank
> 
> 🧶 Using Yarn to install packages. You can pass --npm to use npm instead.
> 
> ✔ Downloaded and extracted project files.
> ✔ Installed JavaScript dependencies.
> 
> ✅ Your project is ready!
> 
> To run your project, navigate to the directory and run one of the following yarn commands.
> 
> - cd testingit
> - yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
> - yarn android
> - yarn ios
> - yarn web
> ╭─~/code
> ╰─$ cd testingit
> ╭─~/code/testingit ‹master›
> ╰─$ expo install react-native-safe-area-context
> Installing 1 SDK 38.0.0 compatible native module using Yarn.
> > yarn add react-native-safe-area-context@~3.0.7
> yarn add v1.22.4
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> [4/4] 🔨  Building fresh packages...
> success Saved 0 new dependencies.
> ✨  Done in 2.67s.
> ```
> 
> the key things here:
> 
> * expo package is `expo@38.0.8`
> * install react-native-safe-area-context with `expo install react-native-safe-area-context`
> 
> ## still having this problem?
> * delete node_modules and your lockfile (package-lock.json / yarn.lock)
> * change the `expo` package version in package.json to 38.0.8
> * remove `react-native-safe-area-context` from your package.json
> * run yarn or npm install
> * run `expo install react-native-safe-area-context`

Nice, Guy~

**Comment by brentvatne** [comment]
## still having this problem?

- delete node_modules and your lockfile (package-lock.json / yarn.lock)
- change the `expo` package version in package.json to 38.0.8
- remove `react-native-safe-area-context` from your package.json
- run yarn or npm install
- run `expo install react-native-safe-area-context`
