### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager

### ISSUE THREAD

**Issue by krakzk** [th3rdwave/react-native-safe-area-context#113]
Updated my existing project from RN 0.59.3 to 0.62.2.
In the process updated react-native-safe-area-view to 0.14 also react-native-safe-area-context.
I'm not running on expo.
Could anyone help?

**Comment by krakzk** [comment]
Issue resolved by manually linking the dafe area context. Autolinking was unsuccessful

**Comment by Desintegrator** [comment]
is there any instructions for manual linking for android?
