### ISSUE TITLE
useSafeAreaInsets doesn't work in class component

### ISSUE THREAD

**Issue by tufik2** [th3rdwave/react-native-safe-area-context#116]
How can I use useSafeAreaInsets in a class component

When I try to use this method I have this error

`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
`

**Comment by satya164** [comment]
```js
class MyComponent extends React.Component {
  render() {
    // Get it from props
    const { insets } = this.props;
  }
}

// Wrap and export
export default function(props) {
  const insets = useSafeAreaInsets();

  return <MyComponent {...props} insets={insets} />;
}
```

**Comment by Ivanov89** [comment]
Same issue here and the `insets` data is `undefined` ?

**Comment by tufik2** [comment]
I don't know why this issue was closed with a hack solution, will be good to give support too class Component too.

**Comment by AKclown** [comment]
hey , In class components you should use SafeAreaInsetsContext instead of useSafeAreaInsets. useSafeAreaInsets is used in hooks

> I don't know why this issue was closed with a hack solution, will be good to give support too class Component too.
