### ISSUE TITLE
Autolinking not finding podspec in monorepo

### ISSUE THREAD

**Issue by jpaas** [th3rdwave/react-native-safe-area-context#12]
When I `pod install` using RN 0.61.1 the podspec for this module doesn't get picked up for some reason. I have a number of other native node modules which work fine, but for some reason its not seeing this one.

If I add the pod manually to my `Podfile` it works fine.

Anybody else seeing this?

**Comment by jpaas** [comment]
So it seems its not working in my monorepo project. I tried it in a clean, normal RN project and it works fine.

My monorepo puts the RN project in a subdirectory and uses yarn workspaces to install `node_modules` in the root of the repo. 

We use quite a few native modules such as `react-native-image-picker`, `react-native-maps`, `react-native-video` to name a few. All of the others work with autolinking, but not this one.

**Comment by gabrielbull** [comment]
Just to add to this. I am also using a monorepo but I do not have the issue shared by @jpaas. Maybe if you could share a stripped down version of your monorepo it would help understand why?

**Comment by jpaas** [comment]
Ah ok thanks for the feedback @gabrielbull . Ya I'll see if I can put a repro together.

**Comment by janicduplessis** [comment]
I'm not using autolinking in my project so I'm not sure if it works. Maybe someone can try to figure out the difference between our podfile (https://github.com/th3rdwave/react-native-safe-area-context/blob/master/react-native-safe-area-context.podspec) and one that works.

**Comment by jpaas** [comment]
This problem seems to have resolved itself for me. Perhaps when I upgraded to RN 0.61.2?

**Comment by naderghanbari** [comment]
Does that mean autolinking works for this library? There is mo mention of autolinking in the docs.
