### ISSUE TITLE
Support for react-native-macos?

### ISSUE THREAD

**Issue by 0xmtn** [th3rdwave/react-native-safe-area-context#120]
Is there any future plans for releasing a version with[ react-native-macos](https://github.com/microsoft/react-native-macos/issues/488) support?

**Comment by janicduplessis** [comment]
I released 3.1.0 with basic support for mac and windows. However it requires a recent commit in rn-cli to work properly with autolinking https://github.com/react-native-community/cli/commit/0a93be1a42ed1fb05bb0ebf3b82d58b2dd920614.

Tested by patching https://github.com/react-native-community/cli/blob/0a93be1a42ed1fb05bb0ebf3b82d58b2dd920614/packages/platform-ios/native_modules.rb
