### ISSUE TITLE
Using react-native-safe-area-context and react-native-admob's PublisherAdView doesn't trigger OMID tracking [Android]

### ISSUE THREAD

**Issue by andresesfm** [th3rdwave/react-native-safe-area-context#121]
Hello, this is kind of a strange issue, and I was hoping to get some pointer so I can continue to debug this. 

Preface:
Admob's PublisherAdView's tracking works as expected if using it on a fully native app, It also tracks correctly in the following situation: 
```
<SafeAreaProvider>
        <SafeAreaView>
          <View>
            <PublisherBanner
              adSize="banner"
              adUnitID="unitId"
              customTargeting={{
                deviceType: "phone",
                slot: "banner1",
                title: "landing",
                test: "on",
              }}
            />
          </View>
        </SafeAreaView>
      </SafeAreaProvider>
```
as long as I change this https://github.com/th3rdwave/react-native-safe-area-context/blob/master/src/SafeAreaContext.tsx#L73-L86 as follows: 
```
  return (
    <NativeSafeAreaProvider
      style={[>>>>styles.fill, REMOVE THIS STYLE<<<<< style]}
      onInsetsChange={onInsetsChange}
    >
      {insets != null ? (<<<<<< REMOVE THIS LINE
        <SafeAreaFrameContext.Provider value={frame}>
          <SafeAreaInsetsContext.Provider value={insets}>
            {children}
          </SafeAreaInsetsContext.Provider>
        </SafeAreaFrameContext.Provider>
      ) : null} <<<<<<REMOVE THIS LINE
    </NativeSafeAreaProvider>
  );
```
I.e: remove the fill style and the checks for null insets

The problem:
This, however, is not a real solution because as soon as I try to add any RN Navigation, the screen is simply blank 

I have tried on the latest RN .63, react-native-safe-context-area 3.0.7

Any pointers on this would be appreciated

**Comment by andresesfm** [comment]
I have also created https://stackoverflow.com/questions/62855865/using-react-native-safe-area-context-and-react-native-admobs-publisheradview-do if you dim it a more appropriate forum for this kind of questions

**Comment by janicduplessis** [comment]
Would you be able to put the PublishedBanner component outside of SafeAreaProvider to workaround the issue? Like:

```
<>
            <PublisherBanner
              adSize="banner"
              adUnitID="unitId"
              customTargeting={{
                deviceType: "phone",
                slot: "banner1",
                title: "landing",
                test: "on",
              }}
            />
<SafeAreaProvider>
        <SafeAreaView>
          <View>
                ...
          </View>
        </SafeAreaView>
      </SafeAreaProvider>
</>
```
