### ISSUE TITLE
False notch auto detect on "hideable" android menu. Bottom tab bar has like double size in height with react-navigation

### ISSUE THREAD

**Issue by Meinl** [th3rdwave/react-native-safe-area-context#122]
Hi, I've installed last versions of react-navigation and react-native-safe-area-context, and we have an issue with Android bottom navigator. This behavior is occurring, at least on my phone (Asus Zenfone 5), and pretty sure in other that have that choice. In previous versions worked fine, that's mean, the bottom tab navigator goes up and down whit Android's navigation bar, isn't static like now with double height. I'm attaching a gif, the code is exactly the same and was taken of example of react navigation tabs (copy paste) from here: https://reactnavigation.org/docs/bottom-tab-navigator last snack example link. I've opened an issue days ago in react-navigation, but they told me that I have to open an issue here.

Thanks in advance.

![86949485-b483c100-c11c-11ea-9ccf-08294225a04d](https://user-images.githubusercontent.com/8104557/87320234-b07ae900-c4f8-11ea-961f-a4acb3c525c4.gif)

**Comment by thetminko** [comment]
I am having the same issue with Samsung S8

**Comment by CDBridger** [comment]
Same issue

**Comment by CDBridger** [comment]
changing from getSystemWindowInsetBottom to getStableInsetBottom seems to have been the problem which was applied between version 1.0.3 and 2.0.0 in the SafeAreaUtils.java

**Comment by Meinl** [comment]
Any news? Can't make it work. Thanks again.

**Comment by CDBridger** [comment]
@Meinl you can use my fork in the meantime if you want. I reverted it back to using getSystemWindowInsetBottom which seemed to do the trick.

https://github.com/CDBridger/react-native-safe-area-context

**Comment by janicduplessis** [comment]
Interesting, I changed to `getStableInsetBottom` because `getSystemWindowInsetBottom` would change when the soft keyboard opens, which we don't want to match the iOS behavior. I didn't some android devices hide the navbar like this. I can probably use `Math.min(getSystemWindowInsetBottom(), getStableInsetBottom())` instead.

**Comment by janicduplessis** [comment]
Could you check if version 3.1.6 fixes the issue?

**Comment by Meinl** [comment]
> Could you check if version 3.1.6 fixes the issue?

I've updated to ^3.1.6 but not work. I assume because I'm using expo and I've checked expo dependencies in yarn.lock file and it's using ~3.0.7 version. I don't how to test it, can you help me? Thanks.

**Comment by janicduplessis** [comment]
The fix is in native code so sadly it won't work until expo updates this dependency. I think you'd have to eject to be able to update now.

**Comment by janweigel** [comment]
Same Problem here even after updating to 3.1.7 on an ejected project (not expo).
Even if android navigation is hidden, the bottom insets are applied.

**Comment by Jalson1982** [comment]
@janicduplessis it does not work.

**Comment by bogdanciobanu** [comment]
Any updates on this issue? Is there a fix expected in the foreseeable future?
Does anybody know if it affects other devices? I've noticed it on a Samsung S8 too.

**Comment by jacobp100** [comment]
This is for v3 of the library, and we're on v4. Please re-open a new issue if you're still facing issues
