### ISSUE TITLE
Unable to resolve module NativeSafeAreaView

### ISSUE THREAD

**Issue by anthowm** [th3rdwave/react-native-safe-area-context#126]
Today I update to last version 3.1.1 and got this issue in both platforms. I tried manual linking and not working. Finally check that in node_modules missing this module
<img width="354" alt="Screenshot 2020-07-21 at 10 29 15" src="https://user-images.githubusercontent.com/5764698/88031775-5c49b780-cb3d-11ea-8554-45316f86a469.png">

**Comment by mattdamon108** [comment]
I have exactly the same issue.

**Comment by paulg0614** [comment]
Same here

**Comment by woltsu** [comment]
`npm start -- --reset-cache` fixed it for me

**Comment by steveZak** [comment]
Still getting this issue, the fix above didn't work for me...

**Comment by wmonecke** [comment]
God this issue made me lose a whole day! Any ideas?

**Comment by wmonecke** [comment]
@janicduplessis

**Comment by wmonecke** [comment]
Current solution:

1) Go to `node_modules/react-native-safe-area-context/src/index.tsx`

2) Add this `export` statement: `export * from './NativeSafeAreaProvider'`

3) `npm start --reset-cache`

4) Keep working.

**Comment by janicduplessis** [comment]
This file doesn't exist anymore (https://github.com/th3rdwave/react-native-safe-area-context/tree/master/src). Would it be possible that you have multiple versions of the library installed? Also you can check what version is actually installed by checking the package.json file "version".

**Comment by comvenger-brandon** [comment]
Having the same problem and I'm sure I'm using the latest react-native-safe-area-context version.

**Comment by walosha** [comment]
I was using expo and this woked for me 

`expo start -c`

**Comment by florian-milky** [comment]
```npm start -- --reset-cache``` was enough for me

**Comment by FanchenBao** [comment]
Using `3.2.0` and `npm start -- --reset-cache` works for me.

**Comment by ghasemikasra39** [comment]
Using `3.3.2` and `npm start -- --reset-cache` also worked for me

**Comment by karim-belhadjali** [comment]
> Current solution:
> 
> 1. Go to `node_modules/react-native-safe-area-context/src/index.tsx`
> 2. Add this `export` statement: `export * from './NativeSafeAreaProvider'`
> 3. `npm start --reset-cache`
> 4. Keep working.

Thank you for this , it did work for me

**Comment by jacobp100** [comment]
This is for v3 of the library, and we're on v4. Please re-open a new issue if you're still facing issues
