### ISSUE TITLE
Is there a straight way of changing the safe area view background color for a couple of screens only?

### ISSUE THREAD

**Issue by federicomiralles** [th3rdwave/react-native-safe-area-context#131]
I'm working on an app where all the screens but 2 have different safe area view background color.
At the moment the SafeAreaView component is wrapping them at app level (i.e.: <SafeAreaView>...screens</SafeAreaView> inside App.js).
Moving the SafeAreaView to each screen (~40) as proposed by [React Navigation](https://reactnavigation.org/docs/handling-safe-area/#summary):

![Untitled](https://user-images.githubusercontent.com/53195495/88547175-bc37d680-cff3-11ea-8635-eb6c3d150cdb.png)

because of a couple doesn't sound quite right...

Is there any other better way of achieving this?

Thanks in advance!

Regards,

Federico

**Comment by janicduplessis** [comment]
This is more related to react-navigation, but yes you would need to wrap each screen with its own SafeAreaView. You can make an abstraction for it to make it easier where you define your routes. Another possibility is use react-navigation cardStyle (or something like that) to override the background color just for certain screens.
