### ISSUE TITLE
Problems with SSR Next.js

### ISSUE THREAD

**Issue by RichardLindhout** [th3rdwave/react-native-safe-area-context#132]
When I wrap my app with a SafeAreaProvider in Next.js (I have a cross platform app with React Native Web + Next.js) SSR does not work.

I've workaround this with
```jsx
export default function isServer() {
  return !!(
    typeof process !== "undefined" &&
    process.release &&
    process.release.name === "node"
  );
}

 const DummyProvider = ({ children }) => children;

    const SafeProviderWithSSR = isServer() ? DummyProvider : SafeAreaProvider;
 <SafeProviderWithSSR>
</SafeProviderWithSSR>
```

Update: does not work too because I got errors
```
Error: No safe area insets value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app.

```

**Comment by satya164** [comment]
Instead of rendering a noop component, you need to provide the `initialMetrics` prop with initial values (`0` for everything) to the `SafeAreaProvider`. Even if there was no such error, rendering different things on client and server will lead to mismatch of the DOM and not recommended.

**Comment by RichardLindhout** [comment]
Thanks a lot, it works!

**Comment by petrbela** [comment]
I just realized I've had this wrong all along. Perhaps the [Optimization](https://github.com/th3rdwave/react-native-safe-area-context#optimization) section should not show an example that sets `initialMetrics={initialWindowMetrics}` when in fact `initialWindowMetrics` is `null`, and thus defeats the purpose.

Is the intention that the `initialWindowMetrics` are passed as the default optimization mechanism? If so, I think https://github.com/th3rdwave/react-native-safe-area-context/blob/master/src/InitialWindow.ts should be changed to

```
export const initialWindowMetrics: Metrics | null = {
  frame: { x: 0, y: 0, width: 0, height: 0 },
  insets: { top: 0, left: 0, right: 0, bottom: 0 },
};
```

The way the Optimization section is worded right now makes it sound like it's already handled, when in fact it's the developer's responsibility to pass the `0`ed object.
