### ISSUE TITLE
react-native-safe-area-context is only RN 0.61 or better?

### ISSUE THREAD

**Issue by TomSwift** [th3rdwave/react-native-safe-area-context#133]
Are there docs on what versions of RN this library supports?  

This usage of `useWindowDimensions` suggests at least RN 0.61 is required, yes?

https://github.com/th3rdwave/react-native-safe-area-context/blob/b1824ef84d78a44e91cd156a29abe3da243eee94/src/CompatNativeSafeAreaProvider.tsx#L10

I think there should be explicit documentation to identify compatibility.

**Comment by janicduplessis** [comment]
True, I did not think about that when using this hook. If someone is interested to submit a PR to add a copy of the `useWindowDimensions` hook to this repo and use this instead of the one added in RN 0.61 that would be great.

**Comment by janicduplessis** [comment]
Fixed in v3.1.7
