### ISSUE TITLE
SafeArea.types.ts: Unexpected token, expected ";"

### ISSUE THREAD

**Issue by feliperaul** [th3rdwave/react-native-safe-area-context#134]
I'm trying to start an Expo app just upgraded to SDK 38 and I'm getting this error:

Failed building JavaScript bundle.
SyntaxError: /Users/dev/react-native-typography/example/node_modules/react-native-safe-area-context/src/SafeArea.types.ts: Unexpected token, expected ";" (42:19)

  40 |   children?: React.ReactNode;
  41 |   mode?: 'padding' | 'margin';
> 42 |   edges?: readonly Edge[];
     |                    ^
  43 | };
  44 |

**Comment by elie222** [comment]
Seeing the same issue. Expo 38 is relying on an older version of this package.

**Comment by janicduplessis** [comment]
hmm maybe certain versions of typescript has issues parsing this syntax, I updated to use something different it should fix it.

**Comment by byCedric** [comment]
This one might be related to Babel's typescript conversion, e.g. [this issue](https://github.com/babel/babel/issues/9502) or [this one](https://github.com/babel/babel/issues/9567). If someone is able to reproduce it, could you try upgrading babel?

**Comment by poonsakn** [comment]
> This one might be related to Babel's typescript conversion, e.g. [this issue](https://github.com/babel/babel/issues/9502) or [this one](https://github.com/babel/babel/issues/9567). If someone is able to reproduce it, could you try upgrading babel?

I upgraded babel from 7.2.2 to 7.11.1 and it solved the problem. Thanks!

**Comment by janicduplessis** [comment]
Awesome, I'll close as this seems to be resolved. I also removed the problematic syntax in the latest update to make sure it doesn't happen even on older babel versions.
