### ISSUE TITLE
Should this work with react-native-windows? I'm getting the error 'requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager'

### ISSUE THREAD

**Issue by joshglenn** [th3rdwave/react-native-safe-area-context#137]
I'm using react-native-windows and trying to integrate an existing react-native project with react-native-windows. I get the following error:

```
requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager
```

Has this module been used / tested at all with react-native-windows?

**Comment by janicduplessis** [comment]
Oh I see, I forgot to add something for the SaveAreaView component for windows / macos. I will fix it.

**Comment by janicduplessis** [comment]
@joshglenn could you try 3.1.3, it should fix the issue!

**Comment by joshglenn** [comment]
I believe it did. I still cannot use my project which uses react-navigation, because the dependency `react-native-gesture-handler` is not compatible with react-native-windows at the moment. I'm trying to find a workaround. Thanks for your help!
