### ISSUE TITLE
Height and insets not updated when Android softkeyboard opens

### ISSUE THREAD

**Issue by janweigel** [th3rdwave/react-native-safe-area-context#138]
Hi everyone,
I have a problem on Android when the soft keyboard opens.
The height and the indents are not changing when the softkeyboard opens.

I'm using react-native-safe-area-context version 3.1.3 and have set android:windowSoftInputMode="adjustResize"
I was using version 0.7.3 before and everything worked, but after updating to 3.1.3 I can't get the SafeAreaView or the insets of the SafeAreaProvider to update when the soft keyboard appears.
Therefore the input fields are always covered by the keyboard and both a ScrollView or KeyboardAvoidingView don't scroll to make the inputs visible.

I'm using compileSdkVersion and targetSdkVersion 30

Any help appreciated.
Thanks

**Comment by nivas412** [comment]
Having the same issue

**Comment by janicduplessis** [comment]
Hi @janweigel, this is actually by design to match the behavior of iOS where the soft keyboard is not considered as an inset. To manage keyboard layout I recommend using KeyboardAvoidingView or https://www.npmjs.com/package/react-native-keyboard-avoiding-scroll-view.

**Comment by janicduplessis** [comment]
For immersive mode there is an open issue about it https://github.com/th3rdwave/react-native-safe-area-context/issues/63, do you know if it works correctly without immersive mode on Galaxy Alpha with Android 5.0.2?

**Comment by janweigel** [comment]
Hi @janicduplessis, 
The keyboard height is also added on Android 5.0.2 if I don't set it to immersive sticky.

For the other issue: the workaround with LAYOUT_FLAG_NO_LIMITS as suggested here #63 doesn't work for me, as the correct insets for display cutouts are not detected if LAYOUT_FLAG_NO_LIMITS is applied. It should be possible to use immersive sticky mode without LAYOUT_FLAG_NO_LIMITS, as this flag introduces some other unwanted behavior and shouldn't be neccessary for immersive sticky mode.

I was hoping that the latest update to v3.1.6 would detect the bottom insets correctly when using immersive sticky mode but the bottom inset is still applied even if the navbar is hidden. The expected behavior would be a bottom inset of 0 in immersive sticky mode.

**Comment by janicduplessis** [comment]
Thanks for the clarification, I'll try to find some time to look at it this week.

**Comment by janweigel** [comment]
Hi @janicduplessis,
did you already have time to take a look on this?
If you need more detailed information about the problem or suggestions how to fix it, let me know.
Thanks
