### ISSUE TITLE
how to disable bottom safe area in some pages

### ISSUE THREAD

**Issue by TheEhsanSarshar** [th3rdwave/react-native-safe-area-context#142]
I have some pages with react navigation 5. I need to disable bottom safeArea in some pages. how can I achieve that ? in pages that have bottom tab bar I need safeArea but in pages that don't have I need to disable it.

**Comment by ajaykumar97** [comment]
It could be helpful:

https://github.com/th3rdwave/react-native-safe-area-context/issues/107#issuecomment-652616230

**Comment by MkNiloufar** [comment]
any solution?

**Comment by MkNiloufar** [comment]
Found the solution. You can wrap your specific page inside Modal and it ignores the safe area

**Comment by jacobp100** [comment]
We support the `edges` prop. If the library you're using doesn't, open an issue with them
