### ISSUE TITLE
Any Solution

### ISSUE THREAD

**Issue by Shekhar7860** [th3rdwave/react-native-safe-area-context#145]
This error is located at:
    in n
    in A
    in RNCSafeAreaProvider
    in Unknown
    in b
    in c
    in L
    in RCTView
    in RCTView
    in c', reason: 'Unhandled JS Exception: TypeError: null is not an object (evaluating 'l.initBuilder')

**Comment by ajaykumar97** [comment]
Hey @Shekhar7860 I am also getting this issue via Firebase Crashlytics. Have you found any solution to it?

**Comment by Shekhar7860** [comment]
hello @ajaykumar97 sorry, i didnt found the exact solution, i compiled project on different system with higher Xcode version and it worked fine there

**Comment by Desintegrator** [comment]
same in Android

**Comment by jacobp100** [comment]
The error is in your `n` component - not here
