### ISSUE TITLE
Build Failing in iOS, 'sharedApplication' is unavailable

### ISSUE THREAD

**Issue by rohitkum28** [th3rdwave/react-native-safe-area-context#151]
I am unable to build my react-native app in iOS because I am getting the following error in `RNCSafeAreaProviderManager.m`

    'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Environment**
react-native:0.63.3
react-native-safe-area-context: 3.1.7
ios: 14
Xcode - 12

Any help will be appreciated.

**Comment by halilbilen** [comment]
+1 

what is the solution?

**Comment by chrisarts** [comment]
+1
same here, any solution ?

**Comment by ignacioiglesias43** [comment]
> I am unable to build my react-native app in iOS because I am getting the following error in `RNCSafeAreaProviderManager.m`
> 
> ```
> 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
> ```
> 
> **Environment**
> react-native:0.63.3
> react-native-safe-area-context: 3.1.7
> ios: 14
> Xcode - 12
> 
> Any help will be appreciated.

same here, any solution ?

**Comment by ignacioiglesias43** [comment]
same here, any solution ?

**Comment by p-gag** [comment]
I installed the react-native-safe-area-view package as specified in the Readme and it went away. 

Unless it was just the pod install but putting it here in case it help someone.

**Comment by janicduplessis** [comment]
Should be fixed in 3.4.0 (https://github.com/th3rdwave/react-native-safe-area-context/commit/d5fab0b5d3e06d066ed288d68f7385e72ea67ad8)
