### ISSUE TITLE
iPhone 12: no safe area insets

### ISSUE THREAD

**Issue by Strate** [th3rdwave/react-native-safe-area-context#154]
On the left side is iPhone 12 Pro Max simulator, on the right side iPhone 11 Pro Max Simulator
![image](https://user-images.githubusercontent.com/392644/96875823-5b982880-1480-11eb-9981-bb364946cfc7.png)

**Comment by Strate** [comment]
Sorry, my issue is unrelated with your awesome library.

**Comment by Vednus** [comment]
@Strate how'd you end up fixing this. running into the same problem

**Comment by Vednus** [comment]
nvm. I needed to upgrade `react-native-device-info`

**Comment by MaxToyberman** [comment]
for me upgrading react-navigation-tabs to 2.10.1 solved the issue

**Comment by nabilfreeman** [comment]
Thank you! Device info upgrade was needed for me.

**Comment by trunglemobiledev** [comment]
> for me upgrading `react-navigation-tabs` to `2.10.1` solved the issue

Thanks! fixed
