### ISSUE TITLE
Keyboard affects bottomInset on Android 5 with android:windowTranslucentNavigation=true

### ISSUE THREAD

**Issue by Ashoat** [th3rdwave/react-native-safe-area-context#155]
I have an app with `android:windowTranslucentNavigation` enabled, which makes it so Android doesn't resize the window for the soft keyboard. `react-native-safe-area-context` handles this well for most versions of Android, but for API levels below 23 it updates the `bottomInset` whenever the soft keyboard appears.

**Comment by jacobp100** [comment]
Android has a bunch of xml configs for this stuff. I know it's not documented here (PRs would be really apprecianted) - but you do have to configure them
