### ISSUE TITLE
Does SafeAreaView support android? 

### ISSUE THREAD

**Issue by VictorioMolina** [th3rdwave/react-native-safe-area-context#156]
I am testing SafeAreaView but this seems not to work on Android.

My app has a minimalistic design and I have hidden the status bar... So, that is why I wrapped most of my components inside your component... The problem is that I have had to write an extra padding for Android like this:

import React from "react";
import { StyleSheet, Platform, StatusBar } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

```
export default function (props) {
  return (
    <SafeAreaView style={styles.AndroidSafeArea} {...props}>
      {props.children}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  AndroidSafeArea: {
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
});

```

Something that doesn't seems really elegant. 

Will this feature be implemented in a future so that I don't have to use this custom component?

Thank you.

**Comment by kuasha420** [comment]
It works on android for sure. Are you sure you haven't imported SafeAreaView from 'react-native' ?

**Comment by VictorioMolina** [comment]
Yeah! I am using the one from react-native-safe-area-context. The thing is, that if I don't apply the paddingTop: StatusBar.currentHeight on android, my [Samsung Galaxy S20 camera ](https://images-na.ssl-images-amazon.com/images/I/61W7GElaqaL._AC_SX679_.jpg) covers the header of screen.

**Comment by nickelbob** [comment]
@VictorioMolina were you able to solve this? I'm dealing with a similar problem on the Pixel 4A.

**Comment by VictorioMolina** [comment]
@nickelbob nope, I didn't :/

**Comment by wuzhipei** [comment]
`import React from 'react';
import {
  SafeAreaView,
  NativeSafeAreaViewProps,
  useSafeAreaInsets,
  EdgeInsets,
  Edge,
} from 'react-native-safe-area-context';
import styled, { css } from 'styled-components';

const SafeAreaViewStyled = styled(SafeAreaView)<{
  insets: EdgeInsets;
  edges: readonly Edge[];
  mode: 'padding' | 'margin';
}>`
  flex: 1;
  ${(p) =>
    p.edges.map(
      (direction) => css`
        ${p.mode}-${direction}: ${p.insets[direction]}px;
      `,
    )}
  background: #fff;
`;

export const CustomSafeAreaView: React.FC<NativeSafeAreaViewProps> = ({
  children,
  edges = ['top', 'right', 'bottom', 'left'],
  ...restProps
}) => {
  const insets = useSafeAreaInsets();

  return (
    <SafeAreaViewStyled edges={edges} insets={insets} mode="padding" {...restProps}>
      {children}
    </SafeAreaViewStyled>
  );
};
`

**Comment by jacobp100** [comment]
It supports Android

**Comment by rdougan** [comment]
I had a similar issue when running on Android. If I add the `flex` prop, it would crash android completely, without any obvious error:

`<SafeAreaView flex>`

But using the `style` property works:

`<SafeAreaView style={{flex: 1}}>`

I would assume that it is due to some kind of property type validation.
