### ISSUE TITLE
[QUESTION🤔] using with react-native-community/safe-area-view

### ISSUE THREAD

**Issue by usrbowe** [th3rdwave/react-native-safe-area-context#16]
# Question

So, with recent release [0.4.1](https://github.com/th3rdwave/react-native-safe-area-context/releases/tag/v0.4.1)
As noted here: https://github.com/react-native-community/react-native-safe-area-view#usage, it uses `Context` from this repo, but last release introduce it's own `SafeAreaView` component. 
So I can assume we no longer need the community one?

---

So the difference is that `SafeAreaView` from here just adds insets to `padding`, and doesn't support `forceInset`.

- `forceInset` - can be achieved by overriding `paddingLeft/Right/Top/Bottom` via `style` prop.

Overall this `SafeAreaView` is good starting point, before plugin-in more complex `SafeAreaVie` from https://github.com/react-native-community/react-native-safe-area-view/

**Comment by janicduplessis** [comment]
The one in this repo is very simple and basically only adds padding, you can achieve a similar effect as force insets by overriding paddings in styles (`<SafeAreaView style={{paddingTop: 0}} />`). One thing the  react-native-safe-area-view does that the one here does not is measure itself in the window to try to figure out the intersection between screen insets and the view position, so if you need this behaviour I suggest using that instead.
