### ISSUE TITLE
SafeAreaView from react-native vs SafeAreaView from this lib

### ISSUE THREAD

**Issue by mohsinulhaq** [th3rdwave/react-native-safe-area-context#160]
What's the difference between the two. If a safe area container is all I need and I don't care about the inset values, can the `SafeAreaView` from this lib be safely replaced by the `SafeAreaView` from RN without losing any features?

**Comment by NS-BOBBY-C** [comment]
I don't know the specifics of the actual implementation, but I've used both in a project and I've had significantly worse rendering with the React Native version. I find that this component renders with less clunkiness and components snapping into place.

That being said, try both in your project and see which renders in the Release variant. What worked for us might not work for everyone!

**Comment by Megatron4537** [comment]
This lib provides hooks to measure the insets/edges and dynamically choose to or not render over those insets. So it's more flexible. see doc https://github.com/th3rdwave/react-native-safe-area-context#usesafeareainsets
