### ISSUE TITLE
Type 'string' is not assignable to type 'Edge'

### ISSUE THREAD

**Issue by Viet27th** [th3rdwave/react-native-safe-area-context#163]
It's not a bug.
I want to disallow "edges" top if "hideTopEdge" condition is true but get a typescript error message "Type 'string' is not assignable to type 'Edge'."  What do I have to do now?
![image](https://user-images.githubusercontent.com/30460839/102128570-0a595380-3e89-11eb-886c-69423fedd52f.png)

`
```
import React from "react";
import Styles from "./style";
import { SafeAreaView } from "react-native-safe-area-context";

type Props = typeof SafeArea.defaultProps & {
  // children: JSX.Element;
  hideTopEdge: boolean;
  hideBottomEdge: boolean;
};

type State = {
  count: Nullable<number>;
};

class SafeArea extends React.Component<Props, State> {
  static defaultProps = {
    hideTopEdge: false,
    hideBottomEdge: false,
  };
  constructor(props: Props) {
    super(props);
  }

  render() {
    const { children, hideTopEdge, hideBottomEdge } = this.props;

    return (
      <SafeAreaView
        edges={[
          "right",
          "left",
          ...(hideTopEdge ? [] : ["top"]),
          ...(hideBottomEdge ? [] : ["bottom"]),
        ]}>
        {children}
      </SafeAreaView>
    );
  }
}

export default SafeArea;
```
`

**Comment by kdbcinco** [comment]
`["top"]` and `["bottom"]` are probably being inferred as `string[]` here. You can work around this in a few ways:

```
// 1) create typed constants
const EDGE_TOP: Edge = 'top';
const EDGE_BOTTOM: Edge = 'bottom';

// and use it like so
...(hideTopEdge ? [] : [EDGE_TOP]),
...(hideBottomEdge ? [] : [EDGE_BOTTOM]),

// 2) or, you can use `as` to specify the type explicitly
...((hideTopEdge ? [] : ["top"]) as Edge[]),
...((hideBottomEdge ? [] : ["bottom"]) as Edge[]),

// 3) you can also build the value for the `edges` prop using useMemo
const edges = useMemo<Edge[]>(() => {
  const edges = ['right', left'];

  if (!hideTopEdge) {
    edges.push('top');
  }

  if (!hideBottomEdge) {
    edges.push('bottom');
  }

  return edges;
}, [hideTopEdge, hideBottomEdge]);

<SafeAreaView
  // ...other props
  edges={edges}
></SafeAreaView>
```

**Comment by Viet27th** [comment]
@kdbcinco 
Thank you for your reply.
Currently, I'm using this way.
`
< SafeAreaView
        edges={[
          "right",
          "left",
          ...(hideTopEdge ? ["top" as Edge] : []),
          ...(hideBottomEdge ? ["bottom" as Edge] : []),
        ]}
        style={Styles.safeArea}>
        {children}
</SafeAreaView >
`
but I need to import  "Edge" type from the library as below
`
import  { Edge } from "react-native-safe-area-context";
`
I don't know if it's the right way. I'm a newbie with typescript.

**Comment by janicduplessis** [comment]
This seems like a proper way to do it! Thanks @kdbcinco for helping

**Comment by janicduplessis** [comment]
You could also use `"top" as const` this forces the type of the variable to be the actual string `"top"` instead of `string`
