### ISSUE TITLE
SafeAreaView and Dark mode

### ISSUE THREAD

**Issue by NS-BOBBY-C** [th3rdwave/react-native-safe-area-context#168]
Hi all!

# Issue
I have an app which uses dark mode. In the image below, you can see the top-left corner of the screen near a back button. This line is what I assume to be the padding that the SafeAreaView uses with the insets - this is the area "underneath" the view, which is rendered with some default light color.

### From package.json
```
    ...
    "react-native-safe-area-context": "^3.1.8",
    ...
```

### Issue Screenshot

![IMG_6696](https://user-images.githubusercontent.com/29097404/104246270-b021c300-5433-11eb-9c17-b4c9da728d41.jpg)

I can work to change/fix an implementation. I am pretty new to this project, so I would need a pointer in the right direction and would want to discuss implementation - should this allow for the color to be the native apple/android dark/light mode colors, or should this be able to be set to any color? (imagine a red themed app)

Looking forward to collaboration,
Bobby

**Comment by janicduplessis** [comment]
Hey! We don't add any color in this library so I suspect this comes from somewhere else in your app. The insets are simply added as padding. If you are using <SafeAreaView /> you should be able to style it like a normal view.

**Comment by NS-BOBBY-C** [comment]
Hmm. I'll take a look at our work and see what's going on. 

I know we use a lot of the SafeAreaViews in our app, do you think that using too many would cause lag?

Thanks for the response! :)

**Comment by NS-BOBBY-C** [comment]
Confirmed this was an issue with our code. Sorry about that!
