### ISSUE TITLE
Simple application using React-Native-safe-area-context  crash on production build on iOS

### ISSUE THREAD

**Issue by allan-simon** [th3rdwave/react-native-safe-area-context#174]
version of the lib: 3.1.9
ios version  14.0
iphone 7

I have the following app 

App.tsx 

```jsx
import React from 'react';
import {Text} from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
export default function App() {

    return (
        <SafeAreaProvider>
            <SafeAreaView style={{height: '100%'}}>
                <Text>
                    Hello world{'\n'}
                    hello world  hellllllloo
                </Text>
            </SafeAreaView>
        </SafeAreaProvider>

    );
}
```

package.json 

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-safe-area-context": "3.1.9"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-dom": "~16.9.8",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}
```

when I run the app through expo  it works fine ,  but when i load the ipa, it crash just after the splash screen.

this however works :

```jsx
import React from 'react';
import {Text} from 'react-native';
export default function App() {

    return (
                <Text>
                    Hello world{'\n'}
                    hello world  hellllllloo
                </Text>
    );
}
```

I'm pretty new to mobile development so tell me if you need additional information.  I unfortunately don't have a mac so i'm building the app through  the expo build system

**Comment by janicduplessis** [comment]
Hey! It might be because expo requires a particular version of this library. Can you try using `expo install react-native-safe-area-context` to install it?

**Comment by allan-simon** [comment]
Hello, thanks for your message,  however it was already installed that way :(

**Comment by janicduplessis** [comment]
@brentvatne What’s the easiest way to get release crash logs on expo (without xcode)?

**Comment by brentvatne** [comment]
the only way to do this is with the xcode crashes organizer, should work the same for managed expo apps

**Comment by brentvatne** [comment]
can't reproduce this using the code you provided above. i suspect your app has some other unrelated code that is causing the crash.

i did a simulator build and ran it on an ios 7 ios 14.2, worked fine. you can try the simulator build here: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40notbrent/allan-a53f83be-4da9-44b7-8057-c8fb85d2e737-simulator.tar.gz

repo: https://github.com/brentvatne/allan-simon

**Comment by brentvatne** [comment]
yeah that might help, but the best option would be to provide a reproducible example that we can use to debug the issue

**Comment by brentvatne** [comment]
@allan-simon - can you share a git repo that i can clone and build to reproduce?

**Comment by allan-simon** [comment]
@brentvatne  i'm really sorry but as it was a quick experiment ,  the code has now been replaced by other sutff :/ 
but it was really nothing more than the code at the beginning of this ticket.

**Comment by brentvatne** [comment]
@allan-simon - i used that exact code and could not repro :/ see https://github.com/brentvatne/allan-simon - let me know if i'm missing something obvious there

**Comment by donnybystrom** [comment]
I got the same problem - It runs fine on Android, but on iOS it doesn't get past the splash screen.
If I remove SafeAreaProvider, everything works fine on iOS even when leaving all the SafeAreaView there. The app seem to load in the backgro
und, no errors, it just gets stuck on the splash screen.
