### ISSUE TITLE
SafeAreaProvider, useSafeArea, and SafeAreaConsumer not Working

### ISSUE THREAD

**Issue by arshiuh** [th3rdwave/react-native-safe-area-context#18]
I am using Expo so that might be a problem but I am getting these methods straight from the Expo documentation so idk what im doing wrong. :/

https://docs.expo.io/versions/v35.0.0/sdk/safe-area-context/

![image](https://user-images.githubusercontent.com/47709508/66801602-79769900-eece-11e9-90ae-4a42e37fa56b.png)

![image](https://user-images.githubusercontent.com/47709508/66803318-20116880-eed4-11e9-8a61-4b53be4b489f.png)

![image](https://user-images.githubusercontent.com/47709508/66803393-53ec8e00-eed4-11e9-85ce-82a891313f7b.png)

**Comment by billouboq** [comment]
SafeAreaConsumer or SafeAreaView needs to be inside the SafeAreaProvider otherwise it won't work at all.

Best way is to wrap the entire application with SafeAreaProvider

**Comment by janicduplessis** [comment]
Looks like this is resolved. Feel free to open a PR to open documentation if this could be explained better.

**Comment by Amna-Coder404** [comment]
thanks for usefull information!
