### ISSUE TITLE
iPhone 12 Safe Area Not Respected

### ISSUE THREAD

**Issue by ChrisHatchDev** [th3rdwave/react-native-safe-area-context#183]
The safe area on the top of the iPhone 12, 12 Pro, and 12 Pro Max do not adjust accordingly. Seems to be a missing declaration of screen height for these new phones

**Comment by ChrisHatchDev** [comment]
Seems related to "react-navigation" version of SafeAreaView. Closing the issue now and replacing the import to correct the issue on our end.

**Comment by vishal1198** [comment]
Hi, from which version to which version you have migrated the react-navigation , is some other package is available to handle this exact issue..
Even have created some issues related to this in git hub. Will share you that for reference.
[](https://github.com/react-navigation/react-navigation/issues/9855
https://github.com/facebook/react-native/issues/32142)
