### ISSUE TITLE
[Android] initialWindowMetrics with insets on screen with no notch

### ISSUE THREAD

**Issue by pesseyjulien** [th3rdwave/react-native-safe-area-context#186]
Hi,

I'm having an issue using the SafeAreaView on Android, the initialWindowMetrics comes with bottom/top insets whereas the emulator device has no notch (see enclosed).

```
'Metrics ', { frame: 
       { height: 659.4285888671875,
         y: 24,
         width: 411.4285583496094,
         x: 0 },
      insets: { right: 0, bottom: 48, left: 0, top: 24 } }
```

![Capture d’écran 2021-03-16 à 18 11 01](https://user-images.githubusercontent.com/10850944/111351706-bf1b3080-8683-11eb-87e7-e471be84cebc.jpg)

Any idea what could be wrong on my side ?

Thanks in advance for your help

,
Julien Pessey

**Comment by impe93** [comment]
Did you find any fix for that?

**Comment by pesseyjulien** [comment]
@impe93 Nop !

**Comment by BridgeEast** [comment]
I have the same issue !

**Comment by jacobp100** [comment]
It might be the status bar
