### ISSUE TITLE
0.5.0 broken - SafeAreaView undefined

### ISSUE THREAD

**Issue by lgraubner** [th3rdwave/react-native-safe-area-context#19]
The latest published release on NPM (0.5.0) seems to be broken. `SafeAreaView` is `undefined`:

```JavaScript
import { SafeAreaView } from 'react-native-safe-area-context';
```

I have wrapped everything in a `SafeAreaProvider`. 0.4.1 Works fine for me.

**Comment by janicduplessis** [comment]
Strange, can you look under node_modules to see if SafeAreaView exists, it is in this file https://github.com/th3rdwave/react-native-safe-area-context/blob/master/src/index.tsx#L56.

**Comment by Nigol496** [comment]
I'm getting similar error. 
 `TypeError: React.useContext is not a function
This error is located at: in SafeAreaProvider (at setup.js:14)`

Here is my Setup.js

`import React, { Component } from "react";
import { StyleProvider } from "native-base";

import App from "../App";
import getTheme from "../theme/components";
import variables from "../theme/variables/focalPoint";
import { SafeAreaProvider } from 'react-native-safe-area-context';

export default class Setup extends Component {
  render() {
    return (
      <SafeAreaProvider>
        <StyleProvider style={getTheme(variables)}>      
            <App />
        </StyleProvider>
         </SafeAreaProvider>
    );
  }
}
`

**Comment by janicduplessis** [comment]
Going to close as inactive.
