### ISSUE TITLE
[Feature Request] Safe area height and width

### ISSUE THREAD

**Issue by novasponge** [th3rdwave/react-native-safe-area-context#20]
Since dimensions has does not give correct height of the safe area for android devices with notches. It would be nice this library also give the height and width of the safe area.

it might benefit some modal like views with animations when not using react native modal.

**Comment by janicduplessis** [comment]
I think it would be better to figure out a way to fix height in RN's Dimensions module instead of duplicating the functionality here. I should be possible to detect notches in RN's implementation and adjust height.
