### ISSUE TITLE
bottom inset is 0 on OnePlus 7 Pro

### ISSUE THREAD

**Issue by israelidanny** [th3rdwave/react-native-safe-area-context#206]
I'm getting a false bottom inset of 0. `initialWindowMetrics` specifies a correct inset of 56, but even using that, it quickly changes to 0.

Using Expo and `react-native-safe-area-context` version 3.2.0, Android v11

**Comment by Nazort** [comment]
Having a similar problem with OnePlus 5T. 

When using `useSafeAreaInsets` the bottom value is equal to 0, but when using the `initialWindowMetrics` object, insets.bottom is 48

With react-native-safe-area-context : 3.2.0 and android v10

**Comment by terryatgithub** [comment]
I've encounted the same issue with emulator and devices too.

**Comment by danielha0221** [comment]
having the same issue with Samsung Galaxy A32

**Comment by f-ricci** [comment]
Having the same issue with Samsung Galaxy A41.

Seems to be a problem with something called "softbar" ?

**Comment by isaachinman** [comment]
Seeing this issue as well. Bottom inset is zero on all tested Android devices when navigation bar is enabled.

Any quick fix?

**Comment by monkora** [comment]
This is also happening to me, using a Pixel 3 emulator.

**Comment by samcarlinone** [comment]
Seeing the same issue on a Pixel emulator running Android 12.

Happens in versions 3.4.1 and 4.3.3

**Comment by jacobp100** [comment]
Android has a bunch of xml configs for this stuff. I know it's not documented here (PRs would be really apprecianted) - but you do have to configure them

**Comment by taylorkline** [comment]
@jacobp100 

> Android has a bunch of xml configs for this stuff.

What does this mean? Any concrete information would be helpful.

> I know it's not documented here (PRs would be really apprecianted) - but you do have to configure them

Can you leave this Issue open, then, and perhaps rename it to reflect that it's about missing / needed documentation about some XML configs?

**Comment by jacobp100** [comment]
https://github.com/th3rdwave/react-native-safe-area-context/issues/349
