### ISSUE TITLE
remove usages of jcenter()

### ISSUE THREAD

**Issue by dlwo159** [th3rdwave/react-native-safe-area-context#209]
WARNING:: Please remove usages of jcenter() Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-safe-area-context'

**Comment by janicduplessis** [comment]
Fixed
