### ISSUE TITLE
SafeAreaProvider doesn't render content on Android if the view remounts

### ISSUE THREAD

**Issue by satya164** [th3rdwave/react-native-safe-area-context#21]
When the view containing the `SafeAreaProvider` remounts, the content isn't rendered. Repro: https://snack.expo.io/@satya164/safe-area-bug

It works on iOS and Web. Because of this issue, it's not possible to use React Navigation 5 on Snack right now :(

**Comment by krakz999** [comment]
same issue

**Comment by snicro** [comment]
Having the same issue. @satya164 found  any workarounds for this?

**Comment by janicduplessis** [comment]
@satya164 Do you know if this is still an issue?

**Comment by satya164** [comment]
It only happened on snack so I can't check until expo includes it :<

**Comment by VictorBaron** [comment]
Seems to still be an issue. On Android our app never leaves the SplashScreen when we add a SafeAreaProvider.
