### ISSUE TITLE
when running on an M1 Mac top value is incorrect

### ISSUE THREAD

**Issue by chrisdrackett** [th3rdwave/react-native-safe-area-context#210]
At the moment when running an iOS app on a Mac the `top` value is reporting the same value that it would on an iPad. IMO this is incorrect because unlike an iPad the app on the Mac has no status bar so I think the top value should report as `0`.

Screenshot:
![CleanShot%202021-08-26%20at%2016 03 33](https://user-images.githubusercontent.com/4378/131047271-28fabad6-c17c-4fa4-9131-ea7da44267fc.png)

on an iPad the wifi and battery info are shown in the yellow bar at the top, but on a Mac nothing is shown in that area.

**Comment by aforty** [comment]
Would be great to `isiOSAppOnMac` to show the correct top value.

**Comment by chrisdrackett** [comment]
This is still an issue on `Monterey`. We ended up fixing this manually based on `isiOSAppOnMac` but I'd love to take out that extra code :)

**Comment by aforty** [comment]
Okay Apple won't fix this apparently.

![Screen Shot 2021-09-23 at 4 12 13 PM](https://user-images.githubusercontent.com/523683/134577291-198b3296-f7d8-4476-8da0-85a456bbb644.png)

**Comment by jacobp100** [comment]
I think you're gonna have to work around this in your own code. It's not safe for us to make assumptions here, as the safe areas don't only relate the status bar etc., but also things like UINavigationControllers.

**Comment by janicduplessis** [comment]
I agree, we'll keep it as won't fix here too, this can be handled in app code.

**Comment by chrisdrackett** [comment]
I'm not going to push this issue too hard as I've already got a fix, but this area is not used for anything when running an app on a Mac. I would personally assume that most uses of this package would expect the safe area at the top of the window to be 0. If left as is seems like everyone or almost everyone will have to handle this themselves.

**Comment by aforty** [comment]
I agree with @chrisdrackett, it's about expectations and what "appears" to be an incorrect value for an area that is never used. As you can see above Apple will not fix this but I think this package should be sensible enough to fix this for the user. I also have a fix in place but that's my thought on it.

**Comment by ex3ndr** [comment]
How you guys fixed that? It is 2025 and still not clear how to work-around this
