### ISSUE TITLE
iphone xr withSafeAreaInsets()

### ISSUE THREAD

**Issue by nschild** [th3rdwave/react-native-safe-area-context#215]
I have an iphone xr, which has a top notch and a soft bottom nav button thing.
This looks correct for portrait: `this.props.insets = {"bottom": 34, "left": 0, "right": 0, "top": 48}`

And on portrait, the notch is now on the left, and th bottom bar thing is moved to the bottom and I get these insets:
insets `this.props.insets = {"bottom": 21, "left": 48, "right": 48, "top": 0}`. I would expect it to come across as `this.props.insets = {"bottom": 34, "left": 48, "right": 0, "top": 0}`

Are the left and right both set to 48 expected?

**Comment by arturbil** [comment]
Hi @nschild, struggling with the same problem. Have you found any reasonable workaround?
