### ISSUE TITLE
TypeScript compilation failing

### ISSUE THREAD

**Issue by sebinq** [th3rdwave/react-native-safe-area-context#22]
Hello!

When I run TS compilation for my project I'm keep getting following error:

```bash
node_modules/react-native-safe-area-context/lib/typescript/src/index.d.ts:3:10 - error TS2440: Import declaration conflicts with local declaration of 'EdgeInsets'.

3 import { EdgeInsets } from './SafeArea.types';
```

I would like to ask you if there is something wrong with my tsconfig as I'm new to TypeScript and I don't know much about it.

Thank you so much!

**Comment by janicduplessis** [comment]
Strange that the error doesn't show up when working on the project repo... I renamed the variable so it should fix the issue. 

I think you can also use `"skipLibCheck": true` in your tsconfig compiler options so errors in node_modules don't prevent your project from compiling.

**Comment by fabiancarlos** [comment]
The package  was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/.../node_modules/react-native-safe-area-context/src/index.tsx`. Indeed, none of these files exist: 

what is this?
