### ISSUE TITLE
SafeAreaProvider doesn't support all the props of a View.

### ISSUE THREAD

**Issue by SohelIslamImran** [th3rdwave/react-native-safe-area-context#222]
`SafeAreaProvider` doesn't support all the props of a `View`.

![image](https://user-images.githubusercontent.com/76745339/142209793-b07426b8-3f34-4c25-88da-d21a7e781456.png)
[In the example said supported, but actually not.](https://github.com/th3rdwave/react-native-safe-area-context/blob/main/README.md#example)

Because You forgot to spread other props. [here](https://github.com/th3rdwave/react-native-safe-area-context/blob/34c30b52d63141889d76c3439265f7f366d0390e/src/SafeAreaContext.tsx#L28)

![image](https://user-images.githubusercontent.com/76745339/142209814-93d33a1d-ef5f-4099-9eac-b7ba6e003c58.png)

I need the `onLayout` props of `View`.

**Comment by kivohin** [comment]
Same scenario here, I need to use the `onLayout` prop as well, and right now it doesn't work.

**Comment by janicduplessis** [comment]
Thanks for reporting this, fixed in 446add02d3b723763eced2bc18e55a06dc76722c, will release a new version soon.
