### ISSUE TITLE
Unexpected behaviour when wrapping a *List Component

### ISSUE THREAD

**Issue by mydesweb** [th3rdwave/react-native-safe-area-context#228]
When I wrap any List with SafeAreaProvider the list Items are rendered multiple times. Please check this snack [https://snack.expo.dev/@mydesweb/safeareaissue](https://snack.expo.dev/@mydesweb/safeareaissue) . 

1. Open the code from your device
2. Check the console logs
3. Shake & Reload button from expo app or remove the app from background and open again
4. You will see unexpected multiple Item renders

In my example I use BigList but it is the same with SectionList from RN.

**Comment by mydesweb** [comment]
<img width="248" alt="Screenshot 2021-12-19 at 11 42 30" src="https://user-images.githubusercontent.com/5901386/146670425-b34453b6-50fe-4421-84ea-507454a06449.png">

**Comment by ddikodroid** [comment]
did you solve it?

**Comment by jacobp100** [comment]
I think this isn't an issue any more
