### ISSUE TITLE
is:issue is:open import androidx.annotation.Nullable; 

### ISSUE THREAD

**Issue by Master-gg-02** [th3rdwave/react-native-safe-area-context#232]
React Native Environment Info:
    System:
      OS: macOS 11.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 225.46 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 28, 29, 30, 31
        Build Tools: 23.0.1, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-16 | Intel x86 Atom, android-19 | Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-screens: 2.9.0

work on ios  but the error apear in andorid runtime

**Comment by lekzd** [comment]
looks like I found solution that can helps https://github.com/facebookarchive/react-native-fbsdk/issues/600#issuecomment-624078479
