### ISSUE TITLE
Version 3.4.0 Pod installation issue

### ISSUE THREAD

**Issue by IanHancock36** [th3rdwave/react-native-safe-area-context#235]
Hello, When I updated to the most recent version 3.4.0 I am not able to build my app. I had to revert back to version 3.3.2 to build. Is there something I overlooked in installation instructions ? 

Here below is the error I was receiving prior to me reverting back to 3.3.2 

[!] CocoaPods could not find compatible versions for pod "react-native-safe-area-context":
  In Podfile:
    react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)

Specs satisfying the `react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)` dependency were found, but they required a higher minimum deployment target.

**Comment by janicduplessis** [comment]
@IanHancock36 3.4.0 now requires iOS 11+, this is also the minimum version supported by recent react native versions.

To fix it you can change the minimum version in your podfile to 11.0 (`platform :ios, "11.0"`).

**Comment by IanHancock36** [comment]
@janicduplessis I upgraded (platform :ios, "11.0") in the pod file and and reinstalled the latest version and did pod install. 
This solved the issue! Thank you very much

**Comment by IanHancock36** [comment]
@janicduplessis I upgraded (platform :ios, "11.0") in the pod file and and reinstalled the latest version and did pod install.
This solved the issue! Thank you very much
