### ISSUE TITLE
Wrong typings for higher order component withSafeAreaInsets

### ISSUE THREAD

**Issue by romixch** [th3rdwave/react-native-safe-area-context#237]
I use withSafeAreaInsets for a class component and a couldn't get the typings right. I wrote a test for it at my fork:
https://github.com/romixch/react-native-safe-area-context/blob/main/src/__tests__/SafeAreaContext-test.tsx#L123

I would expect this to be compilable but it's not:

```tsx
type Props = {insets: EdgeInsets}
  class TestClassComponent extends React.Component<Props> {
      render() {
        return (
          <View
            style={{
              paddingTop: this.props.insets.top,
              paddingLeft: this.props.insets.left,
              paddingBottom: this.props.insets.bottom,
              paddingRight: this.props.insets.right,
            }
          }
        />)
      }
  }
  const TestComponentWithInsets = withSafeAreaInsets(TestClassComponent)
  it('should provide correct typings', () => {
    ReactTestRenderer.create(
    <SafeAreaProvider>
      <TestComponentWithInsets />
    </SafeAreaProvider>)
  })
```

The type that comes out of `withSafeAreaInsets` should not include `insets` as it is the purpose of the higher order component to inject and hide it.

Unfortunately I was not able to fix it on my own. I'm obviously not that good at typescript magic. But could someone else fix it?

**Comment by romixch** [comment]
Thanks for your reply! I merged the changes into my [fork](https://github.com/romixch/react-native-safe-area-context). The problem still exists. Typescript expects the attribute inset to be set although this should not be necessary when using the component from `withSafeAreaInsets`.

**Comment by janicduplessis** [comment]
Ok, the types were actually wrong. It should now work in 4.2.0. I added an example on how to use the types https://github.com/th3rdwave/react-native-safe-area-context/blob/main/README.md#withsafeareainsets
