### ISSUE TITLE
Unexpected .iml file in npm package

### ISSUE THREAD

**Issue by Phecda** [th3rdwave/react-native-safe-area-context#24]
The npm package has an unexpected file `android/react-native-safe-area-context.iml` which may cause
```
Could not set process working directory to '/node_modules/react-native-safe-area-context/example/android': could not setcwd() (errno 2: No such file or directory)
```
in Android Studio.

## Solution
add `*.iml` to `.npmignore`

**Comment by janicduplessis** [comment]
Could you send a PR to fix this?

**Comment by Phecda** [comment]
I tried to run `npm pack` with npm 6.7.0, and no `iml` included. Perhaps something went wrong during packaging? If so, no need for PR, just pack a new package and make sure these files not inclueded.

**Comment by isabelleaubron** [comment]
Same issue here with "react-native-safe-area-context": "^0.6.2",
need to delete manually the iml file

**Comment by mikehardy** [comment]
@janicduplessis this does need a PR then a new release I think, I just proposed #24 based on how we do it in react-native-device-info, cheers :-)
