### ISSUE TITLE
V4 changelog / Github Release

### ISSUE THREAD

**Issue by renchap** [th3rdwave/react-native-safe-area-context#243]
Version 4.0.1 is now the latest available on NPM, but there is no Github Release, changelog or upgrade guide.

Would it be possible to create one of those, so we know what changed and how to upgrade?

Thanks!

**Comment by janicduplessis** [comment]
I posted a summary of the changes here https://github.com/th3rdwave/react-native-safe-area-context/releases/tag/v4.1.2
