### ISSUE TITLE
Compile Error with v4

### ISSUE THREAD

**Issue by hirbod** [th3rdwave/react-native-safe-area-context#245]
```

> Task :react-native-safe-area-context:compileDebugJavaWithJavac FAILED
/myapp/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaProviderManager.java:62: error: cannot find symbol
              UIManagerHelper.getSurfaceId(reactContext), reactTag, insets, frame));
                             ^
  symbol:   method getSurfaceId(ReactContext)
  location: class UIManagerHelper
/myapp/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/InsetsChangeEvent.java:15: error: no suitable constructor found for Event(int,int)
    super(surfaceId, viewTag);
    ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
Note: /myapp/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /myapp/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

React Native Version: 0.64.3

**Comment by janicduplessis** [comment]
What version of react-native are you using? This function was probably added in a more recent version.

**Comment by hirbod** [comment]
Hi, I am using 0.64.3. I downgraded back to 3.4.1 for now.

**Comment by ahansson89** [comment]
Still an issue on 4.0.2

**Comment by janicduplessis** [comment]
Ok, I think I missed the 2nd error. Can you try 4.1.0 (was in the middle of Kotlin rewrite, so I added the fix there)

**Comment by Pralad-Thapa** [comment]
I downgraded my react-native-safe-area-context to 3.3.2 and react-native-screens to 3.10.1 and it worked .
Help me in resolving this error [https://github.com/facebook/react-native/issues/33194](url)

**Comment by jwisbeck** [comment]
I too am getting this on 4.0.1

**Comment by hirbod** [comment]
@janicduplessis I can confirm that the issue has been fixed with 4.1.0.
Works well with react-native-screens 3.13.0 as well.

**Comment by janicduplessis** [comment]
Is that also on Android?

**Comment by hirbod** [comment]
@janicduplessis no, android is working fine.

**Comment by janicduplessis** [comment]
@hirbod Seems to be working fine in the example app, not sure what could cause this.

The code for getting initial insets was moved to a different module in 4.0, can you double check you ran pod install after updating?

**Comment by hirbod** [comment]
@janicduplessis you got me on this one. Sorry for the false alarm, I really did not ran `pod install` (expo prebuild) after installing it. It is working

**Comment by tetanet** [comment]
@hirbod could you please tell me install 4.1.0 version of what??
react-native-safe-area-context?

**Comment by hirbod** [comment]
I kinda don't wanna answer that question. :D
Of course react-native-safe-area-context.

**Comment by tetanet** [comment]
@hirbod I actually know that but not work for me, I m trying to downgrade Gradle version

**Comment by tetanet** [comment]
@hirbod  can I ask you what version of react-native you use?
I have tried on version 0.64.3 and 0.65.0 and also on the last version too.

**Comment by aryoputrap** [comment]
> I downgraded my react-native-safe-area-context to 3.3.2 and react-native-screens to 3.10.1 and it worked . Help me in resolving this error [https://github.com/facebook/react-native/issues/33194](url)

thank you

**Comment by davwheat** [comment]
@Developeranees Cheers! That solved my issue :)

**Comment by manziEric** [comment]
> just set compilesdk version from 29; to => compileSdkVersion = 30 in android/build.gradle

Thanks a Ton!! this worked for me with this error: react-native-safe-area-context:compileDebugKotlin

**Comment by lolyshow** [comment]
@Developeranees thanks that solved my problem. The project was done in expo before but started throwing error: react-native-safe-area-context:compileDebugKotlin after i moved to react cli. thanks for your solution

**Comment by u373693041** [comment]
> just set compilesdk version from 29; to => compileSdkVersion = 30 in android/build.gradle

thank you ! it solved my problem with error: react-native-safe-area-context:compileDebugKotlin

**Comment by hirbod** [comment]
@lolyshow I would've recommended to stay on expo and just use a custom-dev-client. I have a config-plugin ready to bump the compileSdk

```tsx
const {
    withProjectBuildGradle
} = require('@expo/config-plugins')

const setCompileSdkVersion = (buildGradle, sdkVersion) => {
    const regexpCompileSdkVersion = /\bcompileSdkVersion\s*=\s*(\d+)/
    const match = buildGradle.match(regexpCompileSdkVersion)

    if (match) {
        const existingVersion = parseInt(match[1], 10)

        if (existingVersion < sdkVersion) {
            buildGradle = buildGradle.replace(
                /\bcompileSdkVersion\s*=\s*\d+/,
                `compileSdkVersion = ${sdkVersion}`
            )
        } else {
            console.warn(`minSdkVersion is already >= ${sdkVersion}, skipping`);
        }
    }

    return buildGradle
}

module.exports = (config, sdkVersion) => {
    return withProjectBuildGradle(config, (config) => {
        if (config.modResults.language === 'groovy') {
            config.modResults.contents = setCompileSdkVersion(
                config.modResults.contents,
                sdkVersion
            )
        } else {
            throw new Error(
                "Can't set minSdkVersion in the project build.gradle, because it's not groovy"
            )
        }
        return config
    })
}
```

Add to your app.config.js/app.json (expo.plugins)

```ts
  plugins: [
    ['./plugins/withCompileSdkVersion', 31],
]
```

**Comment by vvarh** [comment]
> just set compilesdk version from 29; to => compileSdkVersion = 30 in android/build.gradle

thank you !
what about the rest of the options in build.gradle?


        buildToolsVersion = "29.0.3" //  doesn't look correct.
        minSdkVersion = 21
        compileSdkVersion = 30 // updated since 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"

**Comment by emadbaqeri** [comment]
I'm using `react-native` `0.71` in my project alongside `react-navigation` `v6` updating my `compileSdkVersion` to 31 worked in my case

**Comment by adnen-chouibi** [comment]
🎉 🎉 🎉  If you are using Yarn, try to:
```
yarn remove react-native-safe-area-context
yarn start --reset-cache
yarn add react-native-safe-area-context
``` 
Do the same with other package managers

**Comment by ace0109** [comment]
> 🎉 🎉 🎉 If you are using Yarn, try to:
> 
> ```
> yarn remove react-native-safe-area-context
> yarn start --reset-cache
> yarn add react-native-safe-area-context
> ```
> 
> Do the same with other package managers

This does work, but why? None of the programs mentioned above work for me

**Comment by pheN1x** [comment]
> [](url)
This work for me for android!! Thanks a lot!
