### ISSUE TITLE
react-native-windows "RNCSafeAreaProvider" was not found in the UIManager

### ISSUE THREAD

**Issue by AlenToma** [th3rdwave/react-native-safe-area-context#249]
I know that this question has been asked before but all of them are all about `android` or `IOS `I am having this problem in `react-native-windows
`
`"RNCSafeAreaProvider" was not found in the UIManager`

 Is there any thing I could do about this? I think that the autolinking not working for react-native-windows

Here is my Package.JSON
```
  "dependencies": {
    "@alentoma/usestate": "^1.2.4",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "react": "17.0.2",
    "react-native": "0.67.3",
    "react-native-safe-area-context": "^4.1.2",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.67.3"
  }
```

You can see That I am using the latest version and still having this issue

**Comment by janicduplessis** [comment]
Should be fixed in 4.1.3
