### ISSUE TITLE
Pre AndroidX version

### ISSUE THREAD

**Issue by manish-jain-1** [th3rdwave/react-native-safe-area-context#25]
I am checking history of this repo and I believe there is no version, not even 0.1.0 (I think) that support pre-AndroidX. We haven't yet migrated to AndroidX (or RN 0.60) but looking to use this library. Interestingly I expect 0.3.3 that is pre RN 0.60 version to be without AndroidX but it is not!

**Comment by janicduplessis** [comment]
I don't plan on releasing a pre-android x version but it should be easy to patch. I think the only uses are `androidx.annotation.Nullable` so you can probably juste replace them with the pre-android x version. You can use `patch-package` to save the changes under node_modules.

**Comment by nicolasdanelon** [comment]
@janicduplessis can you please update the code? 
the use of patch-package is not a good practice :cry:

**Comment by janicduplessis** [comment]
Sorry, there is no plan to support pre-android x. Feel free to fork or use patch-package instead.

**Comment by janicduplessis** [comment]
You can also have a look at jetifier and the reverse mode. See https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-507010053

**Comment by pandevim** [comment]
You can use `react-native-safe-area-context <= 0.7.2` and remove all of the annotation imports from the files. For example in `SafeAreaProvider.java`:
https://github.com/th3rdwave/react-native-safe-area-context/blob/d95b5d5e8be54106baba2db5b1692e2deb3f5875/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaProvider.java#L11
Change it to:
```diff
-import androidx.annotation.Nullable;
+import android.support.annotation.Nullable;
```
