### ISSUE TITLE
Wrong SafeAreaProvider gets imported on react-native-macos

### ISSUE THREAD

**Issue by hsjoberg** [th3rdwave/react-native-safe-area-context#251]
Hey.

When importing `<SafeAreaProvider>`, for some reason the native module gets imported instead of the fallback for macOS, `NativeSafeAreaProvider.macos.tsx`.

In other words, `NativeSafeAreaProvider.ts` gets imported instead of `NativeSafeAreaProvider.macos.tsx`, which results in `specs/NativeSafeAreaProvider.js` getting imported causing a crash.
Seems to be some module resolving issue, but it should probably be possible mitigate.

**Comment by janicduplessis** [comment]
Fixed in 4.1.3, thanks for the PR!
