### ISSUE TITLE
Requiring expo-cli in package.json means any app using this package will not build using Expo

### ISSUE THREAD

**Issue by jackkinsella** [th3rdwave/react-native-safe-area-context#256]
The Expo team have moved to a system called EAS Build lately. I was talking with someone from their team earlier today and they told me that if an app installs `expo-cli` on their servers, then the build process will fail. Because my app uses `react-native-safe-area-context`, it will no longer build for Expo. I confirmed this today when trying to build an iOS app that uses this the `react-native-safe-area-context` library.

Would you consider removing this package from `package.json` in order to maintain Expo support?

**Comment by jackkinsella** [comment]
For reference, the Expo documentation recommends a global install of their CLI package, https://docs.expo.dev/workflow/expo-cli/

**Comment by janicduplessis** [comment]
Thanks for the PR, merged and released in 4.2.3
