### ISSUE TITLE
Export initial mount window insets

### ISSUE THREAD

**Issue by jacobp100** [th3rdwave/react-native-safe-area-context#26]
If we exported the insets of the window when the app launched, we could avoid delaying the rendering of the subtree, which could improve initial mount performance

```jsx
import {SafeAreaProvider, initialMountWindowInsets} from 'react-native-safe-area-context';

<SafeAreaProvider initialSafeAreaInsets={initialMountWindowInsets}>
  {content}
</SafeAreaProvider>
```

We might even be able to make this the default. But I'm not sure that's safe (and I'm not sure the current behaviour of inheriting the parent's insets is safe either) because if you present a modal in page sheet mode, the insets will be different from the root

We'd need to check the value of the insets when they get updated from the `onInsetsChange` event to avoid reconciling the subtree twice

Is this a change you'd accept a PR for?

**Comment by janicduplessis** [comment]
Added android support too, let's close this!
