### ISSUE TITLE
SafeAreaView adding padding to bottom when used with ScrollView in React Navigation 6

### ISSUE THREAD

**Issue by chinesehemp** [th3rdwave/react-native-safe-area-context#270]
Hello, I'm having some weird padding issues when I use a ScrollView inside a SafeAreaView using Expo 44, React Navigation 6 bottom Tab navigator, React Native Paper and tailwind.

Note that I'm running this using Expo Web and this is presented as a PWA in the iOS simulator. There's no padding issue inside Safari. Only when it is saved as a desktop bookmark and running as PWA the padding issue appears.

Any ideas on why and how to fix it, please? Thank you! 🙏🏻

<img width="450" alt="Screenshot 2022-04-12 at 22 31 18" src="https://user-images.githubusercontent.com/58605231/163059328-93270702-58cb-4064-b96f-ed95bf553416.png">

```jsx
import React from "react";
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScrollView } from "react-native";
import { Appbar } from "react-native-paper";
import tailwind from "tailwind-rn"

const Home: React.FC = () => {
  return (
    <SafeAreaView style={{flex: 1, padding: 0}}>
      <Appbar
        style={{
          height: 50,
        }}
      >
        <Appbar.Content
          subtitle="The highest authority"
          subtitleStyle={tailwind('text-xs')}
        />
        <Appbar.Action icon="menu" />
      </Appbar>
      <ScrollView style={tailwind("mb-0 pb-0 bg-black")}>
      {SOME LONG OVERFLOWING CONTENT HERE...}
      </ScrollView>
    </SafeAreaView>
  );
};

export default Home;
```

**Comment by chinesehemp** [comment]
I solved it by adding `<SafeAreaView edges={['top', 'left', 'right']} style={tailwind("flex-1 pb-0 mb-0")}>`

**Comment by Salman9000** [comment]
> I solved it by adding `<SafeAreaView edges={['top', 'left', 'right']} style={tailwind("flex-1 pb-0 mb-0")}>`

Works like a charm! thank you
