### ISSUE TITLE
ERROR: Unknown host CPU architecture: arm64

### ISSUE THREAD

**Issue by maximzhemerenko** [th3rdwave/react-native-safe-area-context#272]
When I build Android app (react native 0.68.1) using arm based MacBook Pro M1, I receive 'Unknown host CPU architecture: arm64' error. This happens because library uses default ndkVersion, but not custom ndkVersion from 'ext'. I propose include this line in the build.gradle file to use globally specified ndkVersion if exists.

I created merge request https://github.com/th3rdwave/react-native-safe-area-context/pull/271

p.s. The code based on react-native implementation https://github.com/facebook/react-native/blob/23b6240b256b2afb0e5efb2cef1ce27cbd0fcdf8/ReactAndroid/build.gradle#L257-L262

**Comment by jacobp100** [comment]
https://github.com/th3rdwave/react-native-safe-area-context/pull/348
