### ISSUE TITLE
React Native Android bottom navigation disappears

### ISSUE THREAD

**Issue by Hayk-Zohrabyan** [th3rdwave/react-native-safe-area-context#277]
Help me please.

    "react": "18.1.0",
    "react-native": "0.68.1",
    "react-native-safe-area-context": "^2.0.3",

https://user-images.githubusercontent.com/40742437/166536009-69b3d654-c929-433e-aa51-15410408e7f1.mp4

**Comment by TomCorvus** [comment]
Hi,
I think we need more information to help you, or maybe a repo to reproduce your problem.
With your info, I can just tell you that react 18 isn't entirely compatible with react native 0.68.

> About React 18: React 18's new rendering engine is not supported by React Native 0.68, this will happen in a future version.
https://reactnative.dev/blog/2022/03/30/version-068

**Comment by Hayk-Zohrabyan** [comment]
@MiteshJabuani yes.

https://reactnavigation.org/docs/5.x/bottom-tab-navigator/#keyboardhidestabbar

<img width="585" alt="Screen Shot 2022-10-03 at 21 39 41" src="https://user-images.githubusercontent.com/40742437/193643166-df707e31-a2d0-448b-8f6f-c7002bff02fe.png">
<img width="825" alt="Screen Shot 2022-10-03 at 21 40 07" src="https://user-images.githubusercontent.com/40742437/193643172-b8c43c39-5c34-4e7a-84b0-9b7406f26458.png">
