### ISSUE TITLE
`ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.`

### ISSUE THREAD

**Issue by KrisLau** [th3rdwave/react-native-safe-area-context#278]
Getting the `ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.` on my app. Not 100% sure but I think it might be from this package

**Comment by janicduplessis** [comment]
Not using `ViewPropTypes` so it is not coming from this package.

**Comment by Nesh108** [comment]
@janicduplessis yes, this issue affects this library as well:

Look at the following files:

- src/specs/NativeSafeAreaProvider.js
- src/specs/NativeSafeAreaView.js

You should changing the `ViewProps` import to this:

`import type { ViewProps } from 'deprecated-react-native-prop-types';`
