### ISSUE TITLE
V4 don't works with Modal

### ISSUE THREAD

**Issue by Jawkx** [th3rdwave/react-native-safe-area-context#279]
# Issue
 `<SafeAreaView/>` not working inside Modal, using `useSafeAreaInset()` and it is working correctly. At V3 it was working correctly.

I created a demo repo to better demonstrate it and help reproduce the bug [here](https://github.com/Jawkx/testReactNativeApp/tree/react-native-safe-area-context-not-working-on-modal), with screenshot in the [`README.md` there](https://github.com/Jawkx/testReactNativeApp/blob/react-native-safe-area-context-not-working-on-modal/README.md)

Working on V3 just broke on V4. Sorry can't really help with the problem because i'm not really familiar with native codes

## Version:
| package | version |
| --- | --- |
| react | 17.0.2|
| react-native| 0.68.1|
| react-native-modal| 11.5.6|
|react-native-safe-area-context| 4.2.4|

_This specific versioning is due to my app use this exact version**_

**Comment by zsomborgellerfi** [comment]
I am experiencing the same issue after upgrading the package.

**Comment by VictorioMolina** [comment]
Same here. To fix it, just wrap your modal childs inside a new provider, locally:
```

    <Modal
      animationType="slide"
      visible={visible}
      hardwareAccelerated
      statusBarTranslucent
      transparent
      onRequestClose={onClose}
    >
      <SafeAreaProvider>
        <Map
          searchBarPlaceholder={searchBarPlaceholder}
          showsUserLocation={showsUserLocation}
          onClose={onClose}
        />
      </SafeAreaProvider>
    </Modal>
```

**Comment by ammarfaris** [comment]
> Same here, after upgrading my react native project to _v. 0.68_. To fix it, just wrap your modal childs inside a new provider, locally:
> 
> ```js
> <Modal
>   animationType="slide"
>   visible={visible}
>   hardwareAccelerated
>   statusBarTranslucent
>   transparent
>   onRequestClose={onClose}
> >
>   <SafeAreaProvider>
>     <Map
>       searchBarPlaceholder={searchBarPlaceholder}
>       showsUserLocation={showsUserLocation}
>       onClose={onClose}
>     />
>   </SafeAreaProvider>
> </Modal>
> ```

Thanks @VictorioMolina and @JeremyBradshaw7 .. Almost giving up looking for solution for ios..again, thanks!

**Comment by sergeu90** [comment]
I have same issue after update.

**Comment by JB712** [comment]
Got the same issue but VictorioMolina got the solution ! Thanks! (https://github.com/th3rdwave/react-native-safe-area-context/issues/279#issuecomment-1159644248)

Is the issue still going on with RN0.69 and RN0.70 ? Or is it specific to 0.68 ?

**Comment by jacobp100** [comment]
Yes - you need another SafeAreaProvider inside the modal

**Comment by MetaBenji** [comment]
Why is another provider required?  It's not a good pattern to have multiple providers within the app.  Apps can have a lot of modals so having a provider within each modal is cumbersome and prone for developers in the future to run into issues by not knowing this is necessary.

**Comment by jacobp100** [comment]
It’s necessary because the safe area changes, and the provider establishes a new context for safe areas. Just make your own modal abstraction that includes the safe area
