### ISSUE TITLE
Releases missing for all tags after 4.1.4

### ISSUE THREAD

**Issue by SMJ93** [th3rdwave/react-native-safe-area-context#281]
Have the release notes / changelogs moved?

The tags are showing:
![Screenshot 2022-05-19 at 17 03 34](https://user-images.githubusercontent.com/2145641/169346189-888ecfed-c940-4507-9e5a-c40e08718532.png)

But the most recent release is 4.1.4:
![Screenshot 2022-05-19 at 17 04 48](https://user-images.githubusercontent.com/2145641/169346477-916f9efb-8308-479a-acfd-366d1c067826.png)

**Comment by swkang0513** [comment]
Yes, we want changelogs!

**Comment by jacobp100** [comment]
There're still there? https://github.com/th3rdwave/react-native-safe-area-context/releases

**Comment by SMJ93** [comment]
@jacobp100 there are no releases between 4.1.4 and 4.3.3.

Will lose the issue as newer tags have releases 👍
