### ISSUE TITLE
additional indent appears if I use several several SafeAreaView in one SafeAreaProvider

### ISSUE THREAD

**Issue by Adudarchyk** [th3rdwave/react-native-safe-area-context#282]
If I need to add several SafeAreaViews on my screen, then the bottom one will still take a safe distance, although there is another component above it, and in theory it should not give any indents, how can I get rid of this behavior?

Running version 4.2.4

**Comment by jacobp100** [comment]
No - this is intentional. Use the `edges` prop to configure this
