### ISSUE TITLE
Version > 4 not working on IOS

### ISSUE THREAD

**Issue by iamn1ck** [th3rdwave/react-native-safe-area-context#289]
Hello, 

I was updating the dependencies in my app recently and when I updated this dependency v3.4.1 to the latest version 4.1.4 the app is now rendering where the StatusBar is displayed in IOS. If I use the SafeAreaView provided by react-native then its working, but I would like to use this package because its supposed to support IOS and Android. Has anyone else had this issue?

**Comment by aballister** [comment]
Try this https://github.com/th3rdwave/react-native-safe-area-context/issues/279#issuecomment-1159644248

**Comment by cobaltp** [comment]
You can try wrap the SafeAreaView with SafeAreaProvider like this.

```
<SafeAreaProvider>
  <SafeAreaView>
    ...
  </SafeAreaView>
</SafeAreaProvider>
```

It works for me for both iOS 15.6 and Android 12.

**Comment by cobaltp** [comment]
You can try to wrap the SafeAreaView with SafeAreaProvider like this.

```
<SafeAreaProvider>
  <SafeAreaView style={styles.container}>
    ...
  </SafeAreaView>
</SafeAreaProvider>
```

It works for me in for both iOS 15 and Android 12.
