### ISSUE TITLE
Android: Top inset is changed on keyboard dismissal when windowSoftInputMode = adjustPan

### ISSUE THREAD

**Issue by petekp** [th3rdwave/react-native-safe-area-context#29]
Not sure if this is the expected behavior, but when `windowSoftInputMode` is set to `adjustPan`, the `top` inset changes significantly after opening and dismissing the keyboard, i.e. the `top` inset can increase from `0` to over `100` after the keyboard is dismissed.

On Android, the `adjustPan` input mode automatically shifts the screen upward so that focused text inputs are moved above the software keyboard. This input mode is often recommended for handling input/keyboard avoidance on Android due to inconsistent behavior with `KeyboardAvoidingView`. I assume that when the app screen is shifted back downwards, the top inset value is set to the Y offset value used to pan the view back into its original position. 

If this is expected behavior, it seems inconsistent in that the `bottom` inset doesn't change when the pan-upwards effect is performed upon opening the keyboard.

In my particular use case, the fact that the `adjustPan` mode affects insets makes it difficult to rely on the safe area context insets in places that are intended to account only for the presence of notches: I'm using the `top` inset to add top padding to a navigation bar but the padding value jumps in size after dismissing the keyboard.

**Comment by sshmyg** [comment]
Have same issue for Android 9.
1. focus input field.
2. hide keyboard with this button 
![image](https://user-images.githubusercontent.com/1410608/70324290-bfe5d580-1837-11ea-9df5-369ba0fd0f29.png)
3. Got large top padding

**Comment by alimek** [comment]
as investigation for https://github.com/react-navigation/stack/issues/326 looks like if you have `windowSoftInputMode` is set to `adjustPan` code here: https://github.com/th3rdwave/react-native-safe-area-context/blob/master/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.java#L69 is executed when view is moved and keyboard is still visible, so its generating wrong number which is breaking calculation in next lines.

I am not Android dev and I am not sure if i can help fixing this in code 😭  hope my investigation is helping, at least something 👍

**Comment by ninjacoder95** [comment]
I decided to use react-native-status-bar-height.

**Comment by papigers** [comment]
Same issue here.
For now using `react-native-status-bar-height` as @ninjacoder95 suggested.

**Comment by petekp** [comment]
@ninjacoder95 @papigers I'm unsure how knowing the status bar height would resolve this particular issue. The problem I ran into was the `top` inset increasing drastically after dismissing the keyboard, often to an arbitrary size not based on the dimensions of other elements.

**Comment by janicduplessis** [comment]
Thanks for the detailed repro, looking at this issue today.

**Comment by janicduplessis** [comment]
Fixed in 0.7.0
