### ISSUE TITLE
Ability to get inset values outside of a react component

### ISSUE THREAD

**Issue by AdamGerthel** [th3rdwave/react-native-safe-area-context#30]
I'm looking for a way to use the inset values in styles outside of a component, i.e. without having to use the provided wrapper components, similar to `Dimensions.get('window')` for example. I want this feature because my app doesn't change orientation and I only want to add inset margins/paddings every here and there in my styles. I'm also using MobX which makes it really hard to use components based on render functions because they break the functionality of mobx-react.

Is there a way to do this?

I would use https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets which provides this functionality, but I'm using expo so linking is a no-go.

**Comment by nabilfreeman** [comment]
Thanks for linking to the other library, that's actually what I wanted. 👏

**Comment by janicduplessis** [comment]
We export `initialWindowMetrics` which has initial inset values, but I don't plan on adding more static apis since it tends to be a footgun.

**Comment by a-eid** [comment]
@janicduplessis 
![Screen Shot 2020-05-27 at 11 20 29 AM](https://user-images.githubusercontent.com/19273413/83002145-fb09da00-a00c-11ea-922d-2b99730410de.png)

**Comment by a-eid** [comment]
@janicduplessis I come to this issues time after time, it would be very nice to have.
