### ISSUE TITLE
"Margin collapse" in SafeAreaView?

### ISSUE THREAD

**Issue by fo-fo** [th3rdwave/react-native-safe-area-context#308]
Here's a suggestion. Currently SafeAreaView adds any margin specified by the component user to the safe area margin (assuming mode=margin here.) Sometimes it would be useful to take the _maximum_ of the two margins instead. For example, for a toast at the top of the screen I might want to add some margin myself, but if the safe area margin is already bigger than that margin, then I would like to use that instead.

I know I can already achieve this with `useSafeAreaInsets`, but I'd like to avoid the caveats of the hook.

**Comment by jacobp100** [comment]
I think it's a good feature. Not really sure what the prop would be called - we already used `mode`.

If you're happy to take a stab at it, I'm happy to give pointers.

Start off with this file - https://github.com/th3rdwave/react-native-safe-area-context/blob/main/ios/RNCSafeAreaShadowView.m

**Comment by jacobp100** [comment]
Added in 4.6
