### ISSUE TITLE
Add support for new iPhones (14, 14 Plus, etc.)

### ISSUE THREAD

**Issue by julienR2** [th3rdwave/react-native-safe-area-context#310]
Hey there 👋 

The latest Xcode update (14), brought the iPhone 14, 14 Plus, 14 Pro, and 14 Pro Max simulators. Testing our app on it this morning, I could see that the insets don't seem to be handled correctly on those.

|iPhone 13|iPhone 14|
|-|-|
|![Simulator Screen Shot - iPhone 13 - 2022-09-01 at 16 22 45](https://user-images.githubusercontent.com/3007435/190119334-62877c7d-ca32-42db-96c4-9a5ba55103d6.png)|![Simulator Screen Shot - iPhone 14 - 2022-09-14 at 10 28 54](https://user-images.githubusercontent.com/3007435/190119342-16e0ebde-3a84-49ff-a457-9476a2da8a2a.png)|

If I understand correctly, the lib is supposed to get the insets values directly from the platform. So this should work out of the box for new devices right ? So there might be another issue here ? (Or maybe iOS14 "did an Android 12" 😅 Which wasn't returning the correct value for the top bar height..)

Thanks in advance for any insight on the issue !

**Comment by bombillazo** [comment]
Can confirm, Top and Bottom edges are no longer detected and the content is flush to the edges.

**Comment by brentvatne** [comment]
hi there! can you explain how to reproduce this? this appears to work as expected for me

![image](https://user-images.githubusercontent.com/90494/190519451-4826cc54-0042-4bea-b727-47cc18c8fc50.png)

source code:

```
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

function App() {
  const insets = useSafeAreaInsets();
  return (
    <SafeAreaView style={styles.container}>
      <View style={{ flex: 1, backgroundColor: '#eee' }}>
        <Text>{JSON.stringify(insets)}</Text>
      </View>
    </SafeAreaView>
  );
}

export default function AppContainer() {
  return (
    <SafeAreaProvider>
      <App />
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
});
```

**Comment by Bob-JZhao** [comment]
@brentvatne I guess if the app is using react-navigation lib, you would see the issue. Sorry I don't have an demo project for showing the issue, but our project is having this issue, on iPhone 14 pro, the left drawer and screen title is covered by the island area.

**Comment by julienR2** [comment]
Oh I can confirm that we are also using `react-navigation` lib.. Mm I though they were also using `react-native-safe-area-context` to setup the safe area view...

I'll keep on investigate too and share more details once I'm sure of the source of the issue

**Comment by rossjohnsonMP** [comment]
If its any help at all we had this same issue 2 years ago and upgrading from 3.1.7 -> 3.1.8 fixed it, I took a quick look at the release notes of 3.1.8 and there was no mention of anything relating to fixing the latest iPhones

**Comment by brentvatne** [comment]
old versions of react-navigation may not use react-native-safe-area-context; this library was partially motivated by a need to solve for the issues we encountered in react-navigation around safe areas. it sounds like there are not actually any issues with this library itself and rather just with old versions of react-navigation. please update to a new version of that library.

**Comment by julienR2** [comment]
@brentvatne Thanks for the sum up 👍  We're on it !

Definitely worth closing it ! I'll re-open a ticket with more info if we still face the issue after the migration to the latest version.

**Comment by quangtuan28200** [comment]
> hi there! can you explain how to reproduce this? this appears to work as expected for me
> 
> ![image](https://user-images.githubusercontent.com/90494/190519451-4826cc54-0042-4bea-b727-47cc18c8fc50.png)
> 
> source code:
> 
> ```js
> import { StyleSheet, Text, View } from 'react-native';
> import { SafeAreaProvider, SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
> 
> function App() {
>   const insets = useSafeAreaInsets();
>   return (
>     <SafeAreaView style={styles.container}>
>       <View style={{ flex: 1, backgroundColor: '#eee' }}>
>         <Text>{JSON.stringify(insets)}</Text>
>       </View>
>     </SafeAreaView>
>   );
> }
> 
> export default function AppContainer() {
>   return (
>     <SafeAreaProvider>
>       <App />
>     </SafeAreaProvider>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#fff',
>     justifyContent: 'center',
>   },
> });
> ```

weird, why my top inset is 44, tested with both iphone 14 pro and 15, when I use DeviceInfo.hasDynamicIsland() of react-native-device-info, it always returns false.
