### ISSUE TITLE
Package react-native-safe-area-context contains invalid configuration: "dependency.platforms.android.libraryName" is not allowed

### ISSUE THREAD

**Issue by codewitharun** [th3rdwave/react-native-safe-area-context#314]
warn Package react-native-safe-area-context contains invalid configuration: "dependency.platforms.android.libraryName" is not allowed,"dependency.platforms.android.componentDescriptors" is not allowed,"dependency.platforms.android.cmakeListsPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by rborn** [comment]
yes it is ❤️

**Comment by KrisLau** [comment]
@janicduplessis @rborn I'm still getting this in 4.4.1

**Comment by my-name-is-nheo** [comment]
@janicduplessis using RN -v 0.67.5, safe-area -v 4.4.1 and still seeing this error. Using Pnpm as well

**Comment by rukmanary** [comment]
> This should be fixed in 4.4.1

I'm getting this error in 4.11.0
