### ISSUE TITLE
Bottom navigation bar height

### ISSUE THREAD

**Issue by Rapsssito** [th3rdwave/react-native-safe-area-context#32]
Following my previous [PR at react-native-device-info](https://github.com/react-native-community/react-native-device-info/pull/914), I tried to create a method called **`getBottomNavigationBarHeight()`** in this library that returns the bottom navigation bar height.

However, I am not familiar with React Hooks and I couldn't get it to work. I wanted to ask if that method would make sense in this library and if there is a way to integrate it with the current API.

**Comment by Rapsssito** [comment]
Probably related to #30

**Comment by adkenyon** [comment]
Not a maintainer but having the status bar height would be helpful

**Comment by janicduplessis** [comment]
I don't plan on adding methods specific to certain UI elements. This library abstracts away which system UI is over a view, this is also how native apis work.
