### ISSUE TITLE
Screen not filled

### ISSUE THREAD

**Issue by s-chillo** [th3rdwave/react-native-safe-area-context#320]
Hi 

I followed the tutoriel.
As shown on my image i still have blue bar.

Please what am i missing
![Screenshot_20221009_155952](https://user-images.githubusercontent.com/698056/194761370-ec72f837-e4b0-425c-a82e-1cab288a0762.jpg)

Thanks

**Comment by jacobp100** [comment]
There's not enough information to help you here
