### ISSUE TITLE
WindowInsets.getRoundedCorner ja possible?

### ISSUE THREAD

**Issue by KULTI1995** [th3rdwave/react-native-safe-area-context#321]
Can the library get WindowInsets.getRoundedCorner (int position)?
https://developer.android.com/develop/ui/views/theming/rounded-corners

Useful for e.g. introducing routing transition animations with rounded view edges. If it is possible to obtain these values with this library?

**Comment by janicduplessis** [comment]
It is not currently implemented, but it could be possible to add there values.

**Comment by KULTI1995** [comment]
> It is not currently implemented, but it could be possible to add there values.

how to do it?

**Comment by janicduplessis** [comment]
This library might also be a better option if you are willing to contribute the android implementation. https://github.com/mrousavy/react-native-screen-corner-radius/blob/master/README.md

**Comment by jacobp100** [comment]
Agree - it's only a well defined thing on iOS, makes sense to have an iOS-only library handle this

**Comment by jacobp100** [comment]
I'll close this unless someone feels very strongly it should be in *this* library
