### ISSUE TITLE
Support for XCODE 14 & Android November deadline

### ISSUE THREAD

**Issue by dwkd** [th3rdwave/react-native-safe-area-context#322]
Can we get a compatiblity update for iOS and Android new deployment target requirements:

- XCode 14 requires [IPHONEOS_DEPLOYMENT_TARGET >= 11](https://developer.apple.com/support/xcode)
- Android has a [November deadline for targetSdkVersion of 31](https://developer.android.com/google/play/requirements/target-sdk?authuser=1)

Thank you

**Comment by danidaryaweesh** [comment]
@dwkd I was able to get this library to work with Xcode 14 and Android SDK 31. Make sure to upgrade to RN 0.68.4 and you will be fine.

**Comment by dwkd** [comment]
ok seems to be working, thank you
