### ISSUE TITLE
[BUG]: The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher

### ISSUE THREAD

**Issue by fabio-nettis** [th3rdwave/react-native-safe-area-context#325]
## Description

After upgrading to react-native 0.70.4 I am receiving following error when trying to build the project.

```bash
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-safe-area-context' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10
```

## Setup

- **node**: 18.11.0
- **react-native**: 0.70.4
- **react-native-gradle-plugin**: ^0.71.4
- **react-native-save-area-context**: ^4.3.1

## Additional Context

This might also be related to issue: #300

**Comment by kiroskirin** [comment]
I also face the same issue.

**Comment by mohanagy** [comment]
as a workaround, 
go to react-native-safe-area-context/android/gradle.properties
and change the version from 1.6.10 to 1.6.12

**Comment by Schoonmoeder** [comment]
if you use node modules this requires a patch that is not handy.
I solved this for react-native with this
`buildscript {
    ext {
        kotlinVersion = '1.6.20' // fix for react-native-safe-area-context (4.4.1) forcing kotlinVersion `

in <app>/android/build.gradle

**Comment by FerMoreno17** [comment]
I also face with it. I tried @Schoonmoeder solution but it not works for me. Similar setup to the one above. Any solution?

**Comment by Sid-Turner-Ellis** [comment]
@FerMoreno17 Use [patch-package](https://www.npmjs.com/package/patch-package) and follow Mohanagy's advice to edit the kotlin version to whatever is required by your project.

I was getting an error that required 1.6.20 but one of my dependencies was using 1.5.x so:
```
// node_modules/package/android/gradle.properties

// RNSAC_kotlinVersion=1.6.10 remove the original
+RNSAC_kotlinVersion=1.6.20 // add the version I needed
```

then run `npx patch-package react-native-safe-area-context` to persist the changes
