### ISSUE TITLE
Bottom is too high

### ISSUE THREAD

**Issue by shop-fluencer** [th3rdwave/react-native-safe-area-context#326]
Hello,

why is the bottom to high ? how can I fix it that the bottom is not too high ?

![bottt](https://user-images.githubusercontent.com/101994056/200346514-49336a3f-378c-4b74-9ff2-974143fd2a23.PNG)

**Comment by victoriaSh** [comment]
Same issue. 
![IMG_5135](https://user-images.githubusercontent.com/8823284/206868698-4a9a56b4-ce3d-4993-8a19-e4075b391723.jpg)

My SafeAreaView is inside Tab->Stack view because at some Stack views I don't need SafeAreaView.
I ended up with temporary solution to switch off the bottom edge:
```
<SafeAreaView style={{flex: 1}} edges={['right', 'top', 'left']}>
  <ScrollView>
    ...
  </ScrollView>
</SafeAreaView>
```

**Comment by jacobp100** [comment]
There's not enough code to identify your issue (I'm assuming the tab bar isn't in the ScrollView).

**Comment by jacobp100** [comment]
Feel free to comment if you have further issues
