### ISSUE TITLE
How to get the actual insets.top on iPhone with dynamic island

### ISSUE THREAD

**Issue by nmeibergen** [th3rdwave/react-native-safe-area-context#327]
As can be seen in [this](https://github.com/th3rdwave/react-native-safe-area-context/issues/310#issuecomment-1248697755) comment, the `insets.top` value is found to be 59. However the absolute distance between the top of the screen and the top of the `<View>` inside the `<SafeAreaView>`, is clearly larger. 

**My question is twofold**
1. What exactly is 59 referring to?
2. How would we retrieve the actual distance from the top of the screen to this inner view using a hook?

**Comment by jacobp100** [comment]
https://medium.com/rosberryapps/ios-safe-area-ca10e919526f - does this help?

**Comment by jacobp100** [comment]
Feel free to continue discussion here if you're stuck. Closing to clean up issues tab
