### ISSUE TITLE
How do the insets from this lib differ from RN's SafeAreaView padding?

### ISSUE THREAD

**Issue by eighty4** [th3rdwave/react-native-safe-area-context#329]
I'm seeing different height calculations between emulated devices, a modern Android phone and older Android phones. The older Android phones cause my calculated Y positioning to be vertically out of place. When I create an emulated device of the same screen and older OS version, everything looks okay. Emulated devices and modern phones, regardless of OS and screen/window specs, always look great.

I was able to create an app that uses `Dimensions.get('window').height`, `Dimensions.get('screen').height` and `height: '100%'` to get drastically different results, where neither window nor screen matches the 100% rendered height. Where do these values come from and will they be different or more consistent if I use a custom Android/iOS API (like your library) to get dimensions?

![img](https://user-images.githubusercontent.com/50251875/202051058-eaa5679a-2622-4e64-be7a-a94c9bf96d96.png)

I can't figure out why the following code creates three different shaped boxes, as well as why they're not being centered vertically correctly.

```
() => {
    const containerStyle = {flex: 1, flexDirection: 'row', justifyContent: 'space-between'}
    const boxStyles = {width: '30%', transform: [{scaleY: .5}], alignItems: 'center', justifyContent: 'center', padding: 20}
    const textStyles = {color: '#000', fontSize: 20, lineHeight: 28}

    return (
        <View style={containerStyle}>
            <View style={{...boxStyles, backgroundColor: 'purple', height: '100%', }}>
                <Text style={textStyles}>height 100%</Text>
            </View>
            <View style={{...boxStyles, backgroundColor: 'blue', height: Dimensions.get('window').height}}>
                <Text style={textStyles}>window height</Text>
            </View>
            <View style={{...boxStyles, backgroundColor: 'red', height: Dimensions.get('screen').height}}>
                <Text style={textStyles}>screen height</Text>
            </View>
        </View>
    );
};
```

**Comment by jacobp100** [comment]
Not sure if I get the full question - but [on standard RN Android, SAV is just View](https://github.com/facebook/react-native/blob/0c150b2289818267c940b6e726ec2f7725659817/Libraries/Components/SafeAreaView/SafeAreaView.js#L29)
