### ISSUE TITLE
ios 16 useSafeAreaInsets return 0 from bottom and all other sides.

### ISSUE THREAD

**Issue by iim-norse** [th3rdwave/react-native-safe-area-context#330]
Do anyone have same problem ?

**Comment by jacobp100** [comment]
You need to use [SafeAreaProvider](https://github.com/th3rdwave/react-native-safe-area-context#safeareaprovider)

**Comment by iim-norse** [comment]
I used it. But seems now its resolved (I dont remember what i did)
