### ISSUE TITLE
RNCSafeAreaViewState.h:31:18: Variable has incomplete type 'class JSI_EXPORT'

### ISSUE THREAD

**Issue by MikePendo** [th3rdwave/react-native-safe-area-context#336]
I receive the following issue:

`RNCSafeAreaViewState.h:31:18: Variable has incomplete type 'class JSI_EXPORT'`
With 
react-native-safe-area-context@4.4.1
While trying the new arch 
Please help

**Comment by aryanm5** [comment]
I am also experiencing this issue. It was working on RN 0.70.6 without the New Arch enabled, but once I enabled it this error started occurring.

**Comment by jacobp100** [comment]
Platform?

**Comment by aryanm5** [comment]
> Platform?

Building for iOS on an Intel chip Mac.

**Comment by ravikumarhb** [comment]
any update on this ? i have the same issue too 0.70 RN .. new arch enabled on iOS..  "react-native-safe-area-context":"^4.2.5"

mobileapp/node_modules/react-native-safe-area-context/common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewState.h:31:18 Variable has incomplete type 'class JSI_EXPORT'

**Comment by jacobp100** [comment]
I don’t think we support 0.70 on the new architecture

**Comment by ravikumarhb** [comment]
can you please share which RN version and which Safe-area-context are compatible for new arch support ( stable ones ).
I was under the assumption that below statement is fine.

"New architecture support
This library currently has experimental support for the new react-native architecture. Note that there will be breaking changes and only the latest version of react-native will be supported.

You will need to be on 4.4.0 and react-native 0.70+."

**Comment by jacobp100** [comment]
Think that might be out of date. It's experimental support for an experimental architecture. I don't think any of the current maintainers are looking at fixing new arch issues, but I'm happy to look at PRs that fix these issues

**Comment by jacobp100** [comment]
Closing because RN is on 0.72 and we probably won't backport new arch fixes for older versions
