### ISSUE TITLE
Unable to find a specification for `React-RCTFabric` depended upon by `react-native-safe-area-context/fabric` for react-native 0.71.0

### ISSUE THREAD

**Issue by ko-devHong** [th3rdwave/react-native-safe-area-context#346]
After raising the react-native version to 0.71.0, the following occurs:

![스크린샷 2023-01-19 오전 10 51 07](https://user-images.githubusercontent.com/45538347/213336840-0b0ddf70-c4d4-4fd8-bdd5-470f55939072.png)

**Comment by jacobp100** [comment]
Are you running `bundle exec pod install` in your `ios` folder?

**Comment by jacobp100** [comment]
Closing because it's not a library issue - but you are welcome to continue to ask questions in this thread

**Comment by scrungrth** [comment]
I had to update react-native-safe-area-context to latest after doing RN 71 upgrade to fix this.
