### ISSUE TITLE
RN Android sources cause conflict on RN 0.71

### ISSUE THREAD

**Issue by ospfranco** [th3rdwave/react-native-safe-area-context#351]
I'm the creator of `react-native-quick-sqlite`, I recently [updated the package to support 0.71](https://github.com/ospfranco/react-native-quick-sqlite/pull/108) but it has major breaking changes. You can see on my PR here that the Android sources are no longer packaged inside the `/node_modules/react-native/android` directory and instead you have to use a namespace to be able to link the code.

![CleanShot 2023-01-21 at 14 17 19](https://user-images.githubusercontent.com/1634213/213868816-026918cb-cc7f-474f-a30e-8a35e9cff5ca.png)

As far as I understand the problem is that `safe-area-context` still tries to import the old sources, and it clashes with the new namespaces of 0.71 causing [a class duplication error](https://github.com/ospfranco/react-native-quick-sqlite/pull/108#issuecomment-1399235435).

I'm not an android expert and maybe there is a way to resolve this. But just want to confirm my suspicions are correct.

**Comment by simonkoeck** [comment]
Have you found a fix or a workaround?

**Comment by ospfranco** [comment]
ah yeah, this has nothing to do with this package, but rather re-importing the gradle plugin from react. All 0.71 packages need to update their gradle scripts to the correct configuration. Don't ask me which one is the correct one, I basically stumbled and copied it until it worked.
