### ISSUE TITLE
Build issue with Xcode 14

### ISSUE THREAD

**Issue by saqlainrasheed** [th3rdwave/react-native-safe-area-context#356]
I'm facing following issue while build new React-native project through Xcode 14.

App works fine when I build from terminal and I tried re-installing package and clearing npm cache 

![test](https://user-images.githubusercontent.com/41280524/220429106-0f1e818a-402a-4bd1-8997-4feb9173ddad.png)

**Comment by jacobp100** [comment]
Make sure you run `bundle exec pod install` and clean the build folder before building

Definitely works in Xcode 14 for me

**Comment by saqlainrasheed** [comment]
Thanks for responding @jacobp100, unfortunately I'm still not able to run this project directly from Xcode, although I am able to run it from command line.

I think it's an issue with my project or something else because I tried removing `react-native-area-view-context` from my project and at that time it threw a same error for another library.

**Comment by saqlainrasheed** [comment]
I am finally able to fix this issue by updating all the packages to their latest versions.
