### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RCTView

### ISSUE THREAD

**Issue by deepakdangi** [th3rdwave/react-native-safe-area-context#357]
**Package.json**

{
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  },
  "name": "******",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/cli-platform-android": "^4.10.0",
    "@react-native-community/netinfo": "^4.7.0",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "accordion-collapse-react-native": "^0.3.1",
    "axios": "^0.19.0",
    "native-base": "^2.13.8",
    "patch-package": "^6.4.7",
    "react": "16.9.0",
    "react-country-region-selector": "^3.4.0",
    "react-native": "^0.62.2",
    "react-native-alphabetlistview": "^0.3.1",
    "react-native-base64": "^0.1.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-contacts": "^5.0.2",
    "react-native-device-info": "^5.3.1",
    "react-native-drag-drop-and-swap": "^0.1.6",
    "react-native-easy-grid": "^0.2.2",
    "react-native-elements": "^1.2.7",
    "react-native-firebase": "^5.5.6",
    "react-native-gesture-handler": "^1.5.1",
    "react-native-get-sms-android": "^2.0.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-modal": "^11.5.3",
    "react-native-permissions": "^2.1.5",
    "react-native-popup-menu": "^0.15.10",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.9.0",
    "react-native-webview": "^7.5.1",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "rn-fetch-blob": "^0.11.2"
  },
  "devDependencies": {
    "@babel/core": "7.7.4",
    "@babel/runtime": "7.7.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.7.1",
    "jest": "24.9.0",
    "jetifier": "^1.6.8",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

I have been stuck in this for the past few days. I would appreciate any help.

**Comment by jacobp100** [comment]
You've got this package installed twice

If you're using yarn, run `yarn why react-native-safe-area-context` to see why it's happening. If you're using npm, may the odds ever be in your favour
