### ISSUE TITLE
Missing types for react-native-safe-area-context/jest/mock

### ISSUE THREAD

**Issue by Shahaed** [th3rdwave/react-native-safe-area-context#358]
There are no types for this file so Typescript complains when trying to import it.

**Comment by jacobp100** [comment]
If you figure out the issue I’d be happy to take a look at a PR

**Comment by Shahaed** [comment]
This file: [jest/mock.js](https://github.com/th3rdwave/react-native-safe-area-context/blob/main/jest/mock.js) just needs to be typed. The folder` jest` can be added to the tsconfig https://github.com/th3rdwave/react-native-safe-area-context/blob/cdcde441a8166ef6d9956bb5baa51fe4e2fb5d2d/tsconfig.json#L24 and the file can be rewritten in typescript or an adjacent mock.d.ts can be put there.

**Comment by tarunrajput** [comment]
closed by https://github.com/th3rdwave/react-native-safe-area-context/pull/390
