### ISSUE TITLE
Top inset wrong when using hidden StatusBar in IOS

### ISSUE THREAD

**Issue by tafkanator** [th3rdwave/react-native-safe-area-context#36]
When using `<StatusBar hidden />` in IOS, top inset is 20 instead of 0. It corrects itself after device is rotated to landscape and back.

https://snack.expo.io/SkroOuDAS

Tested phones:
  * iPhone 7 IOS 13.3 (has bug)
  * iPhone X IOS 13.3 (does not have bug)
  * various Android devices (does not have bug)

**Comment by janicduplessis** [comment]
Duplicate #23
