### ISSUE TITLE
Safe area context irrelevant (not needed anymore)

### ISSUE THREAD

**Issue by rcfrias** [th3rdwave/react-native-safe-area-context#367]
What is the point of using -> SafeAreaProvider ?, I recently used the included SafeAreaView without issues. Not sure why we need an extra tag for this?

**Comment by jacobp100** [comment]
it’s needed for iOS

**Comment by rcfrias** [comment]
What do you mean its needed for iOS, this was done without SafeAreaProvider
(SafeAreaView with blue background)
<img width="380" alt="image" src="https://user-images.githubusercontent.com/928112/226739499-7f7adb73-52b0-4f2c-b7ec-240f8133f9b4.png">

**Comment by jacobp100** [comment]
Looks like a bug. Can you share the code?

**Comment by jacobp100** [comment]
I'm going to close this, but if you're certain there's a bug, please share some code
