### ISSUE TITLE
useSafeAreaInsets() position doesn't detect non-notched screen

### ISSUE THREAD

**Issue by soemarko** [th3rdwave/react-native-safe-area-context#371]
<img width="833" alt="Screenshot 2023-04-04 at 5 43 43 pm" src="https://user-images.githubusercontent.com/381585/229769817-b7e25ba2-a176-4f86-ac54-2050567b70bd.png">

Ideally both should be around the top of the screen.

**Comment by jacobp100** [comment]
We give you what iOS returns. Ok non-notched screens it gives you the height of the status bar (20px normally, 40px during a phone call)
