### ISSUE TITLE
Expo example app

### ISSUE THREAD

**Issue by antoine-cottineau** [th3rdwave/react-native-safe-area-context#381]
Hi and thanks for the package, it's really useful!

`CONTRIBUTING.md` mentions that it is possible to run an Expo version of the example app by running `yarn example:expo` (see [here](https://github.com/th3rdwave/react-native-safe-area-context/blob/main/CONTRIBUTING.md#expo-and-web))

However, the example app isn't an Expo app; it doesn't even have `expo` as a dependency.

Should we either simplify `CONTRIBUTING.md` or implement an example Expo app?

**Comment by jacobp100** [comment]
Maybe we should remove the reference to this. I’m not sure how important it is that we show it working on expo
