### ISSUE TITLE
Could not find react-native-0.71.0-rc.0-debug.aar

### ISSUE THREAD

**Issue by coucoseth** [th3rdwave/react-native-safe-area-context#384]
I installed this package and my android app is not compiling, i get the following response

Execution failed for task ':react-native-safe-area-context:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-safe-area-context:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-debug.aar

**Comment by jacobp100** [comment]
Is this still an issue?

**Comment by coucoseth** [comment]
thanks @bang9 
no it is not @jacobp100 , let me go ahead and close it
