### ISSUE TITLE
Solve build issue with gradle >8.0

### ISSUE THREAD

**Issue by mlopezscrm** [th3rdwave/react-native-safe-area-context#397]
Hi, if u are having problems with gradle 8.0 just use this patch and problem solved.

    diff --git a/android/build.gradle b/android/build.gradle
    index 448140f6b54523ebd142bf695f47446fbb11085b..890015d8ee2359b57794a2489871f88600f1e7bd 100644
    --- a/android/build.gradle
    +++ b/android/build.gradle
    @@ -30,6 +30,7 @@ if (isNewArchitectureEnabled()) {
     }
     
     android {
    +    namespace = "com.th3rdwave.safeareacontext"
         compileSdkVersion getExtOrDefault('compileSdkVersion', 30)
     
       // Used to override the NDK path/version on internal CI or by allowing

**Comment by janicduplessis** [comment]
Should be fixed in last version

**Comment by durejagaurav** [comment]
A problem occurred configuring project ':react-native-safe-area-context'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.api.GradleException: Adding a Configuration as a dependency is no longer allowed as of Gradle 8.0.
   > KotlinJvmAndroidCompilation with name 'debug' not found.
   
   
   Please help me solve this.

**Comment by durejagaurav** [comment]
Patch also not working

**Comment by mlopezz1** [comment]
This is not related with the same, can u post ur build gradle? And also app/build.gradle
