### ISSUE TITLE
Violation: requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager.

### ISSUE THREAD

**Issue by brunolemos** [th3rdwave/react-native-safe-area-context#4]
I believe I linked the lib correctly but it still doesn't find `RNCSafeAreaView`. Using RN 0.59.x.

```
[error][tid:com.facebook.react.JavaScript] Invariant Violation: requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager.
    in RNCSafeAreaView (at src/index.tsx:19)
```

![image](https://user-images.githubusercontent.com/619186/63961105-569b3d00-ca66-11e9-8023-605cd9e059a5.png)

![image](https://user-images.githubusercontent.com/619186/63961123-5d29b480-ca66-11e9-8669-50c2b9a31af0.png)

![image](https://user-images.githubusercontent.com/619186/63961147-703c8480-ca66-11e9-8a18-9564a85fb6c1.png)

**Comment by janicduplessis** [comment]
@brentvatne do you think it has to do with e6accf2? The dep should def not be called RNCNetInfo.

**Comment by tvler** [comment]
Same issue here

**Comment by janicduplessis** [comment]
@brunolemos @tvler Could you try v0.3.4? You might have to relink the library since we made changes to the xcodeproj.

**Comment by tvler** [comment]
Still not working :/

I wonder if there's another step we need to do manually linking this particular library that isn't documented here https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

**Comment by janicduplessis** [comment]
@tvler Alright, sorry about that. I'll try to setup a project with libraries linking to test it out (the example in the repo uses pods and I also do in my apps).

**Comment by tvler** [comment]
Thanks!

**Comment by brunolemos** [comment]
I was able to fix it by adding these two missing files to the project:

![image](https://user-images.githubusercontent.com/619186/64038613-d7be0700-cb2e-11e9-80d5-520623c21362.png)


Opened #6.

**Comment by Alaaeldin1993** [comment]
any update ?? i am having this problem

**Comment by Alaaeldin1993** [comment]
for me i have followed this link to solve the problem : https://github.com/th3rdwave/react-native-safe-area-context

**Comment by aacassandra** [comment]
Step to resolve

-Stop the current running Metro Bundler

-install pod for ios

-try re-run the application

Hope this will help !

**Comment by falquinho** [comment]
I had this problem on android after ejecting from expo. Solution was to "react-native link" as instructed in the link provided by @Alaaeldin1993

**Comment by Katanis** [comment]
Manualy linking helped me:
`react-native link react-native-safe-area-context`

**Comment by Devslops** [comment]
> 
> 
> Manualy linking helped me:
> `react-native link react-native-safe-area-context`

Thanks ! 

(if the command react-native not found, execute this command : npm i -g react-native-cli then execute react-native link react-native-safe-area-context !)

**Comment by ahsan-khan1999** [comment]
same issue!

**Comment by ishaqashraf** [comment]
same issue

**Comment by manukastratta** [comment]
Same issue!

**Comment by nateblog** [comment]
Linking the package fixed it via pods

**Comment by RUANDUARTE03** [comment]
Same issue

**Comment by AdiYElisha** [comment]
does not work for me. I use expo. got any idea?

**Comment by Katanis** [comment]
Did you try to build project on androidstudio?
It sometimes solves problems.

**Comment by swushnard** [comment]
Doesnt work . I use Expo and the ui-kitten. i might have same problem with AdiYelisha

**Comment by janicduplessis** [comment]
If using expo make sure to use version 0.7.

**Comment by saradindu** [comment]
> does not work for me. I use expo, and running on android emulator. got any idea?

running below command solved my issue
`expo add react-native-safe-area-context`

**Comment by DagleAnderson** [comment]
basta seguir os passos do site oficial do react navigation  [](https://reactnavigation.org/docs/getting-started/)  que vai funcionar na maioria dos casos. Vlw!

**Comment by manamalani10** [comment]
see the package.json file if it contains the dependecies mentioned mine did'nt otherwise try uninstalling and reinstalling all this helped me.

**Comment by rahuldasgupta24** [comment]
> > does not work for me. I use expo, and running on android emulator. got any idea?
> 
> running below command solved my issue
> `expo add react-native-safe-area-context`

It worked for me, thanks!

**Comment by amit00978** [comment]
> > does not work for me. I use expo, and running on android emulator. got any idea?
> 
> running below command solved my issue
> `expo add react-native-safe-area-context`

It's work for me.

**Comment by arthedza** [comment]
Check out that you've got `new SafeAreaContextPackage()` in MainApplication.java
