### ISSUE TITLE
How to set different background color for bottom and top safe area? 

### ISSUE THREAD

**Issue by panda0603** [th3rdwave/react-native-safe-area-context#40]
I have tried 
```
<View style={{flex:1}}>
   <SafeAreaView style={{flex: 0, backgroundColor: 'white'}}/>
   <SafeAreaView style={{flex: 1, backgroundColor: 'grey'}}>
       ...
   </SafeAreaView>
</View>

```
doesn't work. How would I set different colors for bottom and top?

**Comment by Volekss** [comment]
@panda0603 was you able to find anything over this time?

**Comment by Volekss** [comment]
I managed to fix this by wrapping the whole component into `<SafeAreaView>` and setting `paddingTop: 0`. And also wrapping the most top component into another `<SafeAreaView>` and setting it's color to the one I want to be on the top.
```
<SafeAreaView
            style={{ flex: 1, backgroundColor: 'grey', paddingTop: 0 }}>
            <SafeAreaView style={{ flex: 1, backgroundColor: 'white', paddingBottom: 0 }}>
                <View/>
            </SafeAreaView>
                <View/>
 </SafeAreaView>
```

**Comment by satya164** [comment]
just use `useSafeArea` hook directly for advanced usage. `SafeAreaView` is for basic usage where you just need to apply safe area insets on a view.
