### ISSUE TITLE
[4.6.0] missing types

### ISSUE THREAD

**Issue by efstathiosntonas** [th3rdwave/react-native-safe-area-context#401]
Latest release `4.6.0` is missing types.

![Screenshot 2023-06-21 at 09 59 27](https://github.com/th3rdwave/react-native-safe-area-context/assets/717975/08f8c23a-fa3e-4016-b2ac-addfbf3f8c61)

**Comment by efstathiosntonas** [comment]
For some reason it imports from commonjs folder instead of typescript one 🤔 , at least that's where IntelliJ is taking me when I middle click the import.

**Comment by chj-damon** [comment]
I'm facing the same issue.

**Comment by efstathiosntonas** [comment]
This line: https://github.com/th3rdwave/react-native-safe-area-context/blob/b8b1e8e4ab5e9ca4901ca04d21dd4a000a424ab1/package.json#L8

should be: 
```json
  "types": "lib/typescript/src/index.d.ts",
```

it seems `bob-builder` messed up somehow?

**Comment by jacobp100** [comment]
Fixed in #400

**Comment by efstathiosntonas** [comment]
thanks @jacobp100

**Comment by efstathiosntonas** [comment]
patch just in case someone can't wait for a release:

`react-native-safe-area-context+4.6.0.patch`

```diff
diff --git a/node_modules/react-native-safe-area-context/package.json b/node_modules/react-native-safe-area-context/package.json
index 68f30e6..db9bdfe 100644
--- a/node_modules/react-native-safe-area-context/package.json
+++ b/node_modules/react-native-safe-area-context/package.json
@@ -5,7 +5,7 @@
   "main": "lib/commonjs/index.js",
   "module": "lib/module/index.js",
   "react-native": "src/index.tsx",
-  "types": "lib/typescript/index.d.ts",
+  "types": "lib/typescript/src/index.d.ts",
   "source": "src/index.tsx",
   "sideEffects": false,
   "files": [
```
