### ISSUE TITLE
Height from useSafeAreaFrame doesn't seem to be accurate 

### ISSUE THREAD

**Issue by grid-dres** [th3rdwave/react-native-safe-area-context#405]
Stack - 

react-native: 0.69.7
react-native-safe-area-context: 4.4.1

Expected Behavior - 

`const {height} = useSafeAreaFrame()` should work as an alternative to the Dimensions module. Having a modal animation that tells the view component to move the the y position below the frame should work as expected. 

Actual Behavior -
Users on Android (Specifically Pixel devices) are reporting that the bottom area of the screen is un-tappable. When debugging, we noticed that a global component wasn't animating below the frame as expected. 

Code - 
```
export function useLoadingPanelAnimation() {
  const { height: SCREEN_HEIGHT } = useSafeAreaFrame();

  const yPos = useSharedValue(SCREEN_HEIGHT);
  const opacity = useSharedValue(0);
  const { visible } = useSelector(({ state }) => state.placeholder);

  const animationStyle = useAnimatedStyle(() => {
    return {
      opacity: withTiming(opacity.value, {
        duration: TRANSITION_DURATION / 2,
      }),
      transform: [
        {
          translateY: withTiming(yPos.value, {
            duration: TRANSITION_DURATION,
          }),
        },
      ],
    };
  });

  useEffect(
    function () {
      if (visible) {
        yPos.value = 0;
        opacity.value = 1;
      } else {
        yPos.value = SCREEN_HEIGHT;
        opacity.value = 0;
      }
    },
    [visible],
  );

  return { animationStyle };
}
```

- where the yPos.value is being set to the screen height, the component does not actually go below the frame as expected. As mentioned above, this is an issue we do not see on android emulators, physical samsung galaxy s9 device, and any iOS device. This only impacts Pixel Devices (6a, 7, and 7Pro).
---
If I add the top inset value along with the height, this works as well. 
```
const { top } = useSafeAreaInsets()
const {height} = useSafeAreaFrame()
const ACTUAL_HEIGHT = top + height
```

Is there a recommended solution to using height from this hook? I'd love to use this as an alternative to the Dimensions module as I've heard this library is more accurate, but I want to make sure I'm using this correctly.

Thanks!

**Comment by jacobp100** [comment]
> should work as an alternative to the Dimensions module

Not quite - it’s the frame inside the safe area

**Comment by jacobp100** [comment]
Closing but you’re welcome to ask further questions
