### ISSUE TITLE
[suggestion] Specify OS in configuration

### ISSUE THREAD

**Issue by calebpanza** [th3rdwave/react-native-safe-area-context#406]
With Apple's `modal` taking the SafeArea into account, I often find myself negating the `SafeAreaView` component only to later find out that my Android users are getting their content chopped off!

Given that `edges` already allows an array of configuration values, I would love to be able to pass in an array called `os` (or something of the sort) in order to specify that configuration is only for a specific set of OS's.

For example:

```
edges={[
   {
      top: "off",
      os: ['ios']
   },
   {
      top: "additive",
      os: ['android']
   },
]}
```

**Comment by jacobp100** [comment]
Use Platform.select from react native

**Comment by jacobp100** [comment]
https://reactnative.dev/docs/platform#select
