### ISSUE TITLE
IOS New arch issue RN 0.72.1 error on latest

### ISSUE THREAD

**Issue by billnbell** [th3rdwave/react-native-safe-area-context#408]
"react-native-safe-area-context": "^4.6.3"

Cannot find #include <react/utils/ContextContainer.h> from PropsParserContext.h

**Comment by jacobp100** [comment]
I don’t believe any of the maintainers are using the new arch, so it’s unlikely we’ll get around to fixing this. If you’re able to send a PR it would really help

**Comment by billnbell** [comment]
```
Compiling RNCSafeAreaViewState.cpp

❌  /Users/bill_1/Library/Developer/Xcode/DerivedData/TheClub-cdrjlnanozvjbucvomcedfhcjajw/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/core/PropsParserContext.h:11:10: 'react/utils/ContextContainer.h' file not found

#include <react/utils/ContextContainer.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


▸ Compiling RNCSafeAreaViewShadowNode.cpp

❌  /Users/bill_1/Library/Developer/Xcode/DerivedData/TheClub-cdrjlnanozvjbucvomcedfhcjajw/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/debug/flags.h:10:10: 'react/debug/flags.h' file not found

#include <react/debug/flags.h>
         ^~~~~~~~~~~~~~~~~~~~~


```

I am looking into it.

**Comment by billnbell** [comment]
OK I found the solution. See https://reactnative.dev/docs/the-new-architecture/backward-compatibility-turbomodules

Add install_modules_dependencies(s) in your pod spec per that link, and it fixes it.

**Comment by LimitedDani** [comment]
> OK I found the solution. See https://reactnative.dev/docs/the-new-architecture/backward-compatibility-turbomodules
> 
> Add install_modules_dependencies(s) in your pod spec per that link, and it fixes it.

its added in the 4.7.0 version

**Comment by LimitedDani** [comment]
> Could someone confirm if this is fixed?

its already fixed
