### ISSUE TITLE
RN 0.72.1 giving me linking error in IOS

### ISSUE THREAD

**Issue by billnbell** [th3rdwave/react-native-safe-area-context#410]
```
Undefined symbol: _RNCSafeAreaViewCls
Undefined symbol: _RNCSafeAreaProviderCls
```

No idea how to fix this in the Podspec. Thoughts?

**Comment by jacobp100** [comment]
There’s not enough information to help. Try clearing your build folder or something

**Comment by billnbell** [comment]
I am clearing everything, and doing a simple build with use_frameworks!

```
RCT_NEW_ARCH_ENABLED=1 USE_FABRIC=1 pod install
yarn iOS
```

**Comment by jacobp100** [comment]
Open Xcode and do a clean that way. Think it's under the project menu

**Comment by billnbell** [comment]
Yeah after a reboot it worked. Weird.
