### ISSUE TITLE
Could not create task Kotlin

### ISSUE THREAD

**Issue by alperenkarip** [th3rdwave/react-native-safe-area-context#418]
Hello, there is a problem that I have been trying to solve for a long time, I tried to change the kotlin version and gradle versions, but it did not work. Can you help me ?

`    "react": "18.2.0",    "react-native": "0.72.2",`

>Execution failed for task ':tasks'. Could not create task ':react-native-safe-area-context:compileDebugAndroidTestKotlin'.
   > No enum constant org.jetbrains.kotlin.gradle.plugin.PropertiesProvider.JvmTargetValidationMode.WARNİNG
   
    "react-native-safe-area-context": "^4.7.1",

```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.0"
        androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

```

**Comment by umutazazi** [comment]
I also have the same problem, did  you can fix it ?

**Comment by obenlioglu** [comment]
I upgraded kotlin-gradle-plugin v1.6.0 to v1.9.0 in build.gradle file. This worked for me. 

`dependencies {
        ..
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"   // <--- THIS
        ..
}`

**Comment by umutazazi** [comment]
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0" 

Thank you, it is worked for me.

**Comment by alperenkarip** [comment]
thank you this worked for me @obenlioglu

**Comment by alperenkarip** [comment]
thank you this worked for me @obenlioglu

**Comment by sieta1** [comment]
> I upgraded kotlin-gradle-plugin v1.6.0 to v1.9.0 in build.gradle file. This worked for me.
> 
> `dependencies { .. classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0" // <--- THIS .. }`

worked for me too: location: android/build.gradle
dependencies {
classpath( "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")
`}`

**Comment by dcselek** [comment]
> I upgraded kotlin-gradle-plugin v1.6.0 to v1.9.0 in build.gradle file. This worked for me.
> 
> `dependencies { .. classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0" // <--- THIS .. }`

thanks for your solutions. worked for me.
