### ISSUE TITLE
Safe area is not respected on IOS 12

### ISSUE THREAD

**Issue by kodecreer** [th3rdwave/react-native-safe-area-context#433]
Just as the title says. Here is reproducible code for the issue.

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context'

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <Text>Hello, React Native!</Text>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Text is at the top and not respecting the safe area view with proper edge insets

**Comment by jacobp100** [comment]
iOS 12 is not supported by RN or this library

**Comment by kodecreer** [comment]
This is on IOS 16....

**Comment by jacobp100** [comment]
Your title says iOS 12 🤣

**Comment by jacobp100** [comment]
Your code example is missing stuff but make sure you’re also using the safe area provider
