### ISSUE TITLE
useSafeAreaInsets is not working well in iOS 17.0

### ISSUE THREAD

**Issue by Loh0809** [th3rdwave/react-native-safe-area-context#435]
I am using useSafeAreaInsets hook but it seems to be not working well in the latest iOS OS, 17.0. The safeAreaInsets.top is 59 but safeAreaInsets.bottom is 0 instead of 34, can you check on it?

**Comment by jacobp100** [comment]
Did you validate this with a blank project?

**Comment by Loh0809** [comment]
Hrmm...checked, the issue will only occurred when using this dependency with the [react-native-screenshot-prevent] dependency.

**Comment by jacobp100** [comment]
Alright. I’ll close this because it doesn’t look like there’s anything actionable but if you do find more information do leave a comment
