### ISSUE TITLE
SafeAreaView works in debug mode but not release in iOS

### ISSUE THREAD

**Issue by KylixMedusa** [th3rdwave/react-native-safe-area-context#436]
![Simulator Screenshot - iPhone 15 Pro - 2023-10-01 at 13 09 21](https://github.com/th3rdwave/react-native-safe-area-context/assets/56185721/abee1932-e6b4-43bf-b2e2-5ecf3a7561a9)

ios version: 17.0
library version: 4.7.2

While trying to run in debug mode, the app runs fine and the insets work perfectly, but while running a release build the safe area view doesn't work in iOS.
The library works perfectly fine on Android.

**Comment by KylixMedusa** [comment]
Was related to a peer library `react-native-screenshot-prevent`

**Comment by CherukuriSiva** [comment]
Can you please share details how did you fix the issue... Im facing similar issue but we are not using **react-native-screenshot-prevent** package. App working fine in debug mode but seeing some flickering in release mode.
