### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

### ISSUE THREAD

**Issue by ayanokoujifl** [th3rdwave/react-native-safe-area-context#438]
<h3>package.json</h3>
<pre>
Dependencies:
<code>
    "@gorhom/bottom-sheet": "^4.5.1",
    "expo": "^49.0.13",
    "expo-dev-client": "~0.8.6",
    "expo-font": "~10.0.4",
    "expo-location": "~14.0.1",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "12.1.1"
</code>
</pre>
<h3>App.jsx</h3>

```jsx
export default function App() {
  return (
     <SafeAreaProvider>
      <NativeBaseProvider>
        <Home />
      </NativeBaseProvider>
    </SafeAreaProvider>
  )
}

```
<p>
I have already made several changes related to the dependency versions. I thought it could be related to the native base, but apparently it is related to the safe area. Need help.
</p>
<h4>
Complete error:
</h4>
<p>
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

This error is located at:
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
</p>

**Comment by jacobp100** [comment]
Run the `pod install` step, then clean and rebuild the native code
