### ISSUE TITLE
Purpose on web?

### ISSUE THREAD

**Issue by Sir-hennihau** [th3rdwave/react-native-safe-area-context#450]
Hi,
I'm curious, what would be the purpose of this package to be on web?

Shouldn't browsers already handle content that is cut off at device status bars etc?

Sorry if this is a stupid question, but i really didn't find an answer that satisfies me yet.

**Comment by janicduplessis** [comment]
This explains it pretty well https://webkit.org/blog/7929/designing-websites-for-iphone-x/
