### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

### ISSUE THREAD

**Issue by khlling** [th3rdwave/react-native-safe-area-context#451]
Hi,

I'm trying to run my React Native project after upgrading from 0.69 to 0.71. 

```
   "react": "18.2.0",
   "react-native": "0.71.14",
```

I was trying to update the related packages including @react-navigation:

```
    "@react-navigation/core": "^6.4.10",
    "@react-navigation/material-bottom-tabs": "^6.2.19",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "3.18.0",
```
However, on startup of the app, I get the following error:

```
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

This error is located at:
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by SignedOutStack)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by SignedOutStack)
    in SignedOutStack
    in ThemedComponent (created by withTheme(SignedOutStack))
    in withTheme(SignedOutStack) (created by App)
    in Provider (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in ThemeProvider (created by Provider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Wuji(RootComponent), js engine: hermes
```

I've tried to the following solution https://reactnavigation.org/docs/7.x/troubleshooting/#im-getting-an-error-requirenativecomponent-rncsafeareaprovider-was-not-found-in-the-uimanager But it hasn't fixed the issue. 

Any suggestions? Or does anyone have a list of a combination of versions that I can try out specifically for react-native 0.71.

Thanks

**Comment by khlling** [comment]
Turns out this was an issue with some other packages which weren't up to date. Nothing to do with this package. I did a

`npm i` 

I usually use yarn which hides the conflicting peer dependencies. But npm shows these conflicts and I worked through them to get the right versions for everything.

**Comment by hank619** [comment]
For those who donesn't work even if react-native-safe-area-context is added to package.json, pls try yarn remove @react-native-community/cli in case you have already installed an older version of @react-native-community/cli so react-native config won't analysis the react-native-screeens library properly.

No worry, @react-native-community/cli is automatically imported by react-native so won't cause any error.

Relevant code are [here](https://github.com/react-native-community/cli/blob/6eb95951d9a49114e723d887f7e5223f7fe5f4c9/packages/cli-platform-android/native_modules.gradle#L417)
