### ISSUE TITLE
Mock should use @jest/globals

### ISSUE THREAD

**Issue by trajano** [th3rdwave/react-native-safe-area-context#458]
https://github.com/th3rdwave/react-native-safe-area-context/blob/main/jest/mock.tsx has an implied `jest` it should use `@jest/globals`  as per https://jestjs.io/docs/getting-started#type-definitions as per the note about it

> @types/jest is a third party library maintained at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest), hence the latest Jest features or versions may not be covered yet. Try to match versions of Jest and @types/jest as closely as possible. For example, if you are using Jest 27.4.0 then installing 27.4.x of @types/jest is ideal.

**Comment by jacobp100** [comment]
Fancy doing a PR?
