### ISSUE TITLE
(RN 0.73.0) The following build commands failed: CompileC ... 

### ISSUE THREAD

**Issue by Medkhat** [th3rdwave/react-native-safe-area-context#460]
Hi there!
I just upgraded my project to latest version of RN (073.0)

After pod install I ran the build, but I got an error like this:

> The following build commands failed:
> 	CompileC /Users/user/Library/Developer/Xcode/DerivedData/AwesomeProject-agucnlkgassozxgjpelvmoxkzqle/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-safe-area-context.build/Objects-normal/arm64/RNCSafeAreaViewShadowNode.o /Users/user/Documents/Projects/mobile/AwesomeProject/node_modules/react-native-safe-area-context/common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-safe-area-context' from project 'Pods')
> (1 failure)

Does anyone know the reason why?

**Comment by Medkhat** [comment]
I created a new project and reinstalled all packages with the new version and moved all project files to the new project. So, there is no build cache in this project.

**Comment by jacobp100** [comment]
It’s probably not working on 0.73 with the new architecture then. If you want to take a look at it, it would be really appreciated. There’s only two of us that maintain this library, and I’m not using the new architecture

**Comment by Medkhat** [comment]
Before the update, I had version 0.72.7 and I also had the new architecture enabled there.

**Comment by AlirezaHadjar** [comment]
Yeah, I am experiencing the same with 0.73 and the new architecture.

<img width="1244" alt="Screenshot 2023-12-07 at 12 20 43 PM" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/57192409/e3e30eea-1a0c-4357-a2cc-0662ea6fabaf">

**Comment by ikimiler** [comment]
I had the same problem
![image](https://github.com/th3rdwave/react-native-safe-area-context/assets/13508482/d588a140-8dfd-4843-b6bd-c0d18c24ff3c)

**Comment by jacobp100** [comment]
Please try package version `4.8.0-rc.0`

**Comment by Medkhat** [comment]
@jacobp100 Thank you! Fixed)

**Comment by tnson1307** [comment]
> Please try package version `4.8.0-rc.0`

down-grade safe-area-context to this version worked for me, thanks so much

**Comment by jacobp100** [comment]
@tnson1307 does the latest 4.10.x work for you?

**Comment by khushal87** [comment]
Hey @jacobp100, I am on 4.10.7 and can confirm it doesn't work. Shall I downgrade?
<img width="1219" alt="Screenshot 2024-08-21 at 2 22 55 PM" src="https://github.com/user-attachments/assets/07f83822-e0dd-40de-84e0-a9f140d4b6df">

**Comment by khushal87** [comment]
Any update on this issue? The build still fails on the new architecture with version `4.11.0`.

**Comment by khushal87** [comment]
Hey @vonovak, this is still an issue on the latest version of the package.

**Comment by MrNaughtZero** [comment]
> Hey @vonovak, this is still an issue on the latest version of the package.

Did you find a solution?

**Comment by bear-ei** [comment]
0.76.0 already uses the new architecture by default, but the latest 4.14.* version still has this problem. I think the problem should be reopened.
