### ISSUE TITLE
Failed to build on iOS with new architecture (RN 0.72.8)

### ISSUE THREAD

**Issue by quocluongha** [th3rdwave/react-native-safe-area-context#463]
I encountered this error when building with new architecture:
<img width="1508" alt="image" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/80971410/7779e620-3546-420c-95b0-d31d7c047942">

**Comment by jacobp100** [comment]
The latest version only support 0.73 on the new architecture. Use an older version of this library, upgrade RN, or turn off the new architecture
