### ISSUE TITLE
SafeAreaProvider as root of screens

### ISSUE THREAD

**Issue by slavko-lukic** [th3rdwave/react-native-safe-area-context#467]
![Screenshot 2024-01-26 at 12 12 56](https://github.com/th3rdwave/react-native-safe-area-context/assets/87854709/d5120727-4208-44d8-af0b-6371add6c97a)

What does this part mean exactly?
Should safe area provider be at the route of every screen? I am using react navigation by the way

**Comment by tboba** [comment]
Hi @slavko-lukic, this means that every navigator that contains your screens should be wrapped with SafeAreaProvider.
**However**, I don't think this is necessary now. Currently, every screen is being wrapped with the SafeAreaProvider by default - see https://github.com/software-mansion/react-native-screens/blob/da15ee60af4291b7069bee3dbdf4d7d7e98e2feb/src/native-stack/views/NativeStackView.tsx#L474.
