### ISSUE TITLE
Doesn't account for notch on Pixel 7 in landscape mode

### ISSUE THREAD

**Issue by NiGhTTraX** [th3rdwave/react-native-safe-area-context#470]
### Code

```tsx
<SafeAreaProvider>
  <SafeAreaView style={{ flex: 1, backgroundColor: "blue" }}>
    <View>
      <Text>Hello world</Text>
    </View>
  </SafeAreaView>
</SafeAreaProvider>
```

```json
"expo": "50.0.7",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.73.4",
"react-native-safe-area-context": "4.8.2",
```

### Result

I tested it in the emulator and on the real device:

<img width="795" alt="image" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/485061/8a1ab36d-3a68-4622-8b43-6d9b122e84c7">

**Comment by balazsgerlei** [comment]
I think this is an emulator problem as I was able to test your sample code on both a _Pixel 7 emulator_ with _device skin_ enabled and a real _Pixel 7_ (running _Android 14_) and I only experience what you screenshot with the _emulator_. Also, on the emulator, _pre-installed_ and system apps like _Messages_ and _Settings_ demonstrate the same issue.

Are you sure you experience the same on a real device? Also, would you look at pre-installed apps on the emulator, are they displayed incorrect too?

**Comment by NiGhTTraX** [comment]
You're right, I can't reproduce it anymore on the real device. I must have been doing something else wrong and then simplified my example too much. Sorry for the trouble.

**Comment by balazsgerlei** [comment]
There is defintely something weird going on with the Pixel 7 emulator I think its display cutout emulation is buggy. The same worked fine on a Pixel 6 even though it has a similar cutout, but content goes under it on the Pixel 7.

**Comment by balazsgerlei** [comment]
Interesting, I tried out other emulator variants and the only incorrect one I found is the Pixel 7 image with Android 13 (API 33) with Google Play. Both the Android 14 Google Play image and the  Android 13 image without Google Play simulates the cutout correctly... I might report this to Google if I find time for it.
