### ISSUE TITLE
issues with xcode 15.3

### ISSUE THREAD

**Issue by sameerhamid** [th3rdwave/react-native-safe-area-context#486]
my project was setup with xcode 14.3 and MACOS 13.4(ventura). now i am using xcode 15.3 on MACOS 14.4(Sonoma). now without any changes in code, i am getting this error:
1. No member named 'CompactValue' in namespace 'facebook::yoga'; did you mean simply 'CompactValue'?
2. 'Style' (aka 'unsigned char') is not a class, namespace, or enumeration

if anybody faced this issue. please help

**Comment by jacobp100** [comment]
Have you tried updating your version of react native along with your other dependencies?

**Comment by jacobp100** [comment]
Closing because there's not a library issue here - but shout if you're stuck
