### ISSUE TITLE
Build Failures in React Native New Architecture - Chip M Apple

### ISSUE THREAD

**Issue by phucph1998** [th3rdwave/react-native-safe-area-context#487]
System:
  OS: macOS 13.6.6
  CPU: (12) arm64 Apple M2 Pro
  Memory: 54.81 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 27.0.3
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

"react": "18.2.0",
"react-native": "0.72.4",
"react-native-safe-area-context": "4.8.0-rc.0",

<img width="1132" alt="Screenshot 2024-04-08 at 22 20 51" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/54024031/220d2ce4-dc9a-442e-831d-aead165ad115">
<img width="1149" alt="Screenshot 2024-04-08 at 22 20 39" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/54024031/0bb0cffa-5774-4d84-9675-c1ae599d55b8">

}

**Comment by huextrat** [comment]
Support for 0.74 + new arch is coming with v4.10.0+ 

https://github.com/th3rdwave/react-native-safe-area-context/releases/tag/v4.10.0-rc.0
