### ISSUE TITLE
Android build error in React Native 0.74

### ISSUE THREAD

**Issue by gabrielmaldi** [th3rdwave/react-native-safe-area-context#491]
```
Task :react-native-safe-area-context:compileReleaseKotlin FAILED
e: file:///{project}/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:17:63 Type mismatch: inferred type is Map<String, Any>? but Any was expected
```

<img width="1050" alt="image" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/3728897/5be271a4-7c78-4940-b4ec-7ea3b59d3330">

**Comment by yuhao965472200** [comment]
I solved it this way!
![Uploading WechatIMG51.jpg…]()


private fun getInitialWindowMetrics(): Map<String, Any> {
      val decorView = reactApplicationContext.currentActivity?.window?.decorView as ViewGroup?
      val contentView = decorView?.findViewById<View>(android.R.id.content) ?: return emptyMap()
      val insets = getSafeAreaInsets(decorView)
      val frame = getFrame(decorView, contentView)
      return mapOf(
          "insets" to (insets?.let { edgeInsetsToJavaMap(it) } ?: emptyMap()),
          "frame" to (frame?.let { rectToJavaMap(it) } ?: emptyMap())
      )
  }

**Comment by yuhao965472200** [comment]
I solved it this way!
![WechatIMG51](https://github.com/th3rdwave/react-native-safe-area-context/assets/86100818/e6905c53-c90d-4c38-9c94-968d404529cd)


private fun getInitialWindowMetrics(): Map<String, Any> {
val decorView = reactApplicationContext.currentActivity?.window?.decorView as ViewGroup?
val contentView = decorView?.findViewById(android.R.id.content) ?: return emptyMap()
val insets = getSafeAreaInsets(decorView)
val frame = getFrame(decorView, contentView)
return mapOf(
"insets" to (insets?.let { edgeInsetsToJavaMap(it) } ?: emptyMap()),
"frame" to (frame?.let { rectToJavaMap(it) } ?: emptyMap())
)
}

**Comment by chucongqing** [comment]
they fixed it in  https://github.com/th3rdwave/react-native-safe-area-context/blob/996ec119ffd8e39cbbd542032066db2f5204ef42/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt#L15

**Comment by FernandoAOborges** [comment]
I did one patch. If anyone need. 
[react-native-safe-area-context+4.9.0.patch](https://github.com/th3rdwave/react-native-safe-area-context/files/15075356/react-native-safe-area-context%2B4.9.0.patch)

**Comment by SumitSharmaJii** [comment]
> I did one patch. If anyone need. [react-native-safe-area-context+4.9.0.patch](https://github.com/th3rdwave/react-native-safe-area-context/files/15075356/react-native-safe-area-context%2B4.9.0.patch)

On new arch getting 

[11/13] Building CXX object CMakeFiles/appmodules.dir/Users/sumit/Documents/Lastest74/android/app/build/generated/rncli/src/main/jni/rncli.cpp.o
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /Users/sumit/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -C \
        /Users/sumit/Documents/Lastest74/android/app/.cxx/Debug/5lr4e2t2/arm64-v8a \
        appmodules \
        react_codegen_safeareacontext
    from /Users/sumit/Documents/Lastest74/android/app

**Comment by SumitSharmaJii** [comment]
@FernandoAOborges @chucongqing @yuhao965472200 did you tried on new architecture?

**Comment by mlazari** [comment]
Updating to `"react-native-safe-area-context": "4.10.0-rc.2"` fixed this issue for me (`newArchEnabled=false`).

**Comment by Riyad-Arafat** [comment]
`npm i react-native-safe-area-context@4.10.0-rc.2`
I installed `4.10.0-rc.2` version and it worked fine

**Comment by SumitSharmaJii** [comment]
> @FernandoAOborges @chucongqing @yuhao965472200 did you tried on new architecture?

"react-native-safe-area-context": "4.10.0-rc.2" works for new arch

**Comment by jsp1024** [comment]
"react-native-safe-area-context": "4.10.0-rc.2" library works fine in RN ver.0.74.0

**Comment by janicduplessis** [comment]
I was waiting for the official release to make 4.10 the lastest version, will try to do that today.
