### ISSUE TITLE
RN 0.74.0: Type mismatch: inferred type is Map<String, Any>? but Any was expected

### ISSUE THREAD

**Issue by tapz** [th3rdwave/react-native-safe-area-context#493]
After upgrading to RN 0.74.0 the Android build fails with the following error. I'm using version 4.9.0.

`/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:17:63 Type mismatch: inferred type is Map<String, Any>? but Any was expected`

**Comment by tapz** [comment]
Seems to be fixed in 4.10.0-rc.2

**Comment by najumasad** [comment]
thanks @tapz @florismettey 

npm install `react-native-safe-area-context@4.10.1` worked for me on `react-native 0.74.1`
