### ISSUE TITLE
SafeAreaView seems to fail on Expo when new arch is enabled

### ISSUE THREAD

**Issue by chriszs** [th3rdwave/react-native-safe-area-context#496]
Repro: https://github.com/chriszs/test-expo-app/pull/4

Before enabling new arch:

<img width="868" alt="Screenshot 2024-05-14 at 4 17 36 PM" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/1103467/31903a2c-eba6-4500-9076-83b6db006cc9">

After:

<img width="987" alt="Screenshot 2024-05-14 at 4 10 43 PM" src="https://github.com/th3rdwave/react-native-safe-area-context/assets/1103467/e27f9ad5-d360-4a82-b3d0-4d927e350142">

This is with 4.10.1.

**Comment by AptypTheKing** [comment]
Try to adjust edges

**Comment by jacobp100** [comment]
Did you put in a `SafeAreaProvider` at the top level?

**Comment by jacobp100** [comment]
You need to put a safe area provider inside each screen (RNSScreen)

**Comment by RohovDmytro** [comment]
Confirming. Adding a new provider to each screen does not help either. Proper edges are included.

**Comment by jacobp100** [comment]
I think we still have a few bugs with the new arch. I’m not sure any of the maintainers are using the new arch. If you’d like to take a stab at it we’d happily review and merge PRs. Otherwise I’d recommend holding off upgrading to the new arch

**Comment by AptypTheKing** [comment]
I'm using New Arch and it's working fine there

**Comment by chriszs** [comment]
Likely fixed in ce8aa20a5206da0520f20847f162653f8d6eb23e, but I haven't had a chance to verify yet.

**Comment by chriszs** [comment]
Yeah, looks like my reproduction no longer fails as of 4.10.5. Closing.

**Comment by martinezguillaume** [comment]
Yes it is working fine in `4.10.7`
I had this problem in `4.10.1`

**Comment by ghulamhussainjoyo** [comment]
`import { PropsWithChildren } from "react";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";

function CustomSafeArea({ children }: PropsWithChildren) {
  return (
    <SafeAreaProvider>
      <SafeAreaView style={{ flex: 1 }}>{children}</SafeAreaView>
    </SafeAreaProvider>
  );
}

export default CustomSafeArea;
`

/// usage --->


`import { StyleSheet, View } from "react-native";
import CustomSafeArea from "@/components/CustomSafeArea";

export default function HomeScreen() {
  return (
    <CustomSafeArea>
      <View
        style={{
          flex: 1,
          borderWidth: 1,
          borderColor: "black",
          backgroundColor: "orange",
        }}
      ></View>
    </CustomSafeArea>
  );
}`

**Comment by ghulamhussainjoyo** [comment]
I found same problem. SafeAreaView is not working in new architecture here is what I do:

<img width="590" alt="Screenshot 2024-09-28 at 12 18 39 PM" src="https://github.com/user-attachments/assets/82f476fa-ccae-40bf-95ef-311fdfd3f737">


usage :

<img width="499" alt="Screenshot 2024-09-28 at 12 20 23 PM" src="https://github.com/user-attachments/assets/32b528f0-28ca-449f-8305-b5c407fdfeab">

**Comment by mo-fouad** [comment]
please guys remember to rebuild after upgrading to new versions.
