### ISSUE TITLE
Conflicting recommendations in documentation

### ISSUE THREAD

**Issue by toppsdown** [th3rdwave/react-native-safe-area-context#510]
Hey there, I'm just getting started with this library and there's some conflicting documentation between React Navigation and the Readme.

[React Navigation documentation](https://reactnavigation.org/docs/handling-safe-area/):
_The react-native-safe-area-context library also exports a SafeAreaView component. While it works on Android, it also has the same issues related to jumpy behavior when animating. So we recommend always using the useSafeAreaInsets hook instead and avoid using the SafeAreaView component._

[README:](https://github.com/th3rdwave/react-native-safe-area-context?tab=readme-ov-file#consumers)
_SafeAreaView is the preferred way to consume insets. This is a regular View with insets applied as extra padding or margin. It offers better performance by applying insets natively and avoids flickers that can happen with the other JS based consumers._

_useSafeAreaInsets offers more flexibility, but can cause some layout flicker in certain cases. Use this if you need more control over how insets are applied._

My plan was to just wrap the whole app in a safe area view, but the React nav docs say not to do this. However, I did find [an issue from 2 years ago](https://github.com/th3rdwave/react-native-safe-area-context/issues/219#issuecomment-1169245221) with a custom SafeAreaView which uses the hooks.

Given that it's 2 years later, what's the current recommended way to use safe area views? Can I wrap the whole app in it?

**Comment by jacobp100** [comment]
Assume anything React Navigation says about this project is wrong. They don’t use the library in the best way. We tried to discuss how they should go about fixing it - because we get a lot of issues filed here about their bugs - but they don’t want to make any changes.

**Comment by toppsdown** [comment]
Ok thanks. So in your opinion it's totally fine to wrap the whole app in a SafeAreaView?

**Comment by jacobp100** [comment]
What does your app look like?

**Comment by toppsdown** [comment]
@jacobp100 
<img width="406" alt="image" src="https://github.com/user-attachments/assets/47ae113f-ec7a-4285-b008-0733c2892660">

**Comment by jacobp100** [comment]
You probably want the header and the bottom bars each to be their own SAV with the correct edges set. Otherwise you won’t be able to recolour them correctly
