### ISSUE TITLE
* What went wrong: Execution failed for task ':react-native-safe-area-context:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction >

### ISSUE THREAD

**Issue by souna23** [th3rdwave/react-native-safe-area-context#518]
* What went wrong:
Execution failed for task ':react-native-safe-area-context:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction >

react native :  0.75.0-rc.7

"react-native-safe-area-context": "^4.10.8",

kotlinVersion = "1.9.24"

**Comment by waqas-tr** [comment]
@WoLewicki Any idea about 0.75 version support

**Comment by jacobp100** [comment]
It's an RC. Re-open if it's still the same in a release version of 0.75

**Comment by waqas-tr** [comment]
@jacobp100 The issue is safe-area-context is not compatible with kotlinVersion = "1.9.24"
and in react-native version 0.75 kotlin version is updated, so you need to check the issue for future support

**Comment by WoLewicki** [comment]
The PR making it work is already on main: https://github.com/th3rdwave/react-native-safe-area-context/commit/c29b877aaba10759977d6564c1658acadc4017be, but we need a new version with it.

**Comment by souna23** [comment]
> Currently if anyone wants to run on react-native version 0.75 have to update following code `padding.getType()` and `margin.getType()` to `padding.type` and `margin.type`
> 
> in following locations `android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt:146` `android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt:166:20`

the error is still appearing, should i wait for the next version ?

**Comment by jacobp100** [comment]
@souna23 are you on the latest version now?

**Comment by souna23** [comment]
The issue is gone with the latest version, thank you

**Comment by PrajaRavi** [comment]
@Samama-Zargham  i am also getting the same error but this now not solving this issue
