### ISSUE TITLE
Unresolved reference: getType

### ISSUE THREAD

**Issue by mensonones** [th3rdwave/react-native-safe-area-context#520]
I was creating a simple project using react native **0.75.1** with react-native-safe-area-context **4.10.8** and when I tried to run the project I got the error: Unresolved reference: getType

The error points to

e: /node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt:146:21 Unresolved reference: **getType**
e: /node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt:166:20 Unresolved reference: **getType**

![image](https://github.com/user-attachments/assets/87866638-3030-402e-a03d-460b320a68a5)

When analyzing the Dynamic interface, it does not have the method in question, but rather the **type** property

![image](https://github.com/user-attachments/assets/e71967d3-7e87-4315-9428-3450191d7226)

The **getType** method has been removed as of the following commit: https://github.com/facebook/react-native/commit/5e31b45fc7bea37ecb3703fac6b2abaccae2cbae

After changing **getType** to **type**, I can follow

![image](https://github.com/user-attachments/assets/adbf602a-5c89-4ccb-b3ee-86ec435844b5)

**Comment by Romick2005** [comment]
[It is already in the main branch](https://github.com/th3rdwave/react-native-safe-area-context/commit/c29b877aaba10759977d6564c1658acadc4017be), but just not released.

**Comment by mensonones** [comment]
> [It is already in the main branch](https://github.com/th3rdwave/react-native-safe-area-context/commit/c29b877aaba10759977d6564c1658acadc4017be), but just not released.

nice! 
I hadn't seen it! Thanks
