### ISSUE TITLE
[TS]: Error for withSafeAreaInsets due to @types/react forwardRef update

### ISSUE THREAD

**Issue by akuul** [th3rdwave/react-native-safe-area-context#526]
Hello, 

just bringing awareness here that due to [@types/react^18.3.5](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f3052d979fdf41749d43a1f6abea993763f83e21) and changes made to the forwardRef function, `withSafeAreaInsets` is throwing a Typescript error.

```js
Argument of type '(props: T, ref: React.Ref<unknown>) => React.JSX.Element' is not assignable to parameter of type 'ForwardRefRenderFunction<unknown, PropsWithoutRef<T>>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'PropsWithoutRef<T>' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'PropsWithoutRef<T>'.
```
     
 I have patched T to use `PropsWithoutRef<T> `that resolves the issue, but this is temporary solution as it is not compatible with `@types/react^18.3.4`

**Comment by abrah4mr** [comment]
Same error here, is there any solution to this @janicduplessis?

**Comment by jacobp100** [comment]
If you can submit a PR that fixes the issue without breaking older versions, we’ll merge. Otherwise, you could also open an issue on the react types package as to why it broke other packages

**Comment by abrah4mr** [comment]
Also, is happening on older versions too, I have currently the 4.7.4 in my project.
