### ISSUE TITLE
no safe area value available issue

### ISSUE THREAD

**Issue by hakanuyysal** [th3rdwave/react-native-safe-area-context#529]
I was using my react native application in version 0.70.7. Then I created an empty project and transferred the project's src and configs to the new project with the latest version 0.75. I solved the errors and I get a successful build, but when the app is opened, I get the following error.

[No safe area insets value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app. - how can i ressolve this error?]

package.json:
{
  "name": "AlohaLive",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@eva-design/eva": "^2.2.0",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-clipboard/clipboard": "^1.14.1",
    "@react-native-community/datetimepicker": "^8.2.0",
    "@react-native-community/netinfo": "^11.3.2",
    "@react-native-firebase/analytics": "^20.4.0",
    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/auth": "^20.4.0",
    "@react-native-firebase/crashlytics": "^20.4.0",
    "@react-native-firebase/database": "^20.4.0",
    "@react-native-firebase/messaging": "^20.4.0",
    "@react-native-firebase/perf": "^20.4.0",
    "@react-native-google-signin/google-signin": "^12.2.1",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/elements": "^1.3.31",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "@reduxjs/toolkit": "^2.2.7",
    "@rnhooks/keyboard": "^1.1.0",
    "@sentry/react-native": "^5.29.0",
    "@ui-kitten/components": "^5.3.1",
    "@ui-kitten/eva-icons": "^5.3.1",
    "add": "^2.0.6",
    "axios": "^1.7.4",
    "deprecated-react-native-prop-types": "^5.0.0",
    "he": "^1.2.0",
    "i18next": "^23.12.3",
    "lodash": "^4.17.21",
    "lottie-ios": "4.4.1",
    "lottie-react-native": "^6.7.2",
    "moment": "^2.30.1",
    "moment-duration-format": "^2.3.2",
    "prop-types": "^15.8.1",
    "react": "18.3.1",
    "react-i18next": "^15.0.1",
    "react-native": "0.75.1",
    "react-native-adjust": "^4.38.1",
    "react-native-agora": "^4.3.2",
    "react-native-bootsplash": "^6.1.1",
    "react-native-code-push": "^8.3.1",
    "react-native-config": "^1.5.3",
    "react-native-device-info": "^11.1.0",
    "react-native-dialog": "^9.3.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fbsdk-next": "^13.0.0",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "^2.18.1",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-google-mobile-ads": "^14.2.2",
    "react-native-hyperlink": "^0.0.22",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-localize": "^3.2.1",
    "react-native-mmkv": "^2.12.2",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-orientation-locker": "^1.7.0",
    "react-native-pager-view": "^6.3.4",
    "react-native-permissions": "^4.1.5",
    "react-native-purchases": "^8.0.1",
    "react-native-reanimated": "^3.15.0",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
    "react-native-snackbar": "^2.6.2",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-store-review": "^0.4.3",
    "react-native-svg": "^15.5.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.1.0",
    "react-native-walkthrough-tooltip": "^1.6.0",
    "react-redux": "^9.1.2",
    "redux": "^5.0.1",
    "socket.io-client": "^4.7.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-decorators": "^7.24.7",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.75.1",
    "@react-native/eslint-config": "0.75.1",
    "@react-native/metro-config": "0.75.1",
    "@react-native/typescript-config": "0.75.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}

app.js:
import * as Sentry from '@sentry/react-native';
import React, {useEffect} from 'react';
import {LogBox} from 'react-native';
import FlashMessage from 'react-native-flash-message';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {SafeAreaProvider} from 'react-native-safe-area-context'; // Eklenen import

import {CustomMessage} from './src/components/CustomMessage';
import {IS_STAGING} from './src/config';
import {AdjustContainer} from './src/containers/AdjustContainer';
import {FirebaseContainer} from './src/containers/FirebaseContainer';
import {AlohaAxiosContainer} from './src/containers/AlohaAxiosContainer';
import {AlohaNavigationContainer} from './src/containers/AlohaNavigationContainer';
import {useAppSettings} from './src/hooks/useAppSettings';
import {useScreenOrientation} from './src/hooks/useScreenOrientation';
import {useSentry} from './src/hooks/useSentry';
import {TooltipProvider} from './src/provider/TooltipProvider/TooltipProvider';
import i18next from 'i18next';

if (!__DEV__ && !IS_STAGING) {
  Sentry.init({
    dsn: 'https://2813850b8425484eaa4208520e1ddb96@o4504071042891776.ingest.sentry.io/4504071044071424',
    tracesSampleRate: 0.1,
    enableWatchdogTerminationTracking: false,
    enableAutoPerformanceTracing: false,
  });
}

const ignoreWarns = ['ViewPropTypes will be removed'];
const warn = console.warn;
console.warn = (...arg) => {
  for (let i = 0; i < ignoreWarns.length; i++) {
    if (arg[0].startsWith(ignoreWarns[i])) {
      return;
    }
  }
  warn(...arg);
};
LogBox.ignoreLogs(ignoreWarns);

const App = () => {
  useAppSettings();
  useScreenOrientation();
  useSentry();
  const renderCustomContent = message => {
    return <CustomMessage message={message} />;
  };

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <SafeAreaProvider>
        <TooltipProvider>
          <AdjustContainer>
            <FirebaseContainer>
              <AlohaAxiosContainer>
                <AlohaNavigationContainer />
              </AlohaAxiosContainer>
              <FlashMessage
                position="top"
                MessageComponent={renderCustomContent}
              />
            </FirebaseContainer>
          </AdjustContainer>
        </TooltipProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
};

export default Sentry.wrap(App);

<img width="384" alt="Ekran Resmi 2024-09-07 12 09 42" src="https://github.com/user-attachments/assets/958763d0-b7c1-4c59-996a-f660aca108ba">

**Comment by jacobp100** [comment]
Follow the instructions given in the error

**Comment by hakanuyysal** [comment]
The app.js file I shared already complies with the instructions in the error, but it still shows the same error.

**Comment by hakanuyysal** [comment]
app.js , im sharing again:



import * as Sentry from '@sentry/react-native';
import React, {useEffect} from 'react';
import {LogBox} from 'react-native';
import FlashMessage from 'react-native-flash-message';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {SafeAreaProvider} from 'react-native-safe-area-context'; // Eklenen import

import {CustomMessage} from './src/components/CustomMessage';
import {IS_STAGING} from './src/config';
import {AdjustContainer} from './src/containers/AdjustContainer';
import {FirebaseContainer} from './src/containers/FirebaseContainer';
import {AlohaAxiosContainer} from './src/containers/AlohaAxiosContainer';
import {AlohaNavigationContainer} from './src/containers/AlohaNavigationContainer';
import {useAppSettings} from './src/hooks/useAppSettings';
import {useScreenOrientation} from './src/hooks/useScreenOrientation';
import {useSentry} from './src/hooks/useSentry';
import {TooltipProvider} from './src/provider/TooltipProvider/TooltipProvider';
import i18next from 'i18next';

if (!__DEV__ && !IS_STAGING) {
  Sentry.init({
    dsn: 'https://2813850b8425484eaa4208520e1ddb96@o4504071042891776.ingest.sentry.io/4504071044071424',
    tracesSampleRate: 0.1,
    enableWatchdogTerminationTracking: false,
    enableAutoPerformanceTracing: false,
  });
}

const ignoreWarns = ['ViewPropTypes will be removed'];
const warn = console.warn;
console.warn = (...arg) => {
  for (let i = 0; i < ignoreWarns.length; i++) {
    if (arg[0].startsWith(ignoreWarns[i])) {
      return;
    }
  }
  warn(...arg);
};
LogBox.ignoreLogs(ignoreWarns);

const App = () => {
  useAppSettings();
  useScreenOrientation();
  useSentry();
  const renderCustomContent = message => {
    return <CustomMessage message={message} />;
  };

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <SafeAreaProvider>
        <TooltipProvider>
          <AdjustContainer>
            <FirebaseContainer>
              <AlohaAxiosContainer>
                <AlohaNavigationContainer />
              </AlohaAxiosContainer>
              <FlashMessage
                position="top"
                MessageComponent={renderCustomContent}
              />
            </FirebaseContainer>
          </AdjustContainer>
        </TooltipProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
};

export default Sentry.wrap(App);

**Comment by hakanuyysal** [comment]
<img width="641" alt="Ekran Resmi 2024-09-08 17 59 19" src="https://github.com/user-attachments/assets/a6905ea6-b98d-4579-879d-58e1963811a4">

**Comment by jacobp100** [comment]
You probably have multiple copies of the library. If you're using yarn, run `yarn why react-native-safe-area-context`
