### ISSUE TITLE
[iOS 18] [Question] iPhone 16 Pro/Pro Max support

### ISSUE THREAD

**Issue by FrederickEngelhardt** [th3rdwave/react-native-safe-area-context#532]
Hi, reaching out to verify if there has been additional support / validation for iOS 18 and iPhone 16 Pro / Pro Max devices. 

Not super familiar with how safe-area-context is grabbing these values so wanted to verify that iPhone16 variants are stable.
- I did test this with a iPhone 16 Pro Max simulator and saw it work as expected for top area (top-bar) insets.

Noticed regressions related to iPhone 16s in other libraries that hardcoded sizing of devices. E.g. the deprecated [react-native-iphone-x-helper](https://www.npmjs.com/package/react-native-iphone-x-helper). So if you are using that lib switch here asap!

**Comment by jacobp100** [comment]
Should be fine
