### ISSUE TITLE
A small part of the bottom area is blocked, Inconsistency with official react behavior

### ISSUE THREAD

**Issue by huhu415** [th3rdwave/react-native-safe-area-context#536]
if use `import { Image, StyleSheet, Platform, SafeAreaView } from 'react-native';`will be 
<img width="477" alt="截屏2024-10-13 17 52 32" src="https://github.com/user-attachments/assets/ceac77c2-545a-4ead-b7c3-770a37525e2b">

use react-native-safe-area-context will be 
<img width="480" alt="截屏2024-10-13 17 53 23" src="https://github.com/user-attachments/assets/32dc7241-6524-4897-ae2c-9a0ec1c5d836">
A small part of the bottom area is blocked

**Comment by jacobp100** [comment]
Sorry there’s not enough information to even give you any pointers about what might be wrong

**Comment by huhu415** [comment]
i can give some， donot close😳
