### ISSUE TITLE
Incorrect insets.bottom value on some initial renders on iPhone X

### ISSUE THREAD

**Issue by mic-css** [th3rdwave/react-native-safe-area-context#54]
I have an Expo app with a `SafeAreaContext` declared at the top-level and using the `useSafeArea` hook in a nested component.

About half the time on an iPhone X, `insets.bottom` will return 0 instead of 34 on the first render.

Console logging `insets` shows initial and subsequent render:
```
Object {
  "bottom": 0,
  "left": 0,
  "right": 0,
  "top": 44,
}
Object {
  "bottom": 34,
  "left": 0,
  "right": 0,
  "top": 44,
}
```

Current setup:
```js
"expo": "^36.0.0",
"react": "16.9.0",
"react-native-safe-area-context": "0.7.2",
```

Note: this is also happening in `v0.6.0` which is the version obtained from running `expo install react-native-safe-area-context`

**Comment by mic-css** [comment]
My current workaround `setState` and `useEffect` to update the value when it changes:

```js
function MyComponent() {
  const insets = useSafeArea()
  const [bottomPadding, setBottomPadding] = useState(insets.bottom)

  useEffect(() => {
    setBottomPadding(insets.bottom)
  }, [insets])
}
```

**Comment by compojoom** [comment]
I can also confirm that this happens. Sometimes it returns 0 the first time and on second render 34

**Comment by LMestre14** [comment]
I updated the project with the latest version (3.0.7) and this problem disappeared for me.

If after updating you still have the issue verify if you're mapping the SafeAreaProvider on top of you application.

Note: after updating if you are using SafeAreaConsumer, you should change to SafeAreaInsetsContext.Consumer

**Comment by alexandersandberg** [comment]
I'm still having this issue with the latest version (`3.1.8`), using `<SafeAreaProvider>`.

**Comment by yolpsoftware** [comment]
Also having this issue. On the iPhone 11, both simulator and actual device, `useSafeAreaInsets` sometimes returns the correct `48, 0, 34, 0`, sometimes `48, 0, 0, 0`, and sometimes even `0, 0, 0, 0`.

**Comment by kesha-antonov** [comment]
Same issue on iPhone 11

**Comment by juergengunz** [comment]
same issue for me

**Comment by enesozturk** [comment]
Not sure this is the same issue but as you mentioned, on some iPhone models, bottom value is different. I use bottom value for styling but iPhone 11 is cutting button a little bit. (So button goes under the keyboard). It is ok for other models (iP8, iP 11 Pro, iP 12 etc.)

![Screen Shot 2021-04-27 at 17 09 29](https://user-images.githubusercontent.com/19428358/116256499-e897a380-a77b-11eb-9614-154d5dad3c2e.png)

**Comment by jacobp100** [comment]
This is for v3 of the library, and we're on v4. Please re-open a new issue if you're still facing issues

**Comment by mehdinourollah** [comment]
I'm on v4 and still facing the issue ...
`"react-native-safe-area-context": "^4.2.4"`
