### ISSUE TITLE
Avoid front camera on s24 ultra

### ISSUE THREAD

**Issue by AndrianarivoAlpha** [th3rdwave/react-native-safe-area-context#545]
![20241101_041043133_iOS](https://github.com/user-attachments/assets/02f39f2a-8c33-40de-b311-7f99518319df)
Hello everyone, as on photo, I don't know why SafeAreaView does not avoid this front camera on device like s24 ultra?
 Who can help me please?
 
 I have app.json like:
"androidStatusBar": {
      "translucent": true,
      "hidden": false,
      "backgroundColor": "#1E5A76",
      "barStyle": "light-content"
    },
    "androidNavigationBar": {
      "visible": "sticky-immersive"
    },

**Comment by r-obeen** [comment]
Hey @AndrianarivoAlpha I have this issue as well... Seems like you fixed it... Can you help and explain how ?

**Comment by AndrianarivoAlpha** [comment]
I have just deleted 
"androidNavigationBar": {
"visible": "sticky-immersive"
},
