### ISSUE TITLE
Fatal error: 'react/renderer/components/safeareacontext/Props.h' file not found

### ISSUE THREAD

**Issue by batu0b** [th3rdwave/react-native-safe-area-context#557]
I encountered a build issue while using react-native-safe-area-context in my project. The Android build fails with the following error:
`fatal error: 'react/renderer/components/safeareacontext/Props.h' file not found
#include <react/renderer/components/safeareacontext/Props.h>`

Environment:
React Native version: 0.76.3
react-native-safe-area-context version: 4.12.0 | latest | 4.4.0
Build tool: Android Gradle Plugin
Operating System: macOs

**Comment by Hibbanur-Rahman** [comment]
I am  facing same issue

**Comment by Qdafengzi** [comment]
![Xnip2024-12-12_10-58-04](https://github.com/user-attachments/assets/d810aae8-beaa-4c68-a9b4-a70e327b376e)

**Comment by Qdafengzi** [comment]
@batu0b Did you solve it ？

**Comment by batu0b** [comment]
> @Hibbanur-Rahman @batu0b Did you solve it ？
unfortunately I couldn't figure it out, so I moved my project to expo.

**Comment by batu0b** [comment]
works fine for me with the latest update
