### ISSUE TITLE
After installing the library app is getting crashed .

### ISSUE THREAD

**Issue by SupriyaGo** [th3rdwave/react-native-safe-area-context#58]
package.json

{
"version": "0.0.1",
  "private": true,
  "rnpm": {
    "assets": [
      "./Assets/Fonts"
    ]
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/cli": "^4.1.0",
    "@react-navigation/bottom-tabs": "^5.0.5",
    "@react-navigation/drawer": "^5.0.5",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-screens": "^2.0.0-beta.7",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by RnbWd** [comment]
same here on iOS, I can't start the app

**Comment by janicduplessis** [comment]
Can you provide a stack trace for the crash? Going to close for now, feel free to reopen with more info if this is still an issue.
