### ISSUE TITLE
Usage in combination with React Navigation

### ISSUE THREAD

**Issue by Guuz** [th3rdwave/react-native-safe-area-context#60]
React Navigation already applies the insets for a header and bottom tabs. The react native SafeAreaView doesn't apply double insets in this case.
This lib however does. So you can't use it together with React Navigation screens.

Blue = safe area
Red = content
![image](https://user-images.githubusercontent.com/810327/75756259-a36f1180-5d30-11ea-8f25-adbb8c4c2b41.png)

Or am i missing something?

**Comment by Kyonru** [comment]
Well, since it is inside a screen. I had to use `paddingTop: 0`. I guess you just use it out of the box when you are not using the react-navigation header.

**Comment by Guuz** [comment]
@Kyonru but the whole points of a SafeAreaView is that it works on all orientations and with all insets.
Some devices might have an inset on the sides. And some just at the top. But if you ignore it because of using a header, and you rotate the device, the insets are on one of the sides. And it all falls apart...

**Comment by satya164** [comment]
How does setting `paddingTop: 0` affect insets on sides after rotation? It only disables the top padding (due to top inset).

**Comment by Guuz** [comment]
@satya164 I think you're right. Dunno what i was thinking yesterday ^_^ my apologies.

**Comment by sarmad1995** [comment]
@Guuz 
I had a similar issue, it seems like `react-native-safe-area-context` adds some padding by default 
I removed the bottom space with `paddingBottom: 0`.

**Comment by janicduplessis** [comment]
The old implementation of SafeAreaView did not consider its position on the screen and always added insets. One workaround is to add another provider inside your screen. In v2.0 SafeAreaView is reimplemented in native and is basically the same as the one in React Native so this issue should not happen anymore.
