### ISSUE TITLE
insets.top changed during render on Android with <Statusbar translucent={true} />

### ISSUE THREAD

**Issue by wong2** [th3rdwave/react-native-safe-area-context#61]
```
const insets = useSafeArea()

return (
  <Layout>
    <Statusbar translucent={true} />
    <Content />
  </Layout>
)
```

`insets.top` will change during render(from 0 to the right value), which makes my element position jump

**Comment by satya164** [comment]
You are making the statusbar translucent in render, so it's going to happen after the component mounts which will then trigger event with new size. It seems expected. You need to set translucent statusbar in your native theme to avoid this.

**Comment by wong2** [comment]
What do you mean by native theme?

**Comment by lumberman** [comment]
What do you mean by native theme?

**Comment by davidgovea** [comment]
@wong2 @lumberman 'native theme' means setting the values in XML using android theme values

see: https://developer.android.com/reference/android/R.attr#windowTranslucentStatus

In my case, I specified this behavior in `android/app/src/main/res/values/styles.xml`:

```xml
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    ...
        <item name="android:windowTranslucentStatus">true</item> <!-- Added this -->
```
With this style, content extends under the statusbar, and the safe area `insets` properly include the status bar.
