### ISSUE TITLE
Combined use with react-native-navigation

### ISSUE THREAD

**Issue by zabojad** [th3rdwave/react-native-safe-area-context#65]
I use `react-native-navigation` and when using this lib (especially when wrapping my page components in a `SafeAreaProvider`), my topbar title components renders blank.

If I remove `SafeAreaProvider `, the topbars render fine again but I caannot use this lib...

Anyone using `react-native-navigation` with this lib?

**Comment by parius** [comment]
@zabojad Share your code. In my case adding "style={{flex:1}}" to SafeAreaView solved the same problem.

**Comment by janicduplessis** [comment]
You should just have to add SafeAreaProvider at the top of the app, you can check the examples in the repo it has working examples with react-navigation.

**Comment by hugo-chq** [comment]
@janicduplessis I think `react-native-navigation` as opposed to `react-navigation` doesn't support wrapping the entire app in one context provider, instead each screen needs to be wrapped.

There's a chance this can cause a one frame flicker when each screen component mounts, but that's probably be a different issue

more info from https://wix.github.io/react-native-navigation/docs/third-party-react-context 

> LIMITATION
As RNN screens are not part of the same component tree, updating the values in the shared context does not trigger a re-render across all screens. However you can still use the React.Context per RNN screen component tree.

**Comment by magrinj** [comment]
@janicduplessis With `react-native-navigation` you can't put `SafeAreaProvider` at the top of the app, as each screen is a native one ! So each screen must have is own provider.
