### ISSUE TITLE
React native 0.59

### ISSUE THREAD

**Issue by ansarikhurshid786** [th3rdwave/react-native-safe-area-context#67]
I could not found correction version for react native 0.59.10. can anyone help me?

**Comment by janicduplessis** [comment]
I assume the issue is with AndroidX? Except for that the latest version should work on 0.59. If not please provide more info.

See https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-507010053

Seems like you can add a postinstall script and run `jetifier -r`
