### ISSUE TITLE
useSafeAreaInsets has no exported member

### ISSUE THREAD

**Issue by Glassig** [th3rdwave/react-native-safe-area-context#72]
Hi, I tried using this in my TypeScript project, but I get the error: 
`Module '"<PROJECT_PATH>/node_modules/react-native-safe-area-context/lib/typescript/src"' has no exported member 'useSafeAreaInsets'.ts(2305)`

For anyone with similar problem, it worked to use `useSafeArea` instead.

**Comment by janicduplessis** [comment]
Hey! What version are you using? `useSafeAreaInsets` was added in v1.0.0.

**Comment by Glassig** [comment]
Oh, I am using 0.7.3, but I didn't choose version. I installed normally 3 days ago. Weird that I didn't get the latest version.
Thank you for your response, I will upgrade.
