### ISSUE TITLE
Dont work with styled-components & typescript

### ISSUE THREAD

**Issue by Ciberusps** [th3rdwave/react-native-safe-area-context#74]
When i install `react-native-safe-area-context` or `react-native-safe-area-view` `styled-components` types dont work, when i remove both packages and `npm ci` all ok.
Not sure but looks like there is no overrides of `styled-components` types in package, mb reason react & react-native in `peerDependencies` with version "*"?
![image](https://user-images.githubusercontent.com/14001879/81876670-e6006600-958b-11ea-82bd-c07778ba222f.png)

**Comment by janicduplessis** [comment]
I'm using styled-components and typescript with this library and don't have an issue, I don't see anything in the package that could cause a problem.
