### ISSUE TITLE
Unable to resolve module InitialWindowSafeAreaInsets

### ISSUE THREAD

**Issue by mrousavy** [th3rdwave/react-native-safe-area-context#75]
### Description

On startup the following error is shown:

![Simulator Screen Shot - iPhone 11 - 2020-05-14 at 11 07 37](https://user-images.githubusercontent.com/15199031/81915926-7ca44580-95d3-11ea-8ab3-307fcda7bd80.png)

Making the whole app unusable.

A temporary workaround: I went into the `node_modules/react-native-safe-area-context/src/` folder and manually created the file `InitialWindowSafeAreaInsets.tsx` with no content.

### Steps to reproduce

I'm not sure if this happened after I upgraded to the newest react native version, as this error was shown a week after upgrading. Also it might be because of upgrading to the newest react navigation library.

### Versions

> `package.json`

```json
"@react-navigation/bottom-tabs": "^5.4.2",
"@react-navigation/native": "^5.3.0",
"@react-navigation/stack": "^5.3.3",
"react": "16.13.1",
"react-native": "0.62.2",
"react-native-safe-area-context": "^1.0.0",
"@react-native-community/masked-view": "^0.1.10",
"react-native-screens": "^2.7.0",
```

### System

> `react-native info`

```sh
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 14.63 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by janicduplessis** [comment]
Can you try clearing the metro cache (npm run start --reset-cache)? This file doesn't exist anymore in v1.0.0 (https://github.com/th3rdwave/react-native-safe-area-context/blob/master/src/index.tsx).

**Comment by z4o4z** [comment]
@janicduplessis it helps, thanks!
