### ISSUE TITLE
1.0.0 pod fails to install because v1.0.0 tag is missing

### ISSUE THREAD

**Issue by jpaas** [th3rdwave/react-native-safe-area-context#76]
I just tried upgrading to to 1.0.0 but the cocoapod install failed with
```
warning: Could not find remote branch v1.0.0 to clone.
fatal: Remote branch v1.0.0 not found in upstream origin
```

Sure enough there is no `v1.0.0` tag. There is a `1.0.0` tag and a `v1.0.0-0` tag.

**Comment by janicduplessis** [comment]
Oups not sure why I didn't get this error when updating my app. I had the tag locally but didn't push it. It should be fixed now.
