### ISSUE TITLE
Android: False change of the bottom inset.

### ISSUE THREAD

**Issue by DenysZP** [th3rdwave/react-native-safe-area-context#79]
Hello everyone. After updating to version 1.0.2, I noticed strange behavior on Android.
After I open the keyboard, I get the bottom indent with the wrong value, then the correct one comes.
Example:
```
{left: 0, bottom: 0, right: 0, top: 0}
{left: 0, bottom: 0, right: 0, top: 0}
{left: 0, bottom: 249.3333282470703, right: 0, top: 0}
{left: 0, bottom: 249.3333282470703, right: 0, top: 0}
{left: 0, bottom: 0, right: 0, top: 0}
```
Keyboard mode:
`android:windowSoftInputMode="adjustResize"`

**Comment by janicduplessis** [comment]
What version of android are you using?

**Comment by DenysZP** [comment]
@janicduplessis I am using 7 and 9 versions.
My build config:
```
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
```

**Comment by janicduplessis** [comment]
Ok I figured out what the issue is, will release a fix soon. Thanks for reporting this!

**Comment by janicduplessis** [comment]
Can you test 2.0.0-beta.1 it should fix the issue.

**Comment by DenysZP** [comment]
@janicduplessis Everything works perfectly. Thank you for your work!
