### ISSUE TITLE
Support FLAG_LAYOUT_NO_LIMITS

### ISSUE THREAD

**Issue by brunolemos** [th3rdwave/react-native-safe-area-context#8]
I'm trying to achieve a full transparent NavigationBar background. It seems a way to do it is using `getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);`. 

But when I add this code `react-native-safe-area-context` seems to have no effect anymore. Is this expected? Or is it possible to support it? Any other way to have full transparency without using `FLAG_LAYOUT_NO_LIMITS`?

### Default behaviour

![Screenshot_1567364113](https://user-images.githubusercontent.com/619186/64080979-0378f280-ccd1-11e9-8c9b-17dd68e42860.png)

### FLAG_TRANSLUCENT_NAVIGATION

![image](https://user-images.githubusercontent.com/619186/64081014-8ac66600-ccd1-11e9-81ab-0939bbffe377.png)

### FLAG_LAYOUT_NO_LIMITS

![Screenshot_1567364075](https://user-images.githubusercontent.com/619186/64080988-18ee1c80-ccd1-11e9-8bf3-c3b724571fd9.png)

[Code](https://gist.github.com/brunolemos/ec886065b695d54ba25af7de47475c90)

**Comment by brunolemos** [comment]
Got the desired behavior by setting:

```java
getWindow().setStatusBarColor(getResources().getColor(android.R.color.transparent));
getWindow().setNavigationBarColor(getResources().getColor(android.R.color.transparent));
getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
```

![Screenshot_1567366517](https://user-images.githubusercontent.com/619186/64081414-df201480-ccd6-11e9-928c-169f6d78dbdf.png)

**Comment by crutchcorn** [comment]
@brunolemos did you ever figure out how to change the nav button colors to dark?

Side note, is there any way to support FLAG_LAYOUT_NO_LIMITS as the original issue portrayed?

**Comment by crutchcorn** [comment]
Also, while using your code _does_ allow me to draw under the navigation button:

```
getWindow().setStatusBarColor(getResources().getColor(android.R.color.transparent));
getWindow().setNavigationBarColor(getResources().getColor(android.R.color.transparent));
getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
```

My status bar was not transparent and was a single color that tried to match the system background color. Any ideas how to get the status bar transparent to draw content under it?

**Comment by crutchcorn** [comment]
I had issues getting a fully transparent navbar working for me. I eventually figured it out and wrote a blog post about it:

https://unicorn-utterances.com/posts/draw-under-navbar-using-react-native/
