### ISSUE TITLE
SafeAreaView "edges" prop not working

### ISSUE THREAD

**Issue by choibles** [th3rdwave/react-native-safe-area-context#81]
Hey – loving the library! Working great here with react-navigation 5.

Just tried using the `edges` prop and it doesn't appear to be working.

I wasn't sure if the docs meant to literally to pass an array of which edges ('top', 'left', etc.) to apply insets to, so I checked out the source (which appears to confirm this assumption).

While I was there, noticed something. Though I'm not super familiar w/ TS, it seems like in `src/SafeAreaView.tsx`, that the constants for the `TOP`, `RIGHT`, `BOTTOM`, and `LEFT` should be different bits if we're accumulating them in the reduce function below? Not sure if related or even a good observation.

Anyway, thanks. Let me know if I can help.

**Comment by jacobp100** [comment]
Can you paste the JSX you're using? In the [example](https://github.com/th3rdwave/react-native-safe-area-context/blob/master/example/src/SafeAreaViewExample.tsx), it's used like,

```js
<SafeAreaView edges={['top', 'right', 'bottom', 'left']}>
  ...
</SafeAreaView>
```

The source you're looking at is for the web - and those constants are only internal and are for perf

**Comment by choibles** [comment]
Thanks for the swift reply. Am in fact using that exact JSX. To make sure I wasn't going crazy, I actually replaced my App.js with the entirety of the example you linked, and removed `'bottom'` from the `edges` array, and it still did not work. (no difference in the red/blue views)

I'm running v1.0.2 right now. I tried upgrading to the latest (2.0.1) just now, and it fixes this problem with `edges`, though per #82 I'm seeing the same stutters as the SafeAreaView appears to be loading in. For our use case, we can live without some of the edges, but the stutter is the precise reason why we switched to this library when we upgraded to react-navigation 5.

So I'm back down to 1.0.2 and still experiencing this issue. I understand if it won't be fixed for the old version – we can wait and upgrade to v2 once the stutter is addressed. Thanks again.

**Comment by jacobp100** [comment]
What platform were you using, and was the view touching the edges you were putting the safe area edges on?

**Comment by choibles** [comment]
On a real iPhone X, iOS v13.4.1. Using`react-native` v0.61.5.

Yes – to eliminate potential variables I actually ran a clean, new project, pasting in the example you linked verbatim into App.js. With `react-native-safe-area-context` v1.0.2 changing the `edges` prop did nothing to the example.

**Comment by jacobp100** [comment]
Can you try again with v3? There was some issues in v2 where an edge had to be touching the edge of the screen to have that safe area applied, but v3 fixes that.

This repo now has a edges test app (see [this pr](https://github.com/th3rdwave/react-native-safe-area-context/pull/85)) - and that worked on iOS and Android

**Comment by choibles** [comment]
Success on `v3.0.2`!

**Comment by choibles** [comment]
Actually, perhaps I spoke too soon. The `edges` prop was already working in v2 for my use case (don't think my edges were inset from the screen). The only reason I hadn't upgraded was because of #82 , which was higher-priority for us. The flickering per #82 is still present in `v3.0.2`.

**Comment by jacobp100** [comment]
Is this still an issue then? We can continue the flickering discus in that issue

**Comment by choibles** [comment]
I'd consider it resolved, insofar as the latest versions of the library don't experience the issue. Thanks for the time!
