### ISSUE TITLE
mode = padding | margin | border

### ISSUE THREAD

**Issue by jacobp100** [th3rdwave/react-native-safe-area-context#83]
What do you think about allowing customisation of the property that the edges are assigned to? I have some separator components that in the current version I might format as,

```js
<SafeAreaView edges={['left']} style={{ paddingLeft: 12 }}>
  <View style={{ height: 1, backgroundColor: 'grey' }} />
<SafeAreaView>
```

But if I could use margins, it would look like this,

```js
<SafeAreaView
  mode="margin"
  edges={['left']}
  style={{ marginLeft: 12, height: 1, backgroundColor: 'grey' }}
/>
```

This wouldn't be a breaking change and I can do the work to implement it - I just wanted to get a go-ahead first!

**Comment by janicduplessis** [comment]
Yea sounds like a good idea, feel free to work on that and I'll review it!

**Comment by jacobp100** [comment]
This is implemented now
