### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in UI Manager.

### ISSUE THREAD

**Issue by karimcambridge** [th3rdwave/react-native-safe-area-context#88]
Title says it all, upgraded from 1.0.0, was getting some import issue so I did `npm cache clear --force && expo start -c`

Could it be similar to https://github.com/react-native-community/react-native-picker/issues/45 ?

```
Expo CLI 3.21.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

**Comment by satya164** [comment]
You need to use expo compatible versions with `expo install react-native-safe-area-context`. You can't upgrade to latest versions.

**Comment by karimcambridge** [comment]
Okay

**Comment by DianaKoenraadt** [comment]
Is there a list of expo compatible versions somewhere?

**Comment by Desintegrator** [comment]
same in Android with RN cli
