### ISSUE TITLE
Invariant Violation after updating to 2.x.x

### ISSUE THREAD

**Issue by florinleu** [th3rdwave/react-native-safe-area-context#89]
Hello,
I'm using expo 37.0.2 and after updating react-native-safe-area-context from 1.x.x to 2.x.x it throws the following error when running:

Invariant Violation: requireNativeComponent: “RNCSafeAreaProvider” was not found in the UIManager

Any idea would be appreciated.
<img width="377" alt="Q1A5O" src="https://user-images.githubusercontent.com/1244065/83042877-d2083a00-a04a-11ea-8ef9-aed57ab3dfb6.png">

**Comment by satya164** [comment]
You can't user 2.0 with expo. You need to install expo compatible version with `expo install react-native-safe-area-context`

**Comment by rtanri** [comment]
run this:
$ cd ios && pod install

**Comment by rohankeskar19** [comment]
> run this:
> $ cd ios && pod install

What should I do for android??

**Comment by akunal1** [comment]
I faced this issue while integrating Navigation . adding `"react-native-safe-area-context": "0.7.3"` worked for me in Android.

**Comment by enestatli** [comment]
> > run this:
> > $ cd ios && pod install
> 
> What should I do for android??

I solved this by stopping the app and doing ```react-native link``` 

"react-native-safe-area-context": "^3.1.7",
"react": "16.13.1",
"react-native": "0.63.2",

**Comment by jeremyfrancis** [comment]
I am having this issue on 3.1.7, 3.1.8, and 3.1.9. Have not tested other versions. Have pod installed. Not sure why this is happening.
