### ISSUE TITLE
Changelog for v3

### ISSUE THREAD

**Issue by crutchcorn** [th3rdwave/react-native-safe-area-context#94]
While v2 and v1 had great changelogs, v3 (and its current patch updates) do not seem to currently have a changelog. This would be hugely advantageous to have as a consumer. Thanks so much for your hard work on the project!

**Comment by janicduplessis** [comment]
Thanks for the reminder, this slipped off my mind. https://github.com/th3rdwave/react-native-safe-area-context/releases/tag/v3.0.0
