### ISSUE TITLE
Unable to resolve "./SafeAreaContext" from "node_modules/react-native-safe-area-context/src/index.tsx"

### ISSUE THREAD

**Issue by Mahlyjan** [th3rdwave/react-native-safe-area-context#95]
I have been getting this error when I am trying to do stack navigation in react-native: 
**Unable to resolve "./SafeAreaContext" from "node_modules/react-native-safe-area-context/src/index.tsx"**

App.tsx file:
```
import Navigator from './routes/MainStack';

export default function App() {
  return <Navigator />;
}
```

MainStack.tsx

```
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import GameScreen from '../views/Game';
import LoginScreen from '../views/LogIn';

const screens = {
  LoginScreen: {
    screen: LoginScreen,
  },
  GameScreen: {
    screen: GameScreen,
  },
};

const MainStack = createStackNavigator(screens);

export default createAppContainer(MainStack);
```

Thank you for your help!

**Comment by Glassig** [comment]
I also have this problem, hope it get's fixed soon!

**Comment by janicduplessis** [comment]
This is usually a packager caching issue, make sure the file node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx exists and try starting the react-native packager with the `—reset-cache` flag

**Comment by Benjyben** [comment]
> This is usually a packager caching issue, make sure the file node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx exists and try starting the react-native packager with the `—reset-cache` flag

And if it don't exists ?

**Comment by Benjyben** [comment]
I juste change the line 3 at node_modules/react-native-safe-area-context/src/index.tsx : 
`import { EdgeInsets as EdgeInsetsT, InsetChangedEvent } from './SafeArea.types';`

With a '.ts' in the end of the file path like this : 
`import { EdgeInsets as EdgeInsetsT, InsetChangedEvent } from './SafeArea.types.ts';`

And it worked for me ......

**Comment by israelnojr** [comment]
> I juste change the line 3 at node_modules/react-native-safe-area-context/src/index.tsx :
> `import { EdgeInsets as EdgeInsetsT, InsetChangedEvent } from './SafeArea.types';`
> 
> With a '.ts' in the end of the file path like this :
> `import { EdgeInsets as EdgeInsetsT, InsetChangedEvent } from './SafeArea.types.ts';`
> 
> And it worked for me ......

worked for me thanks

**Comment by Glassig** [comment]
@janicduplessis  solution, ie resetting all the caches, worked for me.

**Comment by proteche** [comment]
@Glassig resetting all the caches, worked for me also.

**Comment by Mahlyjan** [comment]
Yes this worked for me too! Thank you!

**Comment by junioruche49** [comment]
> expo start -c

This worked for me thanks.
