### ISSUE TITLE
IOS：debug ：I got black screen ,maybe some erro happen

### ISSUE THREAD

**Issue by Mollet-Yuan** [th3rdwave/react-native-safe-area-context#96]
react native :0.62.2 ,
react-native-safe-area-context:3.0.2

**Comment by petrbela** [comment]
@Mollet-Yuan If you want other people to help you, you need to describe what happens and when; ideally by creating a reproducible example on [CodeSandbox](https://codesandbox.io/) or similar, or pasting your code here. Without it, there's not much we can do.

**Comment by jacobp100** [comment]
This is for v3 of the library, and we're on v4. Please re-open a new issue if you're still facing issues
