### ISSUE TITLE
hiding/unhiding StatusBar causes problems with the SafeAreaView offset.

### ISSUE THREAD

**Issue by schumannd** [th3rdwave/react-native-safe-area-context#99]
This issue seems to be related to #23 

When hiding and then unhiding the statusbar inbetween screen, the SafeAreaVIew offset changes once, but does not change back after unhiding the statusbar. This results in content being covered by the statusbar. Is there a way to console.log or something the changes happening in the SafeAreaView depending on the StatusBar?

**Comment by janicduplessis** [comment]
Can you post in #23 with any additional info that can help like the device you are using and the version of this library.
